import type { ContentSource, ArticleSection } from "@/lib/types";

export interface Article {
  slug: string;
  title: string;
  excerpt: string;
  content: ArticleSection[];
  date: string;
  category: string;
  readTime: number;
  relatedQuizSlug: string;
  author?: string;
  authorBio?: string;
  sources?: ContentSource[];
  lastReviewedAt?: string;
  disclaimer?: string;
}

export const allArticles: Article[] = [
  {
    slug: "historia-das-copas-do-mundo-curiosidades",
    title: "História das Copas do Mundo: O Que os Bastidores Revelam",
    excerpt:
      "De boicotes diplomáticos a estádios construídos às pressas: como dinheiro, política e rivalidades moldaram 96 anos de Copas.",
    category: "Esportes",
    date: "2026-06-15",
    readTime: 7,
    relatedQuizSlug: "quanto-voce-sabe-sobre-a-copa-2026",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "FIFA.com — History of the FIFA World Cup", url: "https://www.fifa.com/en/tournaments/mens/worldcup", organization: "FIFA", accessedAt: "2026-09-20" },
      { label: "Goldblatt, D. (2008). The Ball is Round: A Global History of Football", organization: "Penguin Books", accessedAt: "2026-09-20" },
      { label: "Britannica — FIFA World Cup", url: "https://www.britannica.com/sports/World-Cup-football", organization: "Encyclopædia Britannica", accessedAt: "2026-09-20" },
      { label: "Bellos, A. (2002). Futebol: The Brazilian Way of Life", organization: "Bloomsbury Publishing", accessedAt: "2026-09-20" },
    ],
    lastReviewedAt: "2026-09-20",
    content: [
      { text: "A Copa do Mundo costuma ser contada como uma sequência de gols, títulos e heróis em campo. Mas a história real do torneio é inseparável do que aconteceu fora dele: os boicotes que esvaziaram edições inteiras, as decisões políticas que escolheram sedes, as crises financeiras que quase cancelaram competições e os bastidores que explicam por que a Copa é o que é hoje. Este artigo conta a história do torneio pelo ângulo que raramente aparece nos compilados de curiosidades — o que moldou a Copa antes de a bola rolar." },
      { heading: "1930: um torneio que quase não existiu", text: "A ideia de um campeonato mundial de futebol foi debatida por quase três décadas antes de se concretizar. Jules Rimet, presidente da FIFA desde 1921, enfrentou resistência sistemática das federações europeias, que preferiam as Olimpíadas como vitrine. Quando o Uruguai se ofereceu para sediar e bancar todas as despesas — inclusive passagens e hospedagem dos times visitantes —, Rimet finalmente teve seu torneio. O problema: apenas 4 das 56 federações europeias aceitaram participar. A viagem de navio até Montevidéu durava 15 dias, e clubes europeus se recusaram a liberar jogadores por dois meses. O rei Romeno Carol II selecionou pessoalmente os convocados de seu país e garantiu que seus empregadores manteriam os salários durante a ausência — sem isso, a Romênia não teria ido." },
      { heading: "1950: o trauma que redesenhou a identidade brasileira", text: "O Maracanazo — a derrota do Brasil para o Uruguai na final de 1950 — não foi apenas um resultado esportivo. O jornalista e historiador Alex Bellos, em 'Futebol: The Brazilian Way of Life', argumenta que o evento provocou uma crise de identidade nacional num país que havia apostado o Maracanã (o maior estádio do planeta, construído às pressas para a ocasião) como símbolo de modernidade. A derrota gerou reflexões sobre raça e culpa que mancharam carreiras: o goleiro Barbosa e o zagueiro Bigode, ambos negros, foram publicamente responsabilizados. Barbosa carregou o estigma até a morte, em 2000, dizendo que no Brasil 'a pena máxima são 30 anos de prisão, mas eu fui condenado à perpétua'. A camisa branca da seleção foi abandonada — o amarelo-canário foi adotado em 1954 justamente para apagar a memória." },
      { heading: "A taça que sumiu — duas vezes, por razões opostas", text: "A Taça Jules Rimet foi roubada em março de 1966, em Londres, poucos meses antes da Copa inglesa. A polícia fracassou na busca; quem encontrou o troféu foi Pickles, um cão vira-lata de South Norwood, farejando debaixo de um arbusto. O dono de Pickles recebeu £6.000 de recompensa (mais que o prêmio dos jogadores campeões), e o cachorro virou celebridade nacional. Em 1983, já em posse permanente do Brasil desde o tricampeonato de 1970, a taça foi roubada novamente — desta vez no Rio de Janeiro, de uma vitrine da CBF protegida por um vidro à prova de bala na frente e madeira compensada atrás. Nunca foi recuperada. A principal teoria é que foi derretida e vendida como ouro." },
      { heading: "1978 e 2022: quando a geopolítica escolhe a sede", text: "A Copa de 1978 na Argentina foi disputada durante uma ditadura militar que usou o torneio como ferramenta de propaganda — o estádio do River Plate ficava a menos de 2 km de um dos centros de detenção e tortura do regime. O historiador David Goldblatt, em 'The Ball is Round', documenta como a junta militar investiu US$ 700 milhões na infraestrutura do evento para projetar uma imagem de estabilidade e modernidade. Décadas depois, a Copa de 2022 no Qatar reacendeu o mesmo debate: um país de 2,8 milhões de habitantes, sem tradição futebolística, gastou estimados US$ 220 bilhões — o evento esportivo mais caro da história — e enfrentou denúncias documentadas sobre condições de trabalho dos operários migrantes que construíram os estádios." },
      { heading: "7 a 1: a partida que o futebol brasileiro tentou explicar", text: "Na semifinal da Copa de 2014, a Alemanha marcou 5 gols contra o Brasil em 18 minutos no Mineirão — um colapso tático e emocional sem precedente nesse nível de competição. O placar final de 7 a 1 não é apenas um resultado; é um ponto de inflexão. A seleção brasileira entrou em campo sem Neymar (machucado) e sem Thiago Silva (suspenso), mas o problema era mais profundo: a estrutura tática de Luiz Felipe Scolari dependia de contenção emocional que ruiu no primeiro gol. A CBF levou anos para reconstruir um projeto técnico sério. O 7 a 1 também inaugurou uma era de memes como linguagem de luto coletivo — o brasileiro processou a derrota com humor porque não havia outro instrumento à altura do absurdo." },
      { heading: "De 32 para 48: a Copa de 2026 como experimento", text: "A expansão para 48 seleções em 2026 é a maior mudança de formato desde 1998. Com 104 jogos distribuídos entre 16 cidades de três países (EUA, México e Canadá), o torneio será um teste logístico sem precedente. A decisão de expandir foi aprovada em 2017 sob a presidência de Gianni Infantino e divide opiniões: defensores argumentam que mais países terão chance de participar (Copas anteriores excluíam sistematicamente África e Ásia); críticos apontam que mais jogos diluem a qualidade e aumentam o desgaste físico dos atletas. A FIFA projeta receita recorde de US$ 11 bilhões, quase o dobro de 2022." },
      { heading: "O que a história ensina", text: "A Copa do Mundo nunca foi apenas sobre futebol. Cada edição carrega as marcas do momento político, econômico e cultural em que aconteceu — das viagens de navio de 1930 aos estádios climatizados do deserto em 2022. Entender os bastidores não diminui o encanto do torneio; amplia. Os gols fazem a emoção, mas são as decisões fora do campo que determinam onde, como e por quem a Copa é jogada." },
    ],
  },
  {
    slug: "como-funcionam-os-testes-de-personalidade",
    title: "Como Funcionam os Testes de Personalidade",
    excerpt:
      "Entenda a psicologia por trás dos quizzes de personalidade e por que eles revelam tanto sobre quem somos.",
    category: "Psicologia",
    date: "2026-06-12",
    readTime: 6,
    relatedQuizSlug: "qual-cidade-brasileira-combina-com-voce",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Briggs Myers, I. & Myers, P. (1995). Gifts Differing", organization: "Davies-Black Publishing", accessedAt: "2026-07-12" },
      { label: "Marston, W. M. (1928). Emotions of Normal People", organization: "Kegan Paul", accessedAt: "2026-07-12" },
    ],
    lastReviewedAt: "2026-07-12",
    content: [
      { text: "Quem nunca fez um teste de personalidade na internet e ficou impressionado com a precisão do resultado? Seja para descobrir qual cidade combina com você ou qual personagem de série você seria, esses quizzes atraem milhões de pessoas todos os dias. Mas o que está por trás dessa fascinação? A resposta envolve psicologia, neurociência e um pouco de autoconhecimento." },
      { heading: "Origens na psicologia: de Jung ao MBTI", text: "Os testes de personalidade têm raízes na psicologia do início do século XX. Carl Jung, um dos fundadores da psicologia analítica, propôs que as pessoas possuem diferentes funções psicológicas dominantes — como pensamento, sentimento, intuição e sensação. Essa teoria inspirou o famoso teste MBTI (Myers-Briggs Type Indicator), criado na década de 1940 por Katharine Briggs e sua filha Isabel Myers, que classifica as pessoas em 16 tipos de personalidade." },
      { heading: "O modelo Big Five (OCEAN)", text: "Na psicologia moderna, o modelo mais aceito cientificamente é o dos Cinco Grandes Fatores, também chamado de Big Five ou OCEAN. Esse modelo avalia cinco dimensões fundamentais da personalidade: Abertura à experiência (curiosidade e criatividade), Conscienciosidade (organização e disciplina), Extroversão (sociabilidade e energia), Amabilidade (cooperação e empatia) e Neuroticismo (tendência à ansiedade e instabilidade emocional)." },
      { heading: "Como funcionam os quizzes online", text: "Mas e os quizzes de personalidade da internet — aqueles mais divertidos e informais? Eles funcionam com um mecanismo chamado mapeamento de perfis. Cada resposta que você dá acumula pontos para diferentes perfis predefinidos. Ao final, o perfil com mais pontos é o seu resultado. Embora não tenham o rigor de um teste clínico, eles usam princípios psicológicos reais para criar categorias que fazem sentido." },
      { heading: "O Efeito Barnum e a identificação com resultados", text: "Um fenômeno psicológico importante que explica por que nos identificamos tanto com os resultados é o Efeito Barnum, também chamado de Efeito Forer. Esse efeito descreve a tendência humana de aceitar descrições vagas e genéricas como extremamente precisas quando acreditamos que foram feitas especificamente para nós. É o mesmo princípio por trás dos horóscopos — as descrições são amplas o suficiente para que a maioria das pessoas se identifique." },
      { heading: "Testes como ferramenta de reflexão", text: "No entanto, isso não significa que os testes são inúteis. Bons testes de personalidade — mesmo os informais — podem servir como ferramentas de reflexão. Eles nos fazem pensar sobre nossas preferências, valores e comportamentos de uma forma lúdica. Um estudo publicado no Journal of Research in Personality mostrou que pessoas que refletem sobre seus traços de personalidade tendem a ter maior autoconsciência e inteligência emocional." },
      { heading: "Testes DISC e vocacionais", text: "Os testes DISC, muito usados em ambientes corporativos, classificam as pessoas em quatro perfis: Dominância, Influência, Estabilidade e Conformidade. Eles ajudam equipes a entender como cada membro se comunica e toma decisões. Já os testes vocacionais utilizam uma abordagem semelhante para sugerir carreiras compatíveis com os interesses e habilidades do indivíduo." },
      { heading: "Personalidade é mais do que um resultado", text: "A verdade é que nossa personalidade é complexa demais para ser resumida em um único resultado. Somos uma combinação fluida de traços que se manifestam de formas diferentes dependendo do contexto. Ainda assim, os testes de personalidade continuam sendo uma das formas mais populares e divertidas de explorar quem somos — ou pelo menos quem gostaríamos de ser." },
    ],
  },
  {
    slug: "melhores-jogadores-copa-2026",
    title: "Copa 2026: Como os Dados Apontam os Favoritos ao Título",
    excerpt:
      "Estatísticas de clubes, evolução tática e histórico em Copas: o que os números dizem sobre quem chega mais forte ao torneio de 48 seleções.",
    category: "Esportes",
    date: "2026-06-18",
    readTime: 8,
    relatedQuizSlug: "qual-artilheiro-historico-voce-e",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "FIFA.com — FIFA World Cup 26", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-09-20" },
      { label: "CIES Football Observatory — Weekly Post", url: "https://football-observatory.com/", organization: "CIES / Université de Neuchâtel", accessedAt: "2026-09-20" },
      { label: "Wilson, J. (2018). Inverting the Pyramid: The History of Football Tactics", organization: "Orion Publishing", accessedAt: "2026-09-20" },
      { label: "FBref — Football Statistics and History", url: "https://fbref.com/", organization: "Sports Reference", accessedAt: "2026-09-20" },
    ],
    lastReviewedAt: "2026-09-20",
    disclaimer: "Estatísticas e situação de clubes refletem o momento da publicação. Convocações, lesões e transferências podem alterar a participação dos atletas.",
    content: [
      { text: "Listas de 'melhores jogadores' antes de uma Copa costumam ser exercícios de torcida disfarçados de análise. Este artigo tenta algo diferente: usar dados de desempenho em clubes, métricas táticas e padrões históricos de Copas para identificar quem — e quais seleções — chegam ao torneio de 2026 com mais fundamento estatístico. Nenhum dado prevê o futuro, mas alguns indicadores separam expectativa de evidência." },
      { heading: "O que os dados de clube realmente dizem", text: "O CIES Football Observatory, ligado à Universidade de Neuchâtel (Suíça), publica semanalmente métricas de desempenho que vão além de gols e assistências. Dois indicadores se destacam para prever rendimento em seleções: participação em ações decisivas (gols + assistências + passes-chave por 90 minutos) e minutos jogados em competições de alta pressão (Champions League, fases eliminatórias). Jogadores que acumulam alta carga em ambos os indicadores tendem a manter desempenho sob pressão de Copa — o ambiente mais próximo de uma final de Champions em intensidade e exposição midiática." },
      { heading: "Mbappé e o paradoxo da velocidade", text: "Kylian Mbappé, aos 27 anos, chega à Copa com um perfil estatístico curioso. Suas métricas de finalização no Real Madrid (expected goals vs. gols reais) mostram eficiência acima da média, mas sua participação em construção caiu em relação ao período no PSG. Na prática, Mbappé se tornou mais letal e menos versátil — o que funciona no Real Madrid, onde Bellingham e Vinícius Jr. compartilham a criação, pode ser um problema na seleção francesa, que depende mais dele para construir jogadas. O hat-trick na final de 2022 prova que ele pode decidir qualquer jogo; a questão é se a França construiu um sistema à altura." },
      { heading: "A tese tática da Argentina: por que o coletivo supera o indivíduo", text: "A Argentina de Scaloni não tem o melhor jogador do torneio, mas pode ter o melhor sistema. Jonathan Wilson, em 'Inverting the Pyramid', argumenta que Copas são vencidas por equipes com identidade tática consolidada — e a Argentina é, estatisticamente, a seleção com mais tempo de trabalho contínuo sob o mesmo treinador entre as favoritas. Scaloni assumiu em 2018 e nunca saiu. O resultado: jogadores como Enzo Fernández, Julián Álvarez e Lautaro Martínez não precisam de adaptação — eles cresceram dentro do sistema. Dados do FBref mostram que a Argentina tem a maior taxa de conversão de posse em chances claras de gol entre as 10 primeiras do ranking FIFA." },
      { heading: "Vinícius Jr. e o fator emocional brasileiro", text: "Vinícius Júnior carrega uma pressão que transcende estatísticas. O Brasil não vence uma Copa desde 2002 — a maior seca desde que o país começou a ganhar, em 1958. Vini Jr. chegou ao patamar de melhor jogador do mundo em termos de dribles completados e ações em terço final (dados FBref, temporada 2025-26), mas seu desempenho pela seleção historicamente fica abaixo do rendimento no Real Madrid. A diferença não é técnica — é contextual. No Real, ele opera com companheiros que jogam juntos o ano inteiro; na seleção, os mecanismos táticos são reconstruídos a cada convocação. Se Dorival Jr. conseguir criar automatismos em tão pouco tempo de preparação, o Brasil tem argumento técnico para ir longe." },
      { heading: "A Alemanha como azarão com fundamento", text: "Florian Wirtz e Jamal Musiala formam a dupla criativa mais produtiva da Europa em termos de expected assists + progressive carries por 90 minutos. Wirtz, agora no Liverpool, acumulou experiência em eliminatórias de altíssima pressão na Premier League. Musiala, no Bayern, é o jogador com mais dribles bem-sucedidos da Bundesliga em 2025-26. A Alemanha, que decepcionou em 2018 e 2022, chega sem a pressão de favorita — e historicamente, isso ajuda: 4 dos 5 títulos mundiais foram conquistados quando os alemães não eram cotados como primeiro ou segundo favorito." },
      { heading: "O fator goleiro: estatisticamente decisivo em mata-mata", text: "Dados históricos mostram que, em fases eliminatórias de Copa, goleiros explicam uma parcela desproporcional do resultado. Desde 2002, o goleiro titular do campeão teve taxa de defesas acima de 78% no torneio. Alisson Becker (Brasil), Courtois (Bélgica) e Donnarumma (Itália) estão entre os goleiros com melhor expected goals prevented (diferença entre gols esperados e gols sofridos) nas últimas três temporadas europeias. Em jogos decididos por um gol de diferença — que representam mais de 60% das eliminatórias de Copa — o goleiro é frequentemente o jogador mais valioso em campo." },
      { heading: "O que as estatísticas não capturam", text: "Nenhuma métrica mede o que acontece quando 80 mil pessoas cantam o hino e o árbitro apita. A Copa é o único torneio onde jogadores de classe mundial jogam com companheiros que veem poucas vezes por ano, sob pressão de um país inteiro, em cidades que nunca visitaram, com fusos horários que desregulam o sono. Os dados apontam tendências, mas a Copa premia quem se adapta ao caos. E é exatamente isso que torna o torneio imprevisível — e irresistível." },
    ],
  },
  {
    slug: "curiosidades-mitologia-grega",
    title: "Curiosidades Sobre Mitologia Grega que Vão Te Surpreender",
    excerpt:
      "Explore fatos fascinantes sobre os deuses, heróis e monstros da mitologia grega que influenciam nossa cultura até hoje.",
    category: "Cultura",
    date: "2026-06-10",
    readTime: 6,
    relatedQuizSlug: "quiz-mitologia-grega",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Theoi Greek Mythology — Encyclopaedia", url: "https://www.theoi.com/", organization: "Theoi Project", accessedAt: "2026-07-12" },
      { label: "Britannica — Greek Mythology", organization: "Encyclopædia Britannica", accessedAt: "2026-07-12" },
    ],
    lastReviewedAt: "2026-07-12",
    content: [
      { text: "A mitologia grega é uma das tradições culturais mais ricas e influentes da história da humanidade. Seus deuses, heróis e monstros continuam presentes em filmes, livros, jogos e até no nosso vocabulário cotidiano. Mas existem muitos fatos sobre essas histórias antigas que são surpreendentes mesmo para quem acha que já conhece o tema." },
      { heading: "Zeus e suas transformações", text: "Zeus, o rei dos deuses do Olimpo, não era exatamente um exemplo de fidelidade. Segundo os mitos, ele teve dezenas de filhos com diversas deusas, ninfas e mortais. Héracles (Hércules, para os romanos), Perseu, Helena de Troia e Dionísio são apenas alguns de seus descendentes. Para se aproximar de seus interesses amorosos, Zeus se transformava em diversas formas: um cisne, um touro, uma chuva de ouro e até uma formiga. Hera, sua esposa e irmã, era famosa por sua fúria contra as amantes e os filhos ilegítimos do marido." },
      { heading: "O Cavalo de Troia não está na Ilíada", text: "O Cavalo de Troia, uma das histórias mais famosas da mitologia, não aparece na Ilíada de Homero. A narrativa do cavalo gigante de madeira usado como armadilha para invadir a cidade de Troia é contada em obras posteriores, como a Eneida de Virgílio e em fragmentos do Ciclo Épico. A Ilíada, na verdade, cobre apenas algumas semanas do décimo ano da Guerra de Troia, focando na ira de Aquiles contra Agamenon." },
      { heading: "O nascimento incomum de Atena", text: "Atena, a deusa da sabedoria e da estratégia, nasceu de uma forma bastante incomum: ela surgiu diretamente da cabeça de Zeus, já adulta e usando armadura completa. Segundo o mito, Zeus engoliu a titã Métis (a mãe de Atena) porque recebeu uma profecia de que um filho de Métis seria mais poderoso que ele. Quando sentiu uma terrível dor de cabeça, pediu a Hefesto que abrisse seu crânio com um machado, e Atena saltou para fora." },
      { heading: "A origem trágica do Minotauro", text: "O Minotauro, a criatura meio homem, meio touro que vivia no Labirinto de Creta, tem uma origem trágica. Poseidon enviou um touro branco magnifico ao rei Minos para que fosse sacrificado em sua honra. Quando Minos se recusou a sacrificar o animal por considerá-lo belo demais, Poseidon fez com que a rainha Pasífae se apaixonasse pelo touro. O Minotauro foi o resultado dessa união, e Minos mandou construir o Labirinto para esconder a criatura." },
      { heading: "Palavras que vieram da mitologia", text: "Muitas palavras que usamos hoje vêm diretamente da mitologia grega. 'Narcisismo' vem de Narciso, o jovem que se apaixonou pelo próprio reflexo. 'Pânico' deriva de Pã, o deus dos bosques que causava medo repentino nos viajantes. 'Eco' era o nome de uma ninfa condenada a repetir apenas as últimas palavras que ouvia. 'Atlas' era o titã condenado a sustentar o céu. E 'cronômetro' vem de Cronos, o titã do tempo." },
      { heading: "Deuses imperfeitos e castigos eternos", text: "Os gregos antigos não viam seus deuses como seres perfeitos e moralmente superiores — muito pelo contrário. Os deuses do Olimpo eram ciumentos, vingadores, vaidosos e frequentemente cruéis. Prometeu foi acorrentado a uma rocha e tinha seu fígado devorado por uma águia todos os dias (ele se regenerava à noite) como punição por ter dado o fogo aos humanos. Sísifo foi condenado a empurrar uma pedra montanha acima eternamente, e Tântalo ficou para sempre com fome e sede, cercado por água e frutos que se afastavam quando ele tentava alcançá-los." },
      { heading: "Por que a mitologia ainda importa", text: "A mitologia grega não é apenas uma coleção de histórias antigas — é um espelho da natureza humana. Os mitos exploram temas universais como amor, inveja, coragem, hubris e destino que continuam relevantes milhares de anos depois. Se você ficou curioso para testar o quanto sabe sobre esse universo fascinante, temos um quiz perfeito para você!" },
    ],
  },
  {
    slug: "verdade-ou-mito-maiores-mitos-sobre-saude",
    title: "Verdade ou Mito: Os Maiores Mitos Sobre Saúde",
    excerpt:
      "Descubra quais crenças populares sobre saúde são reais e quais não passam de mitos sem base científica.",
    category: "Saúde",
    date: "2026-06-08",
    readTime: 6,
    relatedQuizSlug: "verdade-ou-mito-edicao-saude",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "PubMed — National Library of Medicine", url: "https://pubmed.ncbi.nlm.nih.gov/", organization: "NIH/NLM", accessedAt: "2026-07-12" },
      { label: "Zhang, B. et al. (2020). Hyperactivation of sympathetic nerves drives depletion of melanocyte stem cells. Nature, 577, 676–681", organization: "Harvard University / Nature", accessedAt: "2026-07-12" },
    ],
    lastReviewedAt: "2026-07-12",
    disclaimer: "Este artigo tem finalidade informativa e educativa. As informações não substituem orientação médica profissional.",
    content: [
      { heading: "Crenças populares sob o microscópio", text: "Todos nós crescemos ouvindo conselhos de saúde passados de geração em geração: 'não saia com o cabelo molhado que você vai ficar gripado', 'comer manga com leite faz mal', 'estalar os dedos causa artrite'. Mas quantas dessas crenças são realmente verdadeiras? A ciência moderna já desmentiu muitas delas, e algumas respostas podem te surpreender." },
      { heading: "Cabelo molhado causa gripe?", text: "Mito: sair com o cabelo molhado causa gripe. Essa é uma das crenças mais populares do Brasil, mas a verdade é que gripes e resfriados são causados exclusivamente por vírus, não pelo frio ou pela umidade do cabelo. O que acontece é que, durante o inverno, as pessoas tendem a ficar mais tempo em ambientes fechados e com pouca ventilação, o que facilita a transmissão dos vírus. O cabelo molhado pode causar desconforto térmico, mas não tem relação direta com infecções respiratórias." },
      { heading: "Estalar os dedos causa artrite?", text: "Mito: estalar os dedos causa artrite. Esse mito é tão difundido que um médico chamado Donald Unger decidiu testar na própria pele. Durante mais de 60 anos, ele estalou os dedos de apenas uma das mãos todos os dias e comparou com a outra. O resultado? Nenhuma diferença. Ele publicou o estudo e até ganhou o prêmio Ig Nobel de Medicina em 2009. O som do estalo vem do colapso de bolhas de gás no líquido sinovial das articulações, e não causa danos permanentes." },
      { heading: "Ler no escuro prejudica a visão?", text: "Verdade: ler com pouca luz prejudica a visão — parcialmente. Ler em ambientes escuros não causa danos permanentes à visão, mas pode provocar fadiga ocular temporária, dores de cabeça e desconforto. Seus olhos precisam trabalhar mais para focar o texto, o que cansa a musculatura ocular. No entanto, estudos recentes mostram que a exposição prolongada à luz de telas em ambientes escuros pode contribuir para o desenvolvimento de miopia, especialmente em crianças." },
      { heading: "Manga com leite faz mal?", text: "Mito: comer manga com leite faz mal. Essa é uma lenda urbana tipicamente brasileira. Uma teoria popular atribui a origem ao período colonial, quando a combinação teria sido desencorajada para proteger o estoque de leite. Independentemente da origem, a afirmação não tem base científica: a mistura de manga com leite é perfeitamente segura e até nutritiva — pense em vitaminas e smoothies de manga." },
      { heading: "Estresse causa cabelos brancos?", text: "Verdade: o estresse pode causar cabelos brancos. Por muito tempo, essa crença foi considerada um mito, mas pesquisadores da Universidade de Harvard demonstraram em 2020 que o estresse ativa o sistema nervoso simpático e destrói as células-tronco responsáveis pela pigmentação dos fios de cabelo em camundongos. O estudo (Zhang et al., Nature, 2020) indicou que, uma vez que essas células são perdidas, o dano é permanente. Embora a pesquisa tenha sido conduzida em modelos animais, os mecanismos biológicos sugerem que o mesmo processo pode ocorrer em humanos." },
      { heading: "Café atrofia o crescimento?", text: "Mito: tomar café atrofia o crescimento. Essa crença se popularizou principalmente entre pais preocupados com seus filhos. Não existe nenhuma evidência científica de que a cafeína afete o crescimento. A altura é determinada principalmente pela genética e pela nutrição adequada durante a infância e adolescência. O café pode causar insônia e irritabilidade em crianças devido à sensibilidade à cafeína, mas não interfere no crescimento ósseo." },
      { heading: "Busque sempre evidências científicas", text: "A lição mais importante é sempre buscar informações baseadas em evidências científicas, em vez de aceitar crenças populares sem questionamento. A ciência evolui constantemente, e o que achávamos verdade ontem pode ser desmentido amanhã. Se você gostou de separar fatos de ficção, temos um quiz completo sobre mitos de saúde que vai testar todo o seu conhecimento!" },
    ],
  },
  {
    slug: "por-que-adoramos-quizzes-ciencia-da-diversao",
    title: "Por Que Adoramos Quizzes: A Ciência Por Trás da Diversão",
    excerpt:
      "Entenda por que quizzes são tão viciantes e o que a neurociência diz sobre o prazer de responder perguntas.",
    category: "Curiosidades",
    date: "2026-06-05",
    readTime: 5,
    relatedQuizSlug: "desafio-conhecimentos-gerais-8-perguntas",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Loewenstein, G. (1994). The psychology of curiosity. Psychological Bulletin, 116(1), 75–98", organization: "Carnegie Mellon University", accessedAt: "2026-07-12" },
      { label: "Tamir, D. & Mitchell, J. (2012). Disclosing information about the self is intrinsically rewarding. PNAS, 109(21), 8038–8043", organization: "Harvard University", accessedAt: "2026-07-12" },
    ],
    lastReviewedAt: "2026-07-12",
    content: [
      { heading: "O magnetismo das perguntas", text: "Você já percebeu como é difícil parar de fazer um quiz depois que começou? Seja um teste de personalidade nas redes sociais ou uma trivia sobre futebol, existe algo magnético nessas perguntas que nos prende até o final. A explicação está na forma como nosso cérebro funciona — e a ciência tem respostas fascinantes sobre por que adoramos quizzes." },
      { heading: "Dopamina: o prazer de acertar", text: "Quando respondemos uma pergunta corretamente em um quiz, nosso cérebro libera dopamina, o neurotransmissor associado à sensação de prazer e recompensa. É o mesmo mecanismo que nos faz sentir bem ao comer algo gostoso, receber um elogio ou completar uma tarefa. Cada acerto funciona como uma pequena vitória, e nosso cérebro quer mais. É por isso que quizzes de trivia são tão viciantes — cada pergunta é uma nova chance de sentir essa descarga de prazer." },
      { heading: "A teoria da lacuna de curiosidade", text: "O psicólogo George Loewenstein, da Universidade Carnegie Mellon, desenvolveu a teoria da lacuna de curiosidade para explicar por que sentimos uma necessidade quase irresistível de saber as respostas. Segundo essa teoria, quando identificamos uma lacuna entre o que sabemos e o que queremos saber, sentimos um desconforto que só é aliviado ao obter a informação. Um quiz explora isso perfeitamente: ao ler uma pergunta, nosso cérebro precisa da resposta, e não conseguimos simplesmente ignorar." },
      { heading: "Autoconhecimento e busca de identidade", text: "Os quizzes de personalidade ativam outro mecanismo poderoso: a necessidade de autoconhecimento. Psicólogos chamam isso de busca de identidade, um processo que, segundo Erik Erikson, dura a vida inteira. Quando um teste diz que você 'seria um elfo' ou que 'sua cidade ideal é Lisboa', isso satisfaz nossa curiosidade sobre nós mesmos. Mesmo que saibamos que o resultado é simplificado, gostamos de nos ver refletidos em categorias — é uma forma de validar quem somos ou descobrir facetas que não havíamos considerado." },
      { heading: "O efeito das redes sociais", text: "As redes sociais amplificaram exponencialmente o apelo dos quizzes. Compartilhar um resultado é uma forma de expressão social: ao postar 'Eu sou 87% nerd', você está comunicando algo sobre sua identidade para seus amigos. Isso ativa circuitos de conexão social no cérebro, pois gera comentários, comparações e conversas. Pesquisas da Universidade de Harvard mostraram que conteúdos que envolvem autorrevelação ativam as mesmas áreas cerebrais associadas à comida e ao dinheiro (Tamir & Mitchell, PNAS, 2012)." },
      { heading: "Competição e instinto social", text: "Existe também o fator competição. Quizzes de trivia frequentemente mostram sua pontuação ou comparam você com outros jogadores, ativando nosso instinto competitivo natural. Estudos em psicologia evolucionária sugerem que a competição por conhecimento era uma forma de ganhar status social em grupos humanos primitivos. Quem sabia mais sobre o ambiente, os animais e as plantas tinha mais chances de sobreviver e ser respeitado pelo grupo." },
      { heading: "Gamificação: aprender jogando", text: "A gamificação — o uso de elementos de jogos em contextos não lúdicos — explica por que quizzes são mais envolventes que simplesmente ler um texto informativo. Elementos como pontuação, vidas limitadas, timer e ranking transformam o aprendizado passivo em uma experiência ativa e emocional. Quando você tem apenas 3 vidas e erra uma pergunta, a tensão aumenta, o coração acelera e a atenção se aguça. É entretenimento e aprendizado ao mesmo tempo." },
      { heading: "Por que quizzes funcionam tão bem", text: "No fim das contas, os quizzes funcionam porque combinam vários dos maiores motivadores humanos: curiosidade, autoconhecimento, competição, conexão social e a busca por prazer. Não é à toa que bilhões de quizzes são feitos todos os anos ao redor do mundo. E agora que você entende a ciência, que tal colocar seu cérebro para trabalhar e testar seus conhecimentos?" },
    ],
  },
  {
    slug: "por-que-amamos-viloes-de-serie",
    title: "Por Que Amamos os Vilões: A Psicologia dos Antagonistas de Série",
    excerpt:
      "De Walter White a Cersei Lannister: o que a psicologia explica sobre a fascinação humana por personagens que fazem tudo errado.",
    category: "Séries & Filmes",
    date: "2026-09-21",
    readTime: 7,
    relatedQuizSlug: "qual-vilao-de-serie-voce-seria",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Kjeldgaard-Christiansen, J. (2016). Evil Origins: A Darwinian Genealogy of the Popcultural Villain. Evolutionary Behavioral Sciences, 10(2)", organization: "American Psychological Association", accessedAt: "2026-09-21" },
      { label: "Jonason, P. K. et al. (2012). The antihero in popular culture. Review of General Psychology, 16(2)", organization: "SAGE Publications", accessedAt: "2026-09-21" },
      { label: "Britannica — Antihero", url: "https://www.britannica.com/art/antihero", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "Existe um paradoxo que qualquer fã de séries reconhece: os personagens que fazem as piores coisas são frequentemente os mais fascinantes. Walter White cozinha metanfetamina e nós torcemos por ele. Cersei Lannister explode um templo inteiro e assistimos o próximo episódio na mesma noite. Vilões de série acumulam mais engajamento, mais memes e mais discussão que a maioria dos heróis — e a explicação não é simples gosto pelo grotesco. A psicologia tem respostas concretas para essa atração." },
      { heading: "O conceito de 'shadow self' e a identificação proibida", text: "Carl Jung cunhou o conceito de 'Sombra' para descrever os aspectos da personalidade que reprimimos por pressão social — impulsos de raiva, ambição desmedida, desejo de controle. Quando assistimos um vilão agir sem restrições morais, experimentamos esses impulsos de forma vicária e segura. Não precisamos cometer o ato; o personagem faz por nós. Um estudo de Kjeldgaard-Christiansen (2016), publicado na Evolutionary Behavioral Sciences, argumenta que vilões da cultura pop funcionam como representações externalizadas de ameaças sociais ancestrais — dominadores, manipuladores, traidores — e nosso cérebro evoluiu para prestar atenção especial a esses perfis. Ignorar um predador social era perigoso; estudá-lo era sobrevivência." },
      { heading: "A era do anti-herói: de Tony Soprano a Homelander", text: "A televisão mudou radicalmente a partir de 1999, quando Os Sopranos estreou na HBO com um protagonista que era simultaneamente pai de família e chefe da máfia. Antes disso, a TV americana operava quase exclusivamente com heróis moralmente claros. Tony Soprano provou que audiências não só toleram protagonistas moralmente ambíguos — elas preferem. O modelo foi replicado com variações: Dexter (serial killer que mata assassinos), Walter White (professor que vira traficante), Frank Underwood (político que mata para subir). Jonason et al. (2012), na Review of General Psychology, demonstraram que anti-heróis que exibem traços da chamada 'Tríade Sombria' (narcisismo, maquiavelismo, psicopatia) geram mais engajamento emocional que personagens virtuosos — desde que o espectador perceba uma motivação compreensível por trás das ações." },
      { heading: "A 'regra da motivação': por que alguns vilões funcionam e outros não", text: "Nem todo vilão gera empatia. A diferença está na construção narrativa. Vilões eficazes seguem uma estrutura que roteiristas chamam de 'motivação compreensível': o espectador não precisa concordar com o ato, mas precisa entender por que o personagem acredita que é a única opção. Thanos quer salvar o universo do colapso de recursos. Killmonger quer justiça para a diáspora africana. Cersei quer proteger seus filhos. Quando a motivação é puramente 'ser mau' — sem contexto, sem perda, sem lógica interna — o vilão vira caricatura e perde a fascinação. É a diferença entre um Joker (motivação filosófica sobre o caos) e um vilão genérico de filme de ação dos anos 80." },
      { heading: "O papel da empatia cognitiva (não emocional)", text: "Pesquisadores distinguem dois tipos de empatia: a emocional (sentir o que o outro sente) e a cognitiva (entender por que o outro sente o que sente, sem necessariamente compartilhar a emoção). Quando assistimos vilões complexos, ativamos a empatia cognitiva — compreendemos a lógica interna do personagem sem adotar seus valores. Isso explica por que podemos assistir uma cena de violência em Breaking Bad e sentir tensão narrativa (empatia cognitiva pelo dilema de Walter) sem sentir prazer pela violência em si (empatia emocional). Essa distinção é crucial: ela demonstra que gostar de um vilão na ficção não indica tendência à crueldade na vida real — indica sofisticação narrativa." },
      { heading: "Vilãs e a questão de gênero na recepção", text: "A recepção de vilãs segue padrões diferentes. Personagens femininas que exibem os mesmos traços de vilões masculinos adorados — ambição, manipulação, frieza calculada — frequentemente recebem reações mais hostis do público. Cersei Lannister é um caso revelador: estudos de recepção mostram que espectadores tendem a classificar suas ações como 'cruéis' com mais frequência do que classificam ações equivalentes de personagens masculinos como Tywin Lannister. A diferença não está no roteiro, mas nas expectativas culturais sobre como personagens femininas 'devem' se comportar. Séries recentes como Killing Eve e Yellowjackets desafiam isso ao construir vilãs cujas motivações são tão elaboradas quanto as de qualquer anti-herói masculino." },
      { heading: "O que seu vilão favorito diz sobre você", text: "A escolha do vilão favorito funciona como um espelho invertido de valores. Quem admira a inteligência estratégica de Gustavo Fring provavelmente valoriza controle e planejamento. Quem se fascina pela imprevisibilidade do Coringa tende a valorizar autenticidade e rejeição de convenções. Quem torce por Loki aprecia carisma e adaptabilidade. Não é coincidência que quizzes do tipo 'qual vilão você seria' estejam entre os mais compartilhados em redes sociais — eles oferecem uma forma socialmente aceitável de explorar os traços que normalmente escondemos." },
    ],
  },
  {
    slug: "fenomeno-round-6-hallyu-streaming",
    title: "Round 6 e a Onda Coreana: Como a Coreia do Sul Conquistou o Streaming",
    excerpt:
      "De Squid Game a Parasita: os fatores econômicos, culturais e industriais que transformaram a Coreia do Sul na potência criativa do século XXI.",
    category: "Séries & Filmes",
    date: "2026-09-21",
    readTime: 8,
    relatedQuizSlug: "quiz-round-6-voce-sobreviveria",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Jin, D. Y. (2016). New Korean Wave: Transnational Cultural Power in the Age of Social Media", organization: "University of Illinois Press", accessedAt: "2026-09-21" },
      { label: "Korea Creative Content Agency (KOCCA) — Annual Report", url: "https://www.kocca.kr/en", organization: "KOCCA / Ministry of Culture, Sports and Tourism", accessedAt: "2026-09-21" },
      { label: "Britannica — Hallyu", url: "https://www.britannica.com/topic/hallyu", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
      { label: "Netflix — Top 10 Global", url: "https://top10.netflix.com/", organization: "Netflix", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "Em setembro de 2021, uma série sul-coreana sobre jogos infantis mortais se tornou o conteúdo mais assistido da história da Netflix — 1,65 bilhão de horas de visualização nas primeiras 28 semanas. Round 6 (Squid Game) não foi um acidente. Foi o resultado visível de décadas de investimento estatal, evolução industrial e uma estratégia cultural que transformou a Coreia do Sul — um país de 52 milhões de habitantes — na maior exportadora de entretenimento per capita do mundo. Entender como isso aconteceu explica mais sobre o futuro do streaming do que qualquer análise de algoritmo." },
      { heading: "O plano de 30 anos: como o governo coreano apostou na cultura", text: "A história começa em 1994, quando o governo sul-coreano publicou um relatório interno comparando a receita do filme Jurassic Park com as vendas de automóveis Hyundai. A conclusão foi chocante: um único filme americano gerou receita equivalente à venda de 1,5 milhão de carros. O presidente Kim Young-sam criou o Departamento de Indústria Cultural, e em 1999 o governo aprovou a Lei Básica de Promoção de Indústrias Culturais — um marco que canalizou bilhões de dólares em subsídios diretos para cinema, TV, música e games. A KOCCA (Korea Creative Content Agency), criada para administrar esses recursos, investiu sistematicamente em formação de roteiristas, infraestrutura de estúdios e promoção internacional. Nenhum outro país combinou investimento estatal, infraestrutura de banda larga (a mais rápida do mundo desde os anos 2000) e liberdade criativa nessa escala." },
      { heading: "Hallyu: a onda que começou com doramas e K-pop", text: "O termo 'Hallyu' (onda coreana) foi cunhado por jornalistas chineses no final dos anos 1990 para descrever a popularidade crescente de doramas coreanos no leste asiático. Dal Yong Jin, professor da Simon Fraser University, documenta em 'New Korean Wave' (2016) como a segunda fase do Hallyu — impulsionada por redes sociais e streaming — ultrapassou fronteiras regionais. O K-pop (BTS, BLACKPINK) abriu portas culturais que o cinema atravessou: quando Parasita ganhou o Oscar de Melhor Filme em 2020, foi a culminação de uma estratégia que começou 25 anos antes. O público global já estava familiarizado com estética, ritmo narrativo e temas coreanos — Parasita não precisou se apresentar, só confirmar." },
      { heading: "Por que Round 6 funcionou onde outros falharam", text: "Hwang Dong-hyuk escreveu o roteiro de Round 6 em 2009 e passou mais de uma década tentando produzi-lo — todos os estúdios coreanos recusaram. A Netflix comprou os direitos em 2019 como parte de uma estratégia de investimento pesado em conteúdo não-anglófono (a empresa investiu US$ 500 milhões em conteúdo coreano só em 2021). O sucesso de Round 6 combinou fatores específicos: alegoria social universal (desigualdade econômica, dívida, competição por sobrevivência), estética visual marcante (os guardas de máscara, o uniforme verde), e jogos infantis reconhecíveis por qualquer cultura. A série não precisou explicar seu mundo — o público de qualquer país entendeu imediatamente a metáfora." },
      { heading: "Os números que mudaram a indústria", text: "Depois de Round 6, os dados do streaming mudaram permanentemente. Segundo a Netflix Top 10 Global, conteúdos em idiomas que não o inglês passaram de 27% para mais de 40% das horas assistidas na plataforma entre 2021 e 2025. Séries coreanas como All of Us Are Dead, The Glory e Physical: 100 entraram repetidamente no top 10 global. O mercado de exportação de conteúdo coreano cresceu de US$ 6,4 bilhões (2019) para US$ 13,2 bilhões (2024), segundo dados da KOCCA. Para efeito de comparação, toda a indústria cinematográfica brasileira exportou cerca de US$ 30 milhões no mesmo período." },
      { heading: "O modelo coreano vs. o modelo americano de roteiro", text: "Uma diferença estrutural explica a qualidade consistente dos doramas e thrillers coreanos: o modelo de produção. Nos EUA, séries de TV operam com 'writers' rooms' — equipes de roteiristas que escrevem episódios em paralelo, sob pressão de cronograma. Na Coreia, a tradição é o roteirista-autor único, que entrega o roteiro completo antes das filmagens começarem. Isso produz narrativas mais coesas: cada episódio sabe exatamente para onde a história vai. Round 6, Parasita e Oldboy foram todos escritos por um único autor-diretor. O custo é tempo (séries coreanas levam mais para produzir), mas o resultado é uma integridade narrativa que o modelo de assembly line americano raramente alcança." },
      { heading: "O que vem depois do Hallyu", text: "A questão agora não é se a Coreia do Sul vai continuar produzindo conteúdo global — é se outros países vão aprender o modelo. A combinação de investimento público de longo prazo, liberdade criativa, infraestrutura digital de primeira linha e uma cultura que valoriza narrativa como arte (não apenas como produto) criou uma indústria que compete de igual para igual com Hollywood. Para o espectador, o resultado é claro: nunca houve tanta variedade e qualidade disponível em uma tela. E se você quer testar o quanto sabe sobre o universo de Round 6, temos um quiz esperando." },
    ],
  },
  {
    slug: "disc-mbti-big-five-qual-teste-funciona",
    title: "DISC, MBTI e Big Five: Qual Teste de Perfil Profissional Funciona?",
    excerpt:
      "Três frameworks, três promessas. O que a ciência diz sobre a validade de cada teste — e por que empresas continuam usando o que não tem evidência.",
    category: "Carreira",
    date: "2026-09-21",
    readTime: 7,
    relatedQuizSlug: "descubra-seu-perfil-profissional",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "McCrae, R. R. & Costa, P. T. (1987). Validation of the Five-Factor Model across instruments and observers. Journal of Personality and Social Psychology, 52(1)", organization: "American Psychological Association", accessedAt: "2026-09-21" },
      { label: "Pittenger, D. J. (2005). Cautionary comments regarding the Myers-Briggs Type Indicator. Consulting Psychology Journal, 57(3)", organization: "APA / Consulting Psychology Journal", accessedAt: "2026-09-21" },
      { label: "Marston, W. M. (1928). Emotions of Normal People", organization: "Kegan Paul, Trench, Trubner & Co.", accessedAt: "2026-09-21" },
      { label: "Britannica — Personality Assessment", url: "https://www.britannica.com/science/personality-assessment", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "Se você já trabalhou em uma empresa de médio ou grande porte, provavelmente fez pelo menos um teste de perfil profissional. O departamento de RH aplica, você responde 60 perguntas, e no final recebe uma sigla ou uma cor que supostamente explica como você trabalha, se comunica e toma decisões. Mas nem todos esses testes têm a mesma base científica — e a distância entre o mais robusto e o mais questionável é enorme. Este artigo compara os três frameworks mais usados no mercado brasileiro: DISC, MBTI e Big Five." },
      { heading: "DISC: o mais usado no Brasil corporativo", text: "O modelo DISC foi desenvolvido pelo psicólogo William Moulton Marston em 1928 — o mesmo homem que criou a Mulher-Maravilha e o polígrafo. Marston propôs que o comportamento humano pode ser descrito em quatro dimensões: Dominância (foco em resultados e controle), Influência (foco em pessoas e entusiasmo), Estabilidade (foco em ritmo e cooperação) e Conformidade (foco em regras e precisão). O teste classifica a pessoa em um perfil predominante, com combinações secundárias. No Brasil, o DISC é amplamente usado em recrutamento, treinamento de liderança e gestão de equipes. Sua vantagem é a simplicidade: quatro perfis são fáceis de explicar e aplicar. Sua limitação: Marston publicou a teoria em 1928, mas nunca criou um instrumento padronizado de avaliação. Os testes DISC atuais são adaptações comerciais feitas por empresas diferentes, sem um único protocolo validado — o que significa que dois 'testes DISC' de fornecedores diferentes podem dar resultados diferentes para a mesma pessoa." },
      { heading: "MBTI: o mais famoso — e o mais criticado", text: "O MBTI (Myers-Briggs Type Indicator) classifica pessoas em 16 tipos baseados em quatro dicotomias: Extroversão/Introversão, Sensação/Intuição, Pensamento/Sentimento, Julgamento/Percepção. Criado na década de 1940 por Katharine Briggs e Isabel Myers (nenhuma das duas era psicóloga), o teste se tornou um fenômeno corporativo: estima-se que mais de 50 milhões de pessoas já o fizeram. O problema: a validade científica do MBTI é fraca. Pittenger (2005), no Consulting Psychology Journal da APA, compilou décadas de pesquisa mostrando que o MBTI tem baixa confiabilidade teste-reteste — até 50% das pessoas recebem um tipo diferente quando refazem o teste após 5 semanas. Além disso, o modelo de dicotomias (você é Extrovertido OU Introvertido) não reflete como a personalidade funciona na realidade: a maioria das pessoas está no meio do espectro, não nos extremos. Apesar disso, o MBTI gera US$ 2 bilhões por ano em licenciamento e certificação." },
      { heading: "Big Five (OCEAN): o que a ciência realmente valida", text: "O modelo dos Cinco Grandes Fatores — também chamado OCEAN (Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism) — é o framework com maior suporte empírico na psicologia contemporânea. McCrae e Costa (1987) demonstraram sua validade em múltiplos instrumentos, culturas e contextos. Diferente do MBTI, o Big Five não classifica em tipos — ele mede cada traço em um espectro contínuo. Você não 'é' extrovertido ou introvertido; você tem um nível específico de extroversão que pode variar ao longo da vida. Estudos longitudinais mostram que os cinco fatores são estáveis ao longo do tempo, predizem desempenho profissional (especialmente Conscienciosidade) e têm base genética documentada. O Big Five é o padrão-ouro da pesquisa em personalidade — mas é menos popular em empresas justamente porque é mais nuançado e menos 'instagramável' que uma sigla de 4 letras." },
      { heading: "Por que empresas preferem o menos científico", text: "Se o Big Five é o mais válido, por que empresas continuam usando MBTI e DISC? A resposta está na usabilidade, não na ciência. MBTI e DISC produzem categorias discretas ('você é ENTJ', 'você é perfil D') que são fáceis de comunicar em workshops, slides e dinâmicas de grupo. O Big Five produz cinco números em um espectro — mais preciso, mas menos narrativo. Gestores querem uma história sobre cada funcionário ('ele é Dominante, então precisa de autonomia'), não um gráfico radar com percentis. A simplificação sacrifica precisão, mas ganha adoção. É um trade-off que diz mais sobre a cultura corporativa do que sobre a psicologia." },
      { heading: "Como usar testes de perfil sem cair na armadilha", text: "Nenhum teste de perfil deve ser usado como única ferramenta de decisão em recrutamento ou promoção — isso é contraindicado por todas as associações profissionais de psicologia. O valor real desses instrumentos está em três usos legítimos: autoconhecimento (entender suas tendências naturais), comunicação em equipe (adaptar linguagem ao perfil do colega) e desenvolvimento pessoal (identificar áreas de crescimento). O erro é tratar o resultado como diagnóstico fixo: 'sou D, então não sirvo para trabalho colaborativo'. Personalidade é tendência, não destino." },
      { heading: "Teste na prática", text: "Se você quer experimentar um teste de perfil baseado no modelo DISC — o mais utilizado no ambiente corporativo brasileiro — temos um quiz interativo que classifica seu perfil em Dominância, Influência, Estabilidade e Conformidade com base em 12 perguntas sobre comportamento no trabalho. Não é um diagnóstico clínico, mas é uma forma rápida e fundamentada de refletir sobre como você opera profissionalmente." },
    ],
  },
  {
    slug: "copa-2026-48-selecoes-16-cidades",
    title: "48 Seleções em 16 Cidades: O Que Muda na Copa 2026",
    excerpt:
      "A maior Copa da história traz novo formato, fusos horários extremos e desafios logísticos inéditos. O que isso significa para seleções e torcedores.",
    category: "Esportes",
    date: "2026-09-21",
    readTime: 7,
    relatedQuizSlug: "adivinhe-o-pais-pela-bandeira-copa-2026",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "FIFA.com — FIFA World Cup 26 Format", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-09-21" },
      { label: "Britannica — FIFA World Cup", url: "https://www.britannica.com/sports/World-Cup-football", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
      { label: "Panja, T. & Draper, K. (2023). World Cup expansion analysis. The New York Times", organization: "The New York Times", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "A Copa do Mundo de 2026 será a primeira com 48 seleções, 104 jogos e 16 cidades-sede espalhadas por três países e seis fusos horários. É a maior mudança de formato desde a expansão de 24 para 32 times em 1998 — e traz implicações que vão muito além de mais jogos no calendário. Desde a logística de viagens até a matemática de classificação, quase tudo o que conhecíamos sobre 'como funciona uma Copa' muda." },
      { heading: "O novo formato: 12 grupos de 4, não mais 8", text: "Até 2022, a Copa tinha 8 grupos de 4 seleções cada. Em 2026, serão 12 grupos de 4, com os dois primeiros de cada grupo avançando, mais os 8 melhores terceiros colocados — totalizando 32 classificados para o mata-mata. Isso cria uma situação inédita: pela primeira vez, perder um jogo na fase de grupos não é sinônimo de eliminação quase certa. Uma seleção pode perder a estreia, vencer o segundo jogo e se classificar como terceiro colocado com 3 pontos. A consequência tática é que treinadores terão mais margem para rodar elencos e dosificar esforço — mas o risco é que jogos da fase de grupos percam dramaticidade, já que a punição por derrota diminuiu." },
      { heading: "Três países, seis fusos: o desafio logístico", text: "As 16 cidades-sede vão de Vancouver (UTC-8) a Miami (UTC-5), passando pela Cidade do México (UTC-6). Um time que jogue em Seattle na terça e em Nova York no sábado cruzará 3 fusos horários em 4 dias. Para atletas de elite, a diferença de fuso afeta qualidade de sono, tempo de recuperação e ritmo circadiano — fatores que estudos de medicina esportiva correlacionam com aumento de lesões musculares. Seleções com bases fixas mais centrais (Dallas, Houston, Kansas City) terão vantagem logística sobre as que precisarem cruzar o continente entre jogos. A FIFA distribuiu os grupos geograficamente para minimizar viagens, mas não conseguiu eliminar deslocamentos de mais de 3.000 km dentro da mesma fase." },
      { heading: "Quem ganha e quem perde com a expansão", text: "A expansão de 32 para 48 vagas beneficia diretamente confederações historicamente sub-representadas. A África passa de 5 para 9 vagas. A Ásia, de 4 para 8. A Concacaf (América do Norte e Central), por ser anfitriã, tem 6 vagas diretas mais as 3 automáticas dos países-sede. Na prática, isso significa que seleções como Canadá, Qatar, Arábia Saudita e países africanos de segunda linha terão acesso ao torneio principal pela primeira vez ou com mais frequência. Críticos argumentam que isso dilui o nível técnico: nas Copas de 32 times, a fase de grupos já produzia partidas desequilibradas (Alemanha 7x1 Brasil é exceção, não regra — o padrão são goleadas contra seleções menores). Com 48 times, espera-se mais jogos com placares elásticos na primeira fase." },
      { heading: "O impacto econômico: US$ 11 bilhões em receita projetada", text: "A FIFA projeta receita recorde de US$ 11 bilhões para o ciclo 2023-2026, com a Copa respondendo pela maior parte. A diferença de 40 jogos a mais (de 64 para 104) significa 40 ingressos a mais para vender, 40 transmissões a mais para licenciar e 40 oportunidades a mais de patrocínio em estádio. Para os EUA, a Copa é uma oportunidade de infraestrutura: vários estádios de NFL estão sendo adaptados para futebol, com expansão de capacidade e instalação de gramado natural sobre campos sintéticos. O MetLife Stadium (Nova Jersey), que sediará a final, está investindo mais de US$ 100 milhões em reformas." },
      { heading: "O que muda para o torcedor brasileiro", text: "Para torcedores no Brasil, a Copa de 2026 será a primeira em fuso horário majoritariamente desfavorável desde 1994. Jogos na costa oeste dos EUA (Los Angeles, Seattle, San Francisco) às 18h locais significam 22h no horário de Brasília — viável, mas longe do horário nobre. Jogos na costa leste às 21h locais seriam meia-noite no Brasil. A expectativa é que a FIFA agende os jogos do Brasil em horários intermediários para preservar a audiência sul-americana, mas com 104 jogos para distribuir, nem todos os horários serão ideais. A boa notícia: com três países-sede, existem opções de viagem mais acessíveis que Copas na Europa ou Ásia — voos diretos de São Paulo para Miami duram cerca de 8 horas." },
      { heading: "Um experimento em tempo real", text: "A Copa de 2026 é, em muitos sentidos, um experimento. Nunca se tentou organizar um torneio dessa escala em três países simultaneamente. Nunca se jogou com 48 seleções no nível de Copa do Mundo. E nunca se distribuiu tantos jogos em tantos fusos horários diferentes. Se funcionar, o modelo deve se repetir. Se não funcionar, a FIFA terá dados concretos sobre os limites do formato. De qualquer forma, será uma Copa histórica — e entender as mudanças antes de a bola rolar é a melhor preparação para acompanhar o torneio." },
    ],
  },
  {
    slug: "brasil-de-ponta-a-ponta-fatos-geograficos",
    title: "Brasil de Ponta a Ponta: Fatos Geográficos que Desafiam o Senso Comum",
    excerpt:
      "Da fronteira seca com o Uruguai ao ponto mais ocidental que fica mais perto de Lima do que de Brasília: a geografia real do Brasil é mais estranha do que parece.",
    category: "Conhecimentos Gerais",
    date: "2026-09-21",
    readTime: 7,
    relatedQuizSlug: "quiz-geografia-do-brasil",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "IBGE — Brasil em Números", url: "https://www.ibge.gov.br/", organization: "Instituto Brasileiro de Geografia e Estatística", accessedAt: "2026-09-21" },
      { label: "Ab'Sáber, A. N. (2003). Os Domínios de Natureza no Brasil: Potencialidades Paisagísticas", organization: "Ateliê Editorial", accessedAt: "2026-09-21" },
      { label: "Britannica — Brazil", url: "https://www.britannica.com/place/Brazil", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "O Brasil é o quinto maior país do mundo em área (8,5 milhões de km²) e faz fronteira com 10 dos 12 países da América do Sul — só não toca Chile e Equador. Esses dados todo mundo decora na escola. Mas a geografia real do país, quando observada de perto, é cheia de fatos que contradizem o senso comum, desafiam mapas mentais e revelam um território muito mais diverso e estranho do que os livros didáticos sugerem." },
      { heading: "O ponto mais ao norte fica mais perto de Dublin do que de Porto Alegre", text: "O Monte Caburaí, no extremo norte de Roraima, é o ponto mais setentrional do Brasil. Está a 1.640 km da linha do Equador — e a 4.394 km de Porto Alegre. A distância entre Caburaí e Dublin, na Irlanda, é de 7.700 km — parece muito, mas a distância entre Caburaí e o Chuí (ponto mais ao sul, no Rio Grande do Sul) é de 4.378 km em linha reta. Ou seja: de norte a sul, o Brasil se estende por quase 4.400 km — equivalente à distância entre Lisboa e Moscou. Essa extensão explica por que o Brasil tem quatro fusos horários e por que o clima de Manaus não tem absolutamente nada a ver com o de Curitiba." },
      { heading: "Amazonas caberia a Espanha — duas vezes", text: "O estado do Amazonas tem 1.559.167 km², segundo o IBGE. Para contextualizar: a Espanha inteira tem 505.990 km². O Amazonas é três vezes a Espanha e maior que qualquer país da Europa Ocidental. Paradoxalmente, tem apenas 4,2 milhões de habitantes — a cidade de São Paulo sozinha tem três vezes mais. A densidade demográfica do Amazonas é de 2,7 habitantes por km², contra 7.398 em São Paulo capital. São dois Brasis que compartilham o mesmo governo federal mas vivem realidades incomparáveis." },
      { heading: "O Pantanal: a maior área alagável do planeta que quase ninguém visita", text: "O Pantanal ocupa aproximadamente 150.000 km² entre Mato Grosso, Mato Grosso do Sul, Bolívia e Paraguai. É a maior planície de inundação contínua do mundo — durante a estação chuvosa, até 80% de sua área fica submersa. O geógrafo Aziz Ab'Sáber, na obra 'Os Domínios de Natureza no Brasil' (2003), classificou o Pantanal como um dos seis grandes domínios morfoclimáticos brasileiros, com dinâmica hidrológica única. Apesar de ser Patrimônio Natural da Humanidade desde 2000 (UNESCO), o Pantanal recebe menos de 200 mil turistas por ano — contra 6 milhões que visitam as Cataratas do Iguaçu. A razão é infraestrutura: a maioria do Pantanal é acessível apenas por barco ou avião monomotor." },
      { heading: "A fronteira seca com o Uruguai: duas cidades, um calçadão", text: "Na fronteira entre o Brasil e o Uruguai, as cidades de Santana do Livramento (RS) e Rivera formam uma conurbação única separada apenas por uma praça e uma rua. Não há rio, muro ou cerca — moradores cruzam a fronteira a pé para fazer compras, e muitas famílias têm membros dos dois lados. É a fronteira seca mais integrada da América do Sul e um caso raro de convivência binacional no cotidiano. Crianças de Rivera estudam em escolas brasileiras; brasileiros abastecem o carro no Uruguai quando o combustível está mais barato." },
      { heading: "O Brasil tem deserto — e neve", text: "Os Lençóis Maranhenses, no Maranhão, são frequentemente chamados de 'deserto' por seus campos de dunas que se estendem por 155.000 hectares. Mas tecnicamente não é um deserto: a região recebe 1.600 mm de chuva por ano (mais que Londres), e entre janeiro e junho, lagoas de água doce se formam entre as dunas. No extremo oposto, São Joaquim (SC) e Urupema (SC), a mais de 1.300 metros de altitude, registram neve praticamente todo inverno. Em agosto de 2013, pelo menos 90 cidades catarinenses registraram temperaturas negativas. O Brasil que 'só tem calor' é um mito que não sobrevive à geografia real." },
      { heading: "Por que a geografia importa além da prova", text: "Entender a geografia do Brasil não é exercício escolar — é condição para entender por que políticas públicas que funcionam em São Paulo fracassam no Amazonas, por que a logística de transporte rodoviário custa o que custa, e por que o país tem simultaneamente seca no Nordeste e enchentes no Sul. A diversidade geográfica é o dado mais subestimado do Brasil: 8,5 milhões de km² não são um país — são um continente disfarçado de república federativa." },
    ],
  },
  {
    slug: "historia-dos-signos-zodiaco-2500-anos",
    title: "O Zodíaco Tem 2.500 Anos: A História dos Signos que Ninguém Conta",
    excerpt:
      "De tábuas cuneiformes na Babilônia às previsões no Instagram: como o zodíaco sobreviveu à ciência, mudou de significado e se tornou um fenômeno digital.",
    category: "Cultura",
    date: "2026-09-21",
    readTime: 7,
    relatedQuizSlug: "qual-signo-voce-deveria-ser",
    author: "Patrick Bastos",
    authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
    sources: [
      { label: "Rochberg, F. (2004). The Heavenly Writing: Divination, Horoscopy, and Astronomy in Mesopotamian Culture", organization: "Cambridge University Press", accessedAt: "2026-09-21" },
      { label: "Britannica — Zodiac", url: "https://www.britannica.com/topic/zodiac", organization: "Encyclopædia Britannica", accessedAt: "2026-09-21" },
      { label: "IAU — The Constellations", url: "https://www.iau.org/public/themes/constellations/", organization: "International Astronomical Union", accessedAt: "2026-09-21" },
      { label: "Pew Research Center — New Age Beliefs", url: "https://www.pewresearch.org/religion/", organization: "Pew Research Center", accessedAt: "2026-09-21" },
    ],
    lastReviewedAt: "2026-09-21",
    content: [
      { text: "Os 12 signos do zodíaco são um dos sistemas de classificação mais antigos ainda em uso cotidiano. Bilhões de pessoas consultam horóscopos diariamente, apps de astrologia acumulam milhões de downloads, e 'qual é o seu signo?' continua sendo uma das perguntas mais comuns em interações sociais informais. Mas a história de como 12 faixas do céu babilônico se tornaram categorias de personalidade no Instagram é mais complexa, mais política e mais interessante do que a maioria dos entusiastas imagina." },
      { heading: "Babilônia, 500 a.C.: astronomia e presságio eram a mesma coisa", text: "Os primeiros registros sistemáticos do zodíaco aparecem em tábuas cuneiformes babilônicas datadas do século V a.C., conhecidas como MUL.APIN. Francesca Rochberg, professora de história da ciência na UC Berkeley, documenta em 'The Heavenly Writing' (2004) que para os babilônios não existia distinção entre astronomia e astrologia — observar os astros e interpretar seus significados era uma única disciplina praticada por sacerdotes-cientistas chamados tupšar Enūma Anu Enlil. O zodíaco babilônico originalmente não era sobre indivíduos — era sobre o Estado. Os presságios celestiais previam guerras, colheitas e a saúde do rei, não o destino de pessoas comuns." },
      { heading: "A virada grega: de presságio coletivo para horóscopo pessoal", text: "A transformação do zodíaco em ferramenta de análise individual aconteceu na Grécia Helenística, entre os séculos III e I a.C. Os gregos receberam o sistema babilônico via contato com a Pérsia e o Egito, e fizeram duas modificações fundamentais: dividiram o zodíaco em 12 segmentos exatos de 30 graus cada (os babilônios usavam constelações de tamanhos desiguais) e associaram cada segmento a um dos quatro elementos — Fogo, Terra, Ar e Água. Mais importante: os gregos introduziram o conceito de horóscopo natal — a ideia de que a posição dos astros no momento exato do nascimento de uma pessoa determina seu caráter. Antes disso, ninguém tinha 'um signo'. Depois disso, todos passaram a ter." },
      { heading: "A precessão dos equinócios: o problema que a astrologia ignora", text: "Existe uma discrepância astronômica que a astrologia tradicional nunca resolveu. Devido à precessão dos equinócios — a oscilação lenta do eixo de rotação da Terra — as constelações zodiacais se deslocaram aproximadamente 30 graus desde que os babilônios fixaram as datas. Na prática, isso significa que quem nasce em 10 de março é considerado 'Peixes' pelo zodíaco tropical (o usado no Ocidente), mas o Sol na verdade está na constelação de Aquário nessa data. A União Astronômica Internacional (IAU) reconhece 88 constelações oficiais, e a faixa zodiacal real contém 13, não 12 — Ophiuchus (Serpentário) fica entre Escorpião e Sagitário. A astrologia tropical contorna isso usando os signos como marcadores simbólicos fixos (baseados nas estações), não como referência astronômica literal — mas essa distinção raramente é explicada aos consumidores de horóscopos." },
      { heading: "Idade Média e Renascimento: astrologia como ciência de corte", text: "A astrologia sobreviveu à queda de Roma e floresceu na Idade Média islâmica — astrólogos como Abu Ma'shar (século IX) produziram tratados sofisticados que influenciaram a Europa por séculos. No Renascimento, papas e reis mantinham astrólogos oficiais: o papa Júlio II escolheu a data de sua coroação com base em conselhos astrológicos. Até o século XVII, astrologia e astronomia coexistiram como disciplinas irmãs — Kepler, que formulou as leis do movimento planetário, trabalhava como astrólogo para financiar sua pesquisa. A separação definitiva veio com o Iluminismo e a revolução científica, quando a exigência de evidência empírica deixou a astrologia sem base mensurável." },
      { heading: "O renascimento digital: por que o zodíaco voltou", text: "Pesquisas do Pew Research Center mostram que a crença em astrologia entre adultos nos EUA cresceu de 25% em 2009 para 37% em 2023, com pico entre jovens de 18-29 anos. No Brasil, os números são estimados como ainda maiores. O renascimento não é irracional — é funcional. A astrologia digital oferece três coisas que escasseiam na vida contemporânea: uma linguagem compartilhada para falar sobre emoções ('é coisa de Escorpião'), um framework de autoconhecimento acessível (nenhum teste psicológico tem a barreira de entrada de 'qual é o seu signo?') e uma comunidade de pertencimento (identificar-se como 'leonino' cria grupo). Apps como Co-Star e The Pattern acumularam mais de 30 milhões de downloads combinados transformando astrologia em notificações push personalizadas." },
      { heading: "Entre o símbolo e a ciência", text: "A astronomia e a astrologia divergiram há 300 anos, mas o zodíaco sobrevive porque cumpre uma função que a ciência não tenta ocupar: dar às pessoas uma narrativa sobre quem elas são. Isso não valida previsões astrológicas como verdade científica — a IAU é clara sobre isso — mas explica por que um sistema de 2.500 anos continua relevante na era da inteligência artificial. O zodíaco é, acima de tudo, uma história que a humanidade conta sobre si mesma. E como toda boa história, ela se adapta ao meio onde é contada." },
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return allArticles.find((a) => a.slug === slug);
}
