import type { Quiz } from "@/lib/types";

export const bandeirasCopa2026: Quiz = {
  id: "bandeiras-copa-2026",
  slug: "adivinhe-o-pais-pela-bandeira-copa-2026",
  title: "Adivinhe o País pela Bandeira — Edição Copa 2026",
  description: "48 seleções vão disputar a Copa. Quantas bandeiras você reconhece?",
  type: "trivia",
  category: "copa-do-mundo",
  emoji: "🏳️",
  color: "#059669",
  tags: ["copa", "bandeiras", "paises", "geografia", "2026"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "FIFA.com — FIFA World Cup 26 Teams", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-07-12" },
    { label: "CIA World Factbook — Country Flags", organization: "CIA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Reconheça as bandeiras das seleções que disputam a Copa do Mundo de 2026. Cada bandeira conta uma história.",
  questions: [
    {
      id: "q1",
      text: "Qual país tem a bandeira verde e amarela com um losango e globo azul?",
      options: [
        { id: "a", text: "Colômbia", isCorrect: false },
        { id: "b", text: "Brasil", isCorrect: true },
        { id: "c", text: "Bolívia", isCorrect: false },
        { id: "d", text: "Camarões", isCorrect: false },
      ],
      explanation: "A bandeira do Brasil foi adotada em 1889, com o losango amarelo sobre fundo verde e o globo azul com a faixa 'Ordem e Progresso'.",
    },
    {
      id: "q2",
      text: "Bandeira azul, branca e azul com sol no centro — qual país?",
      options: [
        { id: "a", text: "Uruguai", isCorrect: false },
        { id: "b", text: "Argentina", isCorrect: true },
        { id: "c", text: "Honduras", isCorrect: false },
        { id: "d", text: "El Salvador", isCorrect: false },
      ],
      explanation: "O sol na bandeira argentina é o Sol de Maio, símbolo da Revolução de Maio de 1810.",
    },
    {
      id: "q3",
      text: "Qual país tem uma folha de bordo (maple) vermelha na bandeira?",
      options: [
        { id: "a", text: "Irlanda", isCorrect: false },
        { id: "b", text: "Canadá", isCorrect: true },
        { id: "c", text: "Áustria", isCorrect: false },
        { id: "d", text: "Dinamarca", isCorrect: false },
      ],
      explanation: "O Canadá é um dos 3 países-sede da Copa 2026, junto com EUA e México!",
    },
    {
      id: "q4",
      text: "Qual seleção tem uma bandeira verde com uma inscrição árabe branca e uma espada?",
      options: [
        { id: "a", text: "Irã", isCorrect: false },
        { id: "b", text: "Argélia", isCorrect: false },
        { id: "c", text: "Arábia Saudita", isCorrect: true },
        { id: "d", text: "Turquia", isCorrect: false },
      ],
      explanation: "A bandeira da Arábia Saudita traz a Shahada (credo islâmico) em caligrafia branca e uma espada horizontal. O design atual foi adotado em 1973.",
    },
    {
      id: "q5",
      text: "Tricolor vertical azul, branco e vermelho — é a bandeira da:",
      options: [
        { id: "a", text: "Holanda", isCorrect: false },
        { id: "b", text: "Rússia", isCorrect: false },
        { id: "c", text: "França", isCorrect: true },
        { id: "d", text: "Itália", isCorrect: false },
      ],
      explanation: "A tricolor francesa (bleu, blanc, rouge) foi adotada durante a Revolução Francesa e simboliza liberdade, igualdade e fraternidade.",
    },
    {
      id: "q6",
      text: "Bandeira branca com círculo vermelho no centro — qual país?",
      options: [
        { id: "a", text: "China", isCorrect: false },
        { id: "b", text: "Coreia do Sul", isCorrect: false },
        { id: "c", text: "Japão", isCorrect: true },
        { id: "d", text: "Vietnã", isCorrect: false },
      ],
      explanation: "A bandeira do Japão é chamada Nisshoki ('bandeira do sol nascente'). O círculo vermelho representa o sol.",
    },
    {
      id: "q7",
      text: "Qual país africano tem bandeira verde, branca e verde na vertical?",
      options: [
        { id: "a", text: "Camarões", isCorrect: false },
        { id: "b", text: "Nigéria", isCorrect: true },
        { id: "c", text: "Gana", isCorrect: false },
        { id: "d", text: "Costa do Marfim", isCorrect: false },
      ],
      explanation: "A bandeira da Nigéria foi desenhada em 1959 por um estudante de 23 anos, Michael Taiwo Akinkunmi, num concurso nacional.",
    },
    {
      id: "q8",
      text: "Bandeira com águia na serpente sobre um cacto — é a bandeira do:",
      options: [
        { id: "a", text: "Peru", isCorrect: false },
        { id: "b", text: "México", isCorrect: true },
        { id: "c", text: "Equador", isCorrect: false },
        { id: "d", text: "Colômbia", isCorrect: false },
      ],
      explanation: "O México é país-sede da Copa 2026! A águia sobre o cacto vem de uma lenda asteca.",
    },
    {
      id: "q9",
      text: "Cruz vermelha sobre fundo branco — qual seleção europeia?",
      options: [
        { id: "a", text: "Dinamarca", isCorrect: false },
        { id: "b", text: "Suíça", isCorrect: false },
        { id: "c", text: "Inglaterra", isCorrect: true },
        { id: "d", text: "Geórgia", isCorrect: false },
      ],
      explanation: "A Cruz de São Jorge (vermelha sobre fundo branco) é o símbolo da Inglaterra, diferente do Union Jack do Reino Unido.",
    },
    {
      id: "q10",
      text: "Bandeira com listras vermelhas e brancas + quadrado azul com estrelas — é a bandeira:",
      options: [
        { id: "a", text: "Libéria", isCorrect: false },
        { id: "b", text: "Estados Unidos", isCorrect: true },
        { id: "c", text: "Malásia", isCorrect: false },
        { id: "d", text: "Porto Rico", isCorrect: false },
      ],
      explanation: "Os EUA são país-sede da Copa 2026 e terão a maioria dos jogos, incluindo a final!",
    },
    {
      id: "q11",
      text: "Bandeira tricolor verde, branca e laranja na vertical — qual país?",
      options: [
        { id: "a", text: "Itália", isCorrect: false },
        { id: "b", text: "Irlanda", isCorrect: true },
        { id: "c", text: "Costa do Marfim", isCorrect: false },
        { id: "d", text: "Hungria", isCorrect: false },
      ],
      explanation: "A bandeira da Irlanda é verde (católicos), laranja (protestantes) e branca (paz entre os dois grupos) na vertical.",
    },
    {
      id: "q12",
      text: "Bandeira vermelha e branca com xadrez — qual seleção?",
      options: [
        { id: "a", text: "Polônia", isCorrect: false },
        { id: "b", text: "Croácia", isCorrect: true },
        { id: "c", text: "Sérvia", isCorrect: false },
        { id: "d", text: "Eslovênia", isCorrect: false },
      ],
      explanation: "O xadrez vermelho e branco (šahovnica) é símbolo da Croácia desde a Idade Média.",
    },
    {
      id: "q13",
      text: "Bandeira toda vermelha com estrela amarela — qual país asiático?",
      options: [
        { id: "a", text: "China", isCorrect: false },
        { id: "b", text: "Vietnã", isCorrect: true },
        { id: "c", text: "Coreia do Norte", isCorrect: false },
        { id: "d", text: "Turquia", isCorrect: false },
      ],
      explanation: "A bandeira do Vietnã foi adotada em 1955. A estrela amarela de cinco pontas representa as cinco classes sociais.",
    },
    {
      id: "q14",
      text: "Qual seleção tem sol dourado na bandeira azul celeste?",
      options: [
        { id: "a", text: "Argentina", isCorrect: false },
        { id: "b", text: "Uruguai", isCorrect: true },
        { id: "c", text: "Guatemala", isCorrect: false },
        { id: "d", text: "Nicarágua", isCorrect: false },
      ],
      explanation: "O sol na bandeira do Uruguai é o Sol de Maio, mesmo símbolo da Argentina, referente à Revolução de Maio.",
    },
    {
      id: "q15",
      text: "Bandeira tricolor preta, vermelha e dourada na horizontal — qual país?",
      options: [
        { id: "a", text: "Bélgica", isCorrect: false },
        { id: "b", text: "Alemanha", isCorrect: true },
        { id: "c", text: "Angola", isCorrect: false },
        { id: "d", text: "Uganda", isCorrect: false },
      ],
      explanation: "As cores da bandeira alemã (preto, vermelho e dourado) vêm dos uniformes dos voluntários nas Guerras Napoleônicas.",
    },
  ],
};
