import type { Quiz } from "@/lib/types";

export const bandeirasCopa2026: Quiz = {
  id: "bandeiras-copa-2026",
  slug: "adivinhe-o-pais-pela-bandeira-copa-2026",
  title: "Adivinhe o Pais pela Bandeira — Edicao Copa 2026",
  description: "48 selecoes vao disputar a Copa. Quantas bandeiras voce reconhece?",
  type: "trivia",
  category: "copa-do-mundo",
  emoji: "🏳️",
  color: "#059669",
  tags: ["copa", "bandeiras", "paises", "geografia", "2026"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "FIFA.com — FIFA World Cup 26 Teams", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-07-12" },
    { label: "CIA World Factbook — Country Flags", organization: "CIA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Reconheça as bandeiras das seleções que disputam a Copa do Mundo de 2026. Cada bandeira conta uma história.",
  questions: [
    {
      id: "q1",
      text: "Qual pais tem a bandeira verde e amarela com um losango e globo azul?",
      options: [
        { id: "a", text: "Colombia", isCorrect: false },
        { id: "b", text: "Brasil", isCorrect: true },
        { id: "c", text: "Bolivia", isCorrect: false },
        { id: "d", text: "Camaroes", isCorrect: false },
      ],
      explanation: "A bandeira do Brasil foi adotada em 1889, com o losango amarelo sobre fundo verde e o globo azul com a faixa 'Ordem e Progresso'.",
    },
    {
      id: "q2",
      text: "Bandeira azul, branca e azul com sol no centro — qual pais?",
      options: [
        { id: "a", text: "Uruguai", isCorrect: false },
        { id: "b", text: "Argentina", isCorrect: true },
        { id: "c", text: "Honduras", isCorrect: false },
        { id: "d", text: "El Salvador", isCorrect: false },
      ],
      explanation: "O sol na bandeira argentina e o Sol de Maio, simbolo da Revolucao de Maio de 1810.",
    },
    {
      id: "q3",
      text: "Qual pais tem uma folha de bordo (maple) vermelha na bandeira?",
      options: [
        { id: "a", text: "Irlanda", isCorrect: false },
        { id: "b", text: "Canada", isCorrect: true },
        { id: "c", text: "Austria", isCorrect: false },
        { id: "d", text: "Dinamarca", isCorrect: false },
      ],
      explanation: "O Canada e um dos 3 paises-sede da Copa 2026, junto com EUA e Mexico!",
    },
    {
      id: "q4",
      text: "Qual seleção tem uma bandeira verde com uma inscrição árabe branca e uma espada?",
      options: [
        { id: "a", text: "Irã", isCorrect: false },
        { id: "b", text: "Argélia", isCorrect: false },
        { id: "c", text: "Arábia Saudita", isCorrect: true },
        { id: "d", text: "Turquia", isCorrect: false },
      ],
      explanation: "A bandeira da Arábia Saudita traz a Shahada (credo islâmico) em caligrafia branca e uma espada horizontal. O design atual foi adotado em 1973.",
    },
    {
      id: "q5",
      text: "Tricolor vertical azul, branco e vermelho — e a bandeira da:",
      options: [
        { id: "a", text: "Holanda", isCorrect: false },
        { id: "b", text: "Russia", isCorrect: false },
        { id: "c", text: "Franca", isCorrect: true },
        { id: "d", text: "Italia", isCorrect: false },
      ],
      explanation: "A tricolor francesa (bleu, blanc, rouge) foi adotada durante a Revolucao Francesa e simboliza liberdade, igualdade e fraternidade.",
    },
    {
      id: "q6",
      text: "Bandeira branca com circulo vermelho no centro — qual pais?",
      options: [
        { id: "a", text: "China", isCorrect: false },
        { id: "b", text: "Coreia do Sul", isCorrect: false },
        { id: "c", text: "Japao", isCorrect: true },
        { id: "d", text: "Vietna", isCorrect: false },
      ],
      explanation: "A bandeira do Japao e chamada Nisshoki ('bandeira do sol nascente'). O circulo vermelho representa o sol.",
    },
    {
      id: "q7",
      text: "Qual pais africano tem bandeira verde, branca e verde na vertical?",
      options: [
        { id: "a", text: "Camaroes", isCorrect: false },
        { id: "b", text: "Nigeria", isCorrect: true },
        { id: "c", text: "Gana", isCorrect: false },
        { id: "d", text: "Costa do Marfim", isCorrect: false },
      ],
      explanation: "A bandeira da Nigeria foi desenhada em 1959 por um estudante de 23 anos, Michael Taiwo Akinkunmi, num concurso nacional.",
    },
    {
      id: "q8",
      text: "Bandeira com aguia na serpente sobre um cacto — e a bandeira do:",
      options: [
        { id: "a", text: "Peru", isCorrect: false },
        { id: "b", text: "Mexico", isCorrect: true },
        { id: "c", text: "Equador", isCorrect: false },
        { id: "d", text: "Colombia", isCorrect: false },
      ],
      explanation: "O Mexico e pais-sede da Copa 2026! A aguia sobre o cacto vem de uma lenda asteca.",
    },
    {
      id: "q9",
      text: "Cruz vermelha sobre fundo branco — qual selecao europeia?",
      options: [
        { id: "a", text: "Dinamarca", isCorrect: false },
        { id: "b", text: "Suica", isCorrect: false },
        { id: "c", text: "Inglaterra", isCorrect: true },
        { id: "d", text: "Georgia", isCorrect: false },
      ],
      explanation: "A Cruz de Sao Jorge (vermelha sobre fundo branco) e o simbolo da Inglaterra, diferente do Union Jack do Reino Unido.",
    },
    {
      id: "q10",
      text: "Bandeira com listras vermelhas e brancas + quadrado azul com estrelas — e a bandeira:",
      options: [
        { id: "a", text: "Liberia", isCorrect: false },
        { id: "b", text: "Estados Unidos", isCorrect: true },
        { id: "c", text: "Malasia", isCorrect: false },
        { id: "d", text: "Porto Rico", isCorrect: false },
      ],
      explanation: "Os EUA sao pais-sede da Copa 2026 e terao a maioria dos jogos, incluindo a final!",
    },
    {
      id: "q11",
      text: "Bandeira tricolor verde, branca e laranja na vertical — qual pais?",
      options: [
        { id: "a", text: "Italia", isCorrect: false },
        { id: "b", text: "Irlanda", isCorrect: true },
        { id: "c", text: "Costa do Marfim", isCorrect: false },
        { id: "d", text: "Hungria", isCorrect: false },
      ],
      explanation: "A bandeira da Irlanda e verde (catolicos), laranja (protestantes) e branca (paz entre os dois grupos) na vertical.",
    },
    {
      id: "q12",
      text: "Bandeira vermelha e branca com xadrez — qual selecao?",
      options: [
        { id: "a", text: "Polonia", isCorrect: false },
        { id: "b", text: "Croacia", isCorrect: true },
        { id: "c", text: "Serbia", isCorrect: false },
        { id: "d", text: "Eslovenia", isCorrect: false },
      ],
      explanation: "O xadrez vermelho e branco (sahovnica) e simbolo da Croacia desde a Idade Media.",
    },
    {
      id: "q13",
      text: "Bandeira toda vermelha com estrela amarela — qual pais asiatico?",
      options: [
        { id: "a", text: "China", isCorrect: false },
        { id: "b", text: "Vietna", isCorrect: true },
        { id: "c", text: "Coreia do Norte", isCorrect: false },
        { id: "d", text: "Turquia", isCorrect: false },
      ],
      explanation: "A bandeira do Vietna foi adotada em 1955. A estrela amarela de cinco pontas representa as cinco classes sociais.",
    },
    {
      id: "q14",
      text: "Qual selecao tem sol dourado na bandeira azul celeste?",
      options: [
        { id: "a", text: "Argentina", isCorrect: false },
        { id: "b", text: "Uruguai", isCorrect: true },
        { id: "c", text: "Guatemala", isCorrect: false },
        { id: "d", text: "Nicaragua", isCorrect: false },
      ],
      explanation: "O sol na bandeira do Uruguai e o Sol de Maio, mesmo simbolo da Argentina, referente a Revolucao de Maio.",
    },
    {
      id: "q15",
      text: "Bandeira tricolor preta, vermelha e dourada na horizontal — qual pais?",
      options: [
        { id: "a", text: "Belgica", isCorrect: false },
        { id: "b", text: "Alemanha", isCorrect: true },
        { id: "c", text: "Angola", isCorrect: false },
        { id: "d", text: "Uganda", isCorrect: false },
      ],
      explanation: "As cores da bandeira alema (preto, vermelho e dourado) vem dos uniformes dos voluntarios nas Guerras Napoleonicas.",
    },
  ],
};
