import type { Quiz } from "@/lib/types";

export const capitaisDoMundo: Quiz = {
  id: "capitais-do-mundo",
  slug: "quiz-capitais-do-mundo",
  title: "Quiz Capitais do Mundo",
  description: "Você sabe as capitais dos países? Teste sua geografia em 15 perguntas!",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🌍",
  color: "#3B82F6",
  tags: ["geografia", "capitais", "paises", "conhecimentos-gerais"],
  createdAt: "2026-06-08",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "CIA World Factbook — Country Profiles", organization: "CIA", accessedAt: "2026-07-12" },
    { label: "United Nations — Member States", organization: "Nações Unidas", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Você conhece as capitais dos países? Teste sua geografia em 15 perguntas.",
  questions: [
    {
      id: "q1",
      text: "Qual é a capital da Austrália?",
      options: [
        { id: "a", text: "Sydney", isCorrect: false },
        { id: "b", text: "Melbourne", isCorrect: false },
        { id: "c", text: "Canberra", isCorrect: true },
        { id: "d", text: "Brisbane", isCorrect: false },
      ],
      explanation: "Muita gente acha que é Sydney, mas a capital é Canberra! Foi construída especificamente pra ser capital.",
    },
    {
      id: "q2",
      text: "Qual é a capital da Turquia?",
      options: [
        { id: "a", text: "Istambul", isCorrect: false },
        { id: "b", text: "Ancara", isCorrect: true },
        { id: "c", text: "Izmir", isCorrect: false },
        { id: "d", text: "Antália", isCorrect: false },
      ],
      explanation: "Istambul é a maior cidade, mas a capital é Ancara desde 1923.",
    },
    {
      id: "q3",
      text: "Qual é a capital do Canadá?",
      options: [
        { id: "a", text: "Toronto", isCorrect: false },
        { id: "b", text: "Vancouver", isCorrect: false },
        { id: "c", text: "Montreal", isCorrect: false },
        { id: "d", text: "Ottawa", isCorrect: true },
      ],
      explanation: "Ottawa é a capital do Canadá, não Toronto (que é a maior cidade).",
    },
    {
      id: "q4",
      text: "Qual é a capital da África do Sul? (Dica: tem 3 capitais)",
      options: [
        { id: "a", text: "Joanesburgo", isCorrect: false },
        { id: "b", text: "Cidade do Cabo", isCorrect: false },
        { id: "c", text: "Pretória", isCorrect: true },
        { id: "d", text: "Durban", isCorrect: false },
      ],
      explanation: "A África do Sul tem 3 capitais: Pretória (executiva), Cidade do Cabo (legislativa) e Bloemfontein (judiciária).",
    },
    {
      id: "q5",
      text: "Qual é a capital do Marrocos?",
      options: [
        { id: "a", text: "Casablanca", isCorrect: false },
        { id: "b", text: "Marrakech", isCorrect: false },
        { id: "c", text: "Rabat", isCorrect: true },
        { id: "d", text: "Fez", isCorrect: false },
      ],
      explanation: "Rabat é a capital. Casablanca é a maior cidade e Marrakech a mais turística.",
    },
    {
      id: "q6",
      text: "Qual é a capital da Nova Zelândia?",
      options: [
        { id: "a", text: "Auckland", isCorrect: false },
        { id: "b", text: "Queenstown", isCorrect: false },
        { id: "c", text: "Christchurch", isCorrect: false },
        { id: "d", text: "Wellington", isCorrect: true },
      ],
      explanation: "Wellington é a capital! Auckland é a maior cidade mas fica na Ilha Norte.",
    },
    {
      id: "q7",
      text: "Qual é a capital do Paraguai?",
      options: [
        { id: "a", text: "Ciudad del Este", isCorrect: false },
        { id: "b", text: "Assunção", isCorrect: true },
        { id: "c", text: "Encarnación", isCorrect: false },
        { id: "d", text: "San Lorenzo", isCorrect: false },
      ],
      explanation: "Assunção (Asunción) é a capital e maior cidade do Paraguai, nosso vizinho.",
    },
    {
      id: "q8",
      text: "Qual é a capital da Suíça?",
      options: [
        { id: "a", text: "Zurique", isCorrect: false },
        { id: "b", text: "Genebra", isCorrect: false },
        { id: "c", text: "Berna", isCorrect: true },
        { id: "d", text: "Basileia", isCorrect: false },
      ],
      explanation: "Berna é a capital federal. Zurique é a maior cidade e Genebra a sede da ONU.",
    },
    {
      id: "q9",
      text: "Qual é a capital de Myanmar (Birmânia)?",
      options: [
        { id: "a", text: "Rangum", isCorrect: false },
        { id: "b", text: "Mandalay", isCorrect: false },
        { id: "c", text: "Naypyidaw", isCorrect: true },
        { id: "d", text: "Bago", isCorrect: false },
      ],
      explanation: "Naypyidaw se tornou capital em 2006, substituindo Rangum. É uma das capitais mais 'vazias' do mundo!",
    },
    {
      id: "q10",
      text: "Qual é a capital da Colômbia?",
      options: [
        { id: "a", text: "Medellín", isCorrect: false },
        { id: "b", text: "Bogotá", isCorrect: true },
        { id: "c", text: "Cartagena", isCorrect: false },
        { id: "d", text: "Cali", isCorrect: false },
      ],
      explanation: "Bogotá é a capital e fica a 2.640 metros de altitude nos Andes!",
    },
    {
      id: "q11",
      text: "Qual é a capital da Noruega?",
      options: [
        { id: "a", text: "Bergen", isCorrect: false },
        { id: "b", text: "Oslo", isCorrect: true },
        { id: "c", text: "Stavanger", isCorrect: false },
        { id: "d", text: "Tromsø", isCorrect: false },
      ],
      explanation: "Oslo é a capital e maior cidade da Noruega, localizada no sul do país.",
    },
    {
      id: "q12",
      text: "Qual é a capital do Vietnã?",
      options: [
        { id: "a", text: "Ho Chi Minh", isCorrect: false },
        { id: "b", text: "Da Nang", isCorrect: false },
        { id: "c", text: "Hanói", isCorrect: true },
        { id: "d", text: "Huế", isCorrect: false },
      ],
      explanation: "Hanói é a capital. Ho Chi Minh (antiga Saigon) é a maior cidade.",
    },
    {
      id: "q13",
      text: "Qual é a capital do Egito?",
      options: [
        { id: "a", text: "Alexandria", isCorrect: false },
        { id: "b", text: "Cairo", isCorrect: true },
        { id: "c", text: "Luxor", isCorrect: false },
        { id: "d", text: "Gizé", isCorrect: false },
      ],
      explanation: "Cairo é a maior cidade da África e do mundo árabe, com mais de 20 milhões de habitantes na região metropolitana.",
    },
    {
      id: "q14",
      text: "Qual país tem Ulan Bator como capital?",
      options: [
        { id: "a", text: "Cazaquistão", isCorrect: false },
        { id: "b", text: "Mongólia", isCorrect: true },
        { id: "c", text: "Quirguistão", isCorrect: false },
        { id: "d", text: "Tibete", isCorrect: false },
      ],
      explanation: "Ulan Bator é a capital da Mongólia e abriga quase metade da população do país!",
    },
    {
      id: "q15",
      text: "Qual é a capital do Sri Lanka?",
      options: [
        { id: "a", text: "Colombo", isCorrect: false },
        { id: "b", text: "Sri Jayawardenepura Kotte", isCorrect: true },
        { id: "c", text: "Kandy", isCorrect: false },
        { id: "d", text: "Galle", isCorrect: false },
      ],
      explanation: "A capital oficial é Sri Jayawardenepura Kotte, mas Colombo é a maior cidade e capital comercial.",
    },
  ],
};
