import type { Quiz } from "@/lib/types";

export const copa2026Trivia: Quiz = {
  id: "copa-2026-trivia",
  slug: "quanto-voce-sabe-sobre-a-copa-2026",
  title: "Quanto voce sabe sobre a Copa do Mundo 2026?",
  description:
    "Teste seus conhecimentos sobre a maior Copa da historia! 48 selecoes, 3 paises-sede e muitas curiosidades. Cuidado: 3 erros e voce perde!",
  type: "trivia",
  category: "copa-do-mundo",
  emoji: "🏆",
  color: "#16A34A",
  tags: ["copa do mundo", "futebol", "2026", "fifa", "selecoes"],
  createdAt: "2026-06-08",
  featured: true,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "FIFA.com — History of the FIFA World Cup", url: "https://www.fifa.com/en/tournaments/mens/worldcup", organization: "FIFA", accessedAt: "2026-07-12" },
    { label: "FIFA.com — FIFA World Cup 26", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Teste seus conhecimentos sobre a história e as curiosidades da Copa do Mundo, do primeiro torneio em 1930 até a edição de 2026.",
  questions: [
    {
      id: "q1",
      text: "Quantas selecoes participam da Copa do Mundo 2026?",
      options: [
        { id: "a", text: "32", isCorrect: false },
        { id: "b", text: "48", isCorrect: true },
        { id: "c", text: "40", isCorrect: false },
        { id: "d", text: "64", isCorrect: false },
      ],
      explanation: "A Copa de 2026 e a primeira com 48 selecoes, um aumento em relacao as 32 de edicoes anteriores.",
    },
    {
      id: "q2",
      text: "Quais paises sediam a Copa do Mundo 2026?",
      options: [
        { id: "a", text: "EUA, Canada e Mexico", isCorrect: true },
        { id: "b", text: "EUA, Brasil e Argentina", isCorrect: false },
        { id: "c", text: "Canada, Mexico e Colombia", isCorrect: false },
        { id: "d", text: "EUA, Canada e Jamaica", isCorrect: false },
      ],
      explanation: "E a primeira Copa com 3 paises-sede na historia!",
    },
    {
      id: "q3",
      text: "Qual selecao e a maior campea da Copa do Mundo?",
      options: [
        { id: "a", text: "Alemanha", isCorrect: false },
        { id: "b", text: "Italia", isCorrect: false },
        { id: "c", text: "Brasil", isCorrect: true },
        { id: "d", text: "Argentina", isCorrect: false },
      ],
      explanation: "O Brasil e pentacampeao mundial (1958, 1962, 1970, 1994, 2002).",
    },
    {
      id: "q4",
      text: "Quantos jogos serao disputados na Copa 2026?",
      options: [
        { id: "a", text: "64", isCorrect: false },
        { id: "b", text: "80", isCorrect: false },
        { id: "c", text: "104", isCorrect: true },
        { id: "d", text: "96", isCorrect: false },
      ],
      explanation: "Com 48 selecoes, o numero de jogos subiu de 64 para 104.",
    },
    {
      id: "q5",
      text: "Quem venceu a Copa do Mundo de 2022 no Qatar?",
      options: [
        { id: "a", text: "Franca", isCorrect: false },
        { id: "b", text: "Argentina", isCorrect: true },
        { id: "c", text: "Brasil", isCorrect: false },
        { id: "d", text: "Croacia", isCorrect: false },
      ],
      explanation: "A Argentina venceu a Franca nos penaltis na final de 2022.",
    },
    {
      id: "q6",
      text: "Qual jogador tem mais gols em Copas do Mundo na historia?",
      options: [
        { id: "a", text: "Pele", isCorrect: false },
        { id: "b", text: "Ronaldo Fenomeno", isCorrect: false },
        { id: "c", text: "Miroslav Klose", isCorrect: true },
        { id: "d", text: "Lionel Messi", isCorrect: false },
      ],
      explanation: "Klose marcou 16 gols em Copas (2002-2014), superando Ronaldo (15).",
    },
    {
      id: "q7",
      text: "Em que ano o Brasil ganhou sua ultima Copa do Mundo?",
      options: [
        { id: "a", text: "1998", isCorrect: false },
        { id: "b", text: "2002", isCorrect: true },
        { id: "c", text: "2006", isCorrect: false },
        { id: "d", text: "1994", isCorrect: false },
      ],
      explanation: "O penta veio em 2002, na Coreia e Japao, com Ronaldo, Rivaldo e Ronaldinho.",
    },
    {
      id: "q8",
      text: "Qual estadio sera a sede da final da Copa 2026?",
      options: [
        { id: "a", text: "Estadio Azteca (Mexico)", isCorrect: false },
        { id: "b", text: "MetLife Stadium (EUA)", isCorrect: true },
        { id: "c", text: "SoFi Stadium (EUA)", isCorrect: false },
        { id: "d", text: "BMO Field (Canada)", isCorrect: false },
      ],
      explanation: "O MetLife Stadium, em Nova Jersey, recebera a grande final.",
    },
    {
      id: "q9",
      text: "Qual selecao nunca venceu uma Copa do Mundo?",
      options: [
        { id: "a", text: "Uruguai", isCorrect: false },
        { id: "b", text: "Espanha", isCorrect: false },
        { id: "c", text: "Holanda", isCorrect: true },
        { id: "d", text: "Inglaterra", isCorrect: false },
      ],
      explanation: "A Holanda chegou a 3 finais (1974, 1978, 2010) mas nunca conquistou o titulo.",
    },
    {
      id: "q10",
      text: "Qual foi o placar da maior goleada da historia das Copas?",
      options: [
        { id: "a", text: "7 x 1", isCorrect: false },
        { id: "b", text: "10 x 1", isCorrect: true },
        { id: "c", text: "9 x 0", isCorrect: false },
        { id: "d", text: "8 x 0", isCorrect: false },
      ],
      explanation: "Hungria 10 x 1 El Salvador em 1982. O 7x1 do Brasil (2014) e 'so' o 6o maior.",
    },
    {
      id: "q11",
      text: "Quem e o jogador com mais Copas do Mundo disputadas?",
      options: [
        { id: "a", text: "Lionel Messi", isCorrect: true },
        { id: "b", text: "Cristiano Ronaldo", isCorrect: false },
        { id: "c", text: "Lothar Matthaus", isCorrect: false },
        { id: "d", text: "Cafu", isCorrect: false },
      ],
      explanation: "Messi disputou 5 Copas (2006, 2010, 2014, 2018, 2022), assim como Matthaus e Carbajal.",
    },
    {
      id: "q12",
      text: "Qual pais sediou a primeira Copa do Mundo em 1930?",
      options: [
        { id: "a", text: "Brasil", isCorrect: false },
        { id: "b", text: "Italia", isCorrect: false },
        { id: "c", text: "Uruguai", isCorrect: true },
        { id: "d", text: "Argentina", isCorrect: false },
      ],
      explanation: "O Uruguai sediou e venceu a primeira Copa em 1930.",
    },
    {
      id: "q13",
      text: "Qual selecao tem a maior sequencia invicta em Copas?",
      options: [
        { id: "a", text: "Brasil (13 jogos)", isCorrect: true },
        { id: "b", text: "Alemanha (11 jogos)", isCorrect: false },
        { id: "c", text: "Italia (10 jogos)", isCorrect: false },
        { id: "d", text: "Argentina (9 jogos)", isCorrect: false },
      ],
      explanation: "O Brasil ficou 13 jogos invicto entre as Copas de 2002 e 2006.",
    },
    {
      id: "q14",
      text: "Quantos mascotes oficiais tem a Copa 2026?",
      options: [
        { id: "a", text: "1", isCorrect: false },
        { id: "b", text: "2", isCorrect: false },
        { id: "c", text: "3", isCorrect: true },
        { id: "d", text: "4", isCorrect: false },
      ],
      explanation: "A Copa 2026 e a primeira com 3 mascotes: Maple (alce, Canada), Zayu (onca-pintada, Mexico) e Clutch (aguia-careca, EUA).",
    },
    {
      id: "q15",
      text: "Qual selecao foi campea em 2018 na Russia?",
      options: [
        { id: "a", text: "Croacia", isCorrect: false },
        { id: "b", text: "Franca", isCorrect: true },
        { id: "c", text: "Belgica", isCorrect: false },
        { id: "d", text: "Inglaterra", isCorrect: false },
      ],
      explanation: "A Franca venceu a Croacia por 4x2 na final em Moscou.",
    },
    {
      id: "q16",
      text: "Quem marcou o gol mais rapido da historia das Copas?",
      options: [
        { id: "a", text: "Hakan Sukur (11 segundos)", isCorrect: true },
        { id: "b", text: "Clint Dempsey (30 segundos)", isCorrect: false },
        { id: "c", text: "Ronaldo (15 segundos)", isCorrect: false },
        { id: "d", text: "Neymar (20 segundos)", isCorrect: false },
      ],
      explanation: "Hakan Sukur (Turquia) marcou em 11 segundos contra a Coreia em 2002.",
    },
    {
      id: "q17",
      text: "Quantas vezes a Alemanha foi campea mundial?",
      options: [
        { id: "a", text: "3 vezes", isCorrect: false },
        { id: "b", text: "4 vezes", isCorrect: true },
        { id: "c", text: "5 vezes", isCorrect: false },
        { id: "d", text: "2 vezes", isCorrect: false },
      ],
      explanation: "A Alemanha foi campea em 1954, 1974, 1990 e 2014.",
    },
    {
      id: "q18",
      text: "Em qual Copa aconteceu o famoso 'Maracanazo'?",
      options: [
        { id: "a", text: "1950", isCorrect: true },
        { id: "b", text: "1954", isCorrect: false },
        { id: "c", text: "1962", isCorrect: false },
        { id: "d", text: "1958", isCorrect: false },
      ],
      explanation: "O Uruguai venceu o Brasil na final de 1950, no Maracana lotado.",
    },
    {
      id: "q19",
      text: "Qual jogador brasileiro foi artilheiro da Copa de 2002?",
      options: [
        { id: "a", text: "Rivaldo", isCorrect: false },
        { id: "b", text: "Ronaldo", isCorrect: true },
        { id: "c", text: "Ronaldinho", isCorrect: false },
        { id: "d", text: "Roberto Carlos", isCorrect: false },
      ],
      explanation: "Ronaldo marcou 8 gols na Copa de 2002, incluindo 2 na final.",
    },
    {
      id: "q20",
      text: "Qual selecao africana foi a primeira a chegar nas quartas de final?",
      options: [
        { id: "a", text: "Nigeria", isCorrect: false },
        { id: "b", text: "Camaroes", isCorrect: true },
        { id: "c", text: "Senegal", isCorrect: false },
        { id: "d", text: "Gana", isCorrect: false },
      ],
      explanation: "Camaroes, liderado por Roger Milla, chegou as quartas em 1990.",
    },
    {
      id: "q21",
      text: "Quantas Copas a Italia venceu?",
      options: [
        { id: "a", text: "3 vezes", isCorrect: false },
        { id: "b", text: "4 vezes", isCorrect: true },
        { id: "c", text: "2 vezes", isCorrect: false },
        { id: "d", text: "5 vezes", isCorrect: false },
      ],
      explanation: "A Italia foi campea em 1934, 1938, 1982 e 2006.",
    },
    {
      id: "q22",
      text: "Qual a bola oficial da Copa de 2026?",
      options: [
        { id: "a", text: "Brazuca", isCorrect: false },
        { id: "b", text: "Telstar", isCorrect: false },
        { id: "c", text: "Al Rihla", isCorrect: false },
        { id: "d", text: "adidas Trionda", isCorrect: true },
      ],
      explanation: "A Trionda e a bola oficial da Copa 2026, produzida pela adidas. O nome homenageia as 3 nacoes-sede.",
    },
    {
      id: "q23",
      text: "Quem foi o tecnico do Brasil na Copa de 1970?",
      options: [
        { id: "a", text: "Zagallo", isCorrect: true },
        { id: "b", text: "Tele Santana", isCorrect: false },
        { id: "c", text: "Parreira", isCorrect: false },
        { id: "d", text: "Felipao", isCorrect: false },
      ],
      explanation: "Zagallo comandou o Brasil no tri em 1970, com Pele, Tostao e Jairzinho.",
    },
    {
      id: "q24",
      text: "Em que ano Pele ganhou sua primeira Copa do Mundo?",
      options: [
        { id: "a", text: "1954", isCorrect: false },
        { id: "b", text: "1958", isCorrect: true },
        { id: "c", text: "1962", isCorrect: false },
        { id: "d", text: "1966", isCorrect: false },
      ],
      explanation: "Pele tinha apenas 17 anos quando o Brasil venceu a Copa de 1958 na Suecia.",
    },
    {
      id: "q25",
      text: "Quantos grupos tera a fase de grupos da Copa 2026?",
      options: [
        { id: "a", text: "8 grupos", isCorrect: false },
        { id: "b", text: "12 grupos", isCorrect: true },
        { id: "c", text: "16 grupos", isCorrect: false },
        { id: "d", text: "10 grupos", isCorrect: false },
      ],
      explanation: "Com 48 selecoes, serao 12 grupos de 4 equipes cada.",
    },
  ],
};
