import type { Quiz } from "@/lib/types";

export const copa2026Trivia: Quiz = {
  id: "copa-2026-trivia",
  slug: "quanto-voce-sabe-sobre-a-copa-2026",
  title: "Quanto você sabe sobre a Copa do Mundo 2026?",
  description:
    "Teste seus conhecimentos sobre a maior Copa da história! 48 seleções, 3 países-sede e muitas curiosidades. Cuidado: 3 erros e você perde!",
  type: "trivia",
  category: "copa-do-mundo",
  emoji: "🏆",
  color: "#16A34A",
  tags: ["copa do mundo", "futebol", "2026", "fifa", "selecoes"],
  createdAt: "2026-06-08",
  featured: true,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "FIFA.com — History of the FIFA World Cup", url: "https://www.fifa.com/en/tournaments/mens/worldcup", organization: "FIFA", accessedAt: "2026-07-12" },
    { label: "FIFA.com — FIFA World Cup 26", url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026", organization: "FIFA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "De 1930 até 2026, a Copa do Mundo acumulou histórias incríveis — este quiz cobre sedes, recordes, polêmicas e momentos que todo fã deveria conhecer.",
  questions: [
    {
      id: "q1",
      text: "Quantas seleções participam da Copa do Mundo 2026?",
      options: [
        { id: "a", text: "32", isCorrect: false },
        { id: "b", text: "48", isCorrect: true },
        { id: "c", text: "40", isCorrect: false },
        { id: "d", text: "64", isCorrect: false },
      ],
      explanation: "A Copa de 2026 é a primeira com 48 seleções, um aumento em relação às 32 de edições anteriores.",
    },
    {
      id: "q2",
      text: "Quais países sediam a Copa do Mundo 2026?",
      options: [
        { id: "a", text: "EUA, Canadá e México", isCorrect: true },
        { id: "b", text: "EUA, Brasil e Argentina", isCorrect: false },
        { id: "c", text: "Canadá, México e Colômbia", isCorrect: false },
        { id: "d", text: "EUA, Canadá e Jamaica", isCorrect: false },
      ],
      explanation: "É a primeira Copa com 3 países-sede na história!",
    },
    {
      id: "q3",
      text: "Qual seleção é a maior campeã da Copa do Mundo?",
      options: [
        { id: "a", text: "Alemanha", isCorrect: false },
        { id: "b", text: "Itália", isCorrect: false },
        { id: "c", text: "Brasil", isCorrect: true },
        { id: "d", text: "Argentina", isCorrect: false },
      ],
      explanation: "O Brasil é pentacampeão mundial (1958, 1962, 1970, 1994, 2002).",
    },
    {
      id: "q4",
      text: "Quantos jogos serão disputados na Copa 2026?",
      options: [
        { id: "a", text: "64", isCorrect: false },
        { id: "b", text: "80", isCorrect: false },
        { id: "c", text: "104", isCorrect: true },
        { id: "d", text: "96", isCorrect: false },
      ],
      explanation: "Com 48 seleções, o número de jogos subiu de 64 para 104.",
    },
    {
      id: "q5",
      text: "Quem venceu a Copa do Mundo de 2022 no Qatar?",
      options: [
        { id: "a", text: "França", isCorrect: false },
        { id: "b", text: "Argentina", isCorrect: true },
        { id: "c", text: "Brasil", isCorrect: false },
        { id: "d", text: "Croácia", isCorrect: false },
      ],
      explanation: "A Argentina venceu a França nos pênaltis na final de 2022.",
    },
    {
      id: "q6",
      text: "Qual jogador tem mais gols em Copas do Mundo na história?",
      options: [
        { id: "a", text: "Pelé", isCorrect: false },
        { id: "b", text: "Ronaldo Fenômeno", isCorrect: false },
        { id: "c", text: "Miroslav Klose", isCorrect: true },
        { id: "d", text: "Lionel Messi", isCorrect: false },
      ],
      explanation: "Klose marcou 16 gols em Copas (2002-2014), superando Ronaldo (15).",
    },
    {
      id: "q7",
      text: "Em que ano o Brasil ganhou sua última Copa do Mundo?",
      options: [
        { id: "a", text: "1998", isCorrect: false },
        { id: "b", text: "2002", isCorrect: true },
        { id: "c", text: "2006", isCorrect: false },
        { id: "d", text: "1994", isCorrect: false },
      ],
      explanation: "O penta veio em 2002, na Coreia e Japão, com Ronaldo, Rivaldo e Ronaldinho.",
    },
    {
      id: "q8",
      text: "Qual estádio será a sede da final da Copa 2026?",
      options: [
        { id: "a", text: "Estádio Azteca (México)", isCorrect: false },
        { id: "b", text: "MetLife Stadium (EUA)", isCorrect: true },
        { id: "c", text: "SoFi Stadium (EUA)", isCorrect: false },
        { id: "d", text: "BMO Field (Canadá)", isCorrect: false },
      ],
      explanation: "O MetLife Stadium, em Nova Jersey, receberá a grande final.",
    },
    {
      id: "q9",
      text: "Qual seleção nunca venceu uma Copa do Mundo?",
      options: [
        { id: "a", text: "Uruguai", isCorrect: false },
        { id: "b", text: "Espanha", isCorrect: false },
        { id: "c", text: "Holanda", isCorrect: true },
        { id: "d", text: "Inglaterra", isCorrect: false },
      ],
      explanation: "A Holanda chegou a 3 finais (1974, 1978, 2010) mas nunca conquistou o título.",
    },
    {
      id: "q10",
      text: "Qual foi o placar da maior goleada da história das Copas?",
      options: [
        { id: "a", text: "7 x 1", isCorrect: false },
        { id: "b", text: "10 x 1", isCorrect: true },
        { id: "c", text: "9 x 0", isCorrect: false },
        { id: "d", text: "8 x 0", isCorrect: false },
      ],
      explanation: "Hungria 10 x 1 El Salvador em 1982. O 7x1 do Brasil (2014) é 'só' o 6º maior.",
    },
    {
      id: "q11",
      text: "Quem é o jogador com mais Copas do Mundo disputadas?",
      options: [
        { id: "a", text: "Lionel Messi", isCorrect: true },
        { id: "b", text: "Cristiano Ronaldo", isCorrect: false },
        { id: "c", text: "Lothar Matthäus", isCorrect: false },
        { id: "d", text: "Cafu", isCorrect: false },
      ],
      explanation: "Messi disputou 5 Copas (2006, 2010, 2014, 2018, 2022), assim como Matthäus e Carbajal.",
    },
    {
      id: "q12",
      text: "Qual país sediou a primeira Copa do Mundo em 1930?",
      options: [
        { id: "a", text: "Brasil", isCorrect: false },
        { id: "b", text: "Itália", isCorrect: false },
        { id: "c", text: "Uruguai", isCorrect: true },
        { id: "d", text: "Argentina", isCorrect: false },
      ],
      explanation: "O Uruguai sediou e venceu a primeira Copa em 1930.",
    },
    {
      id: "q13",
      text: "Qual seleção tem a maior sequência invicta em Copas?",
      options: [
        { id: "a", text: "Brasil (13 jogos)", isCorrect: true },
        { id: "b", text: "Alemanha (11 jogos)", isCorrect: false },
        { id: "c", text: "Itália (10 jogos)", isCorrect: false },
        { id: "d", text: "Argentina (9 jogos)", isCorrect: false },
      ],
      explanation: "O Brasil ficou 13 jogos invicto entre as Copas de 2002 e 2006.",
    },
    {
      id: "q14",
      text: "Quantos mascotes oficiais tem a Copa 2026?",
      options: [
        { id: "a", text: "1", isCorrect: false },
        { id: "b", text: "2", isCorrect: false },
        { id: "c", text: "3", isCorrect: true },
        { id: "d", text: "4", isCorrect: false },
      ],
      explanation: "A Copa 2026 é a primeira com 3 mascotes: Maple (alce, Canadá), Zayu (onça-pintada, México) e Clutch (águia-careca, EUA).",
    },
    {
      id: "q15",
      text: "Qual seleção foi campeã em 2018 na Rússia?",
      options: [
        { id: "a", text: "Croácia", isCorrect: false },
        { id: "b", text: "França", isCorrect: true },
        { id: "c", text: "Bélgica", isCorrect: false },
        { id: "d", text: "Inglaterra", isCorrect: false },
      ],
      explanation: "A França venceu a Croácia por 4x2 na final em Moscou.",
    },
    {
      id: "q16",
      text: "Quem marcou o gol mais rápido da história das Copas?",
      options: [
        { id: "a", text: "Hakan Şükür (11 segundos)", isCorrect: true },
        { id: "b", text: "Clint Dempsey (30 segundos)", isCorrect: false },
        { id: "c", text: "Ronaldo (15 segundos)", isCorrect: false },
        { id: "d", text: "Neymar (20 segundos)", isCorrect: false },
      ],
      explanation: "Hakan Şükür (Turquia) marcou em 11 segundos contra a Coreia em 2002.",
    },
    {
      id: "q17",
      text: "Quantas vezes a Alemanha foi campeã mundial?",
      options: [
        { id: "a", text: "3 vezes", isCorrect: false },
        { id: "b", text: "4 vezes", isCorrect: true },
        { id: "c", text: "5 vezes", isCorrect: false },
        { id: "d", text: "2 vezes", isCorrect: false },
      ],
      explanation: "A Alemanha foi campeã em 1954, 1974, 1990 e 2014.",
    },
    {
      id: "q18",
      text: "Em qual Copa aconteceu o famoso 'Maracanazo'?",
      options: [
        { id: "a", text: "1950", isCorrect: true },
        { id: "b", text: "1954", isCorrect: false },
        { id: "c", text: "1962", isCorrect: false },
        { id: "d", text: "1958", isCorrect: false },
      ],
      explanation: "O Uruguai venceu o Brasil na final de 1950, no Maracanã lotado.",
    },
    {
      id: "q19",
      text: "Qual jogador brasileiro foi artilheiro da Copa de 2002?",
      options: [
        { id: "a", text: "Rivaldo", isCorrect: false },
        { id: "b", text: "Ronaldo", isCorrect: true },
        { id: "c", text: "Ronaldinho", isCorrect: false },
        { id: "d", text: "Roberto Carlos", isCorrect: false },
      ],
      explanation: "Ronaldo marcou 8 gols na Copa de 2002, incluindo 2 na final.",
    },
    {
      id: "q20",
      text: "Qual seleção africana foi a primeira a chegar nas quartas de final?",
      options: [
        { id: "a", text: "Nigéria", isCorrect: false },
        { id: "b", text: "Camarões", isCorrect: true },
        { id: "c", text: "Senegal", isCorrect: false },
        { id: "d", text: "Gana", isCorrect: false },
      ],
      explanation: "Camarões, liderado por Roger Milla, chegou às quartas em 1990.",
    },
    {
      id: "q21",
      text: "Quantas Copas a Itália venceu?",
      options: [
        { id: "a", text: "3 vezes", isCorrect: false },
        { id: "b", text: "4 vezes", isCorrect: true },
        { id: "c", text: "2 vezes", isCorrect: false },
        { id: "d", text: "5 vezes", isCorrect: false },
      ],
      explanation: "A Itália foi campeã em 1934, 1938, 1982 e 2006.",
    },
    {
      id: "q22",
      text: "Qual a bola oficial da Copa de 2026?",
      options: [
        { id: "a", text: "Brazuca", isCorrect: false },
        { id: "b", text: "Telstar", isCorrect: false },
        { id: "c", text: "Al Rihla", isCorrect: false },
        { id: "d", text: "adidas Trionda", isCorrect: true },
      ],
      explanation: "A Trionda é a bola oficial da Copa 2026, produzida pela adidas. O nome homenageia as 3 nações-sede.",
    },
    {
      id: "q23",
      text: "Quem foi o técnico do Brasil na Copa de 1970?",
      options: [
        { id: "a", text: "Zagallo", isCorrect: true },
        { id: "b", text: "Telê Santana", isCorrect: false },
        { id: "c", text: "Parreira", isCorrect: false },
        { id: "d", text: "Felipão", isCorrect: false },
      ],
      explanation: "Zagallo comandou o Brasil no tri em 1970, com Pelé, Tostão e Jairzinho.",
    },
    {
      id: "q24",
      text: "Em que ano Pelé ganhou sua primeira Copa do Mundo?",
      options: [
        { id: "a", text: "1954", isCorrect: false },
        { id: "b", text: "1958", isCorrect: true },
        { id: "c", text: "1962", isCorrect: false },
        { id: "d", text: "1966", isCorrect: false },
      ],
      explanation: "Pelé tinha apenas 17 anos quando o Brasil venceu a Copa de 1958 na Suécia.",
    },
    {
      id: "q25",
      text: "Quantos grupos terá a fase de grupos da Copa 2026?",
      options: [
        { id: "a", text: "8 grupos", isCorrect: false },
        { id: "b", text: "12 grupos", isCorrect: true },
        { id: "c", text: "16 grupos", isCorrect: false },
        { id: "d", text: "10 grupos", isCorrect: false },
      ],
      explanation: "Com 48 seleções, serão 12 grupos de 4 equipes cada.",
    },
  ],
};
