import type { Quiz } from "@/lib/types";

export const curiosidadesCiencia: Quiz = {
  id: "curiosidades-ciencia",
  slug: "quiz-curiosidades-da-ciencia",
  title: "Quiz Curiosidades da Ciência",
  description: "Do espaço ao corpo humano — teste seus conhecimentos científicos!",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🔬",
  color: "#6366F1",
  tags: ["ciencia", "curiosidades", "espaco", "biologia", "educacao"],
  createdAt: "2026-06-09",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "NASA — Solar System Exploration", url: "https://solarsystem.nasa.gov/", organization: "NASA", accessedAt: "2026-07-12" },
    { label: "Britannica — Science", organization: "Encyclopædia Britannica", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Fatos sobre o espaço, o corpo humano, reações químicas e fenômenos naturais que parecem mentira mas são reais — e alguns que parecem reais mas não são.",
  questions: [
    {
      id: "q1",
      text: "Qual é o planeta mais quente do Sistema Solar?",
      options: [
        { id: "a", text: "Mercúrio", isCorrect: false },
        { id: "b", text: "Vênus", isCorrect: true },
        { id: "c", text: "Marte", isCorrect: false },
        { id: "d", text: "Júpiter", isCorrect: false },
      ],
      explanation: "Apesar de Mercúrio ser mais próximo do Sol, Vênus é mais quente (462°C) por causa do efeito estufa extremo!",
    },
    {
      id: "q2",
      text: "Quantos ossos tem o corpo humano adulto?",
      options: [
        { id: "a", text: "186", isCorrect: false },
        { id: "b", text: "206", isCorrect: true },
        { id: "c", text: "226", isCorrect: false },
        { id: "d", text: "256", isCorrect: false },
      ],
      explanation: "Bebês nascem com cerca de 270 ossos, mas muitos se fundem durante o crescimento, resultando em 206 na idade adulta.",
    },
    {
      id: "q3",
      text: "Qual é o elemento químico mais abundante no universo?",
      options: [
        { id: "a", text: "Oxigênio", isCorrect: false },
        { id: "b", text: "Carbono", isCorrect: false },
        { id: "c", text: "Hidrogênio", isCorrect: true },
        { id: "d", text: "Hélio", isCorrect: false },
      ],
      explanation: "O hidrogênio compõe cerca de 75% da massa do universo. O hélio vem em segundo, com cerca de 24%.",
    },
    {
      id: "q4",
      text: "Quanto tempo a luz do Sol demora pra chegar na Terra?",
      options: [
        { id: "a", text: "1 segundo", isCorrect: false },
        { id: "b", text: "8 minutos", isCorrect: true },
        { id: "c", text: "1 hora", isCorrect: false },
        { id: "d", text: "24 horas", isCorrect: false },
      ],
      explanation: "A luz viaja a 300.000 km/s e demora cerca de 8 minutos e 20 segundos pra percorrer os 150 milhões de km até a Terra.",
    },
    {
      id: "q5",
      text: "Qual órgão do corpo humano consome mais energia?",
      options: [
        { id: "a", text: "Coração", isCorrect: false },
        { id: "b", text: "Fígado", isCorrect: false },
        { id: "c", text: "Cérebro", isCorrect: true },
        { id: "d", text: "Músculos", isCorrect: false },
      ],
      explanation: "O cérebro consome cerca de 20% de toda energia do corpo, apesar de representar apenas 2% do peso!",
    },
    {
      id: "q6",
      text: "O que é um ano-luz?",
      options: [
        { id: "a", text: "Uma medida de tempo", isCorrect: false },
        { id: "b", text: "Uma medida de distância", isCorrect: true },
        { id: "c", text: "Uma medida de velocidade", isCorrect: false },
        { id: "d", text: "Uma medida de energia", isCorrect: false },
      ],
      explanation: "Um ano-luz equivale a cerca de 9,46 trilhões de quilômetros — a distância que a luz percorre em um ano.",
    },
    {
      id: "q7",
      text: "Qual animal é o mais rápido do mundo?",
      options: [
        { id: "a", text: "Guepardo", isCorrect: false },
        { id: "b", text: "Falcão-peregrino", isCorrect: true },
        { id: "c", text: "Agulhão-vela (peixe)", isCorrect: false },
        { id: "d", text: "Águia", isCorrect: false },
      ],
      explanation: "O falcão-peregrino atinge 389 km/h em mergulho! O guepardo é o mais rápido em terra (120 km/h).",
    },
    {
      id: "q8",
      text: "Qual porcentagem do corpo humano é água?",
      options: [
        { id: "a", text: "40-50%", isCorrect: false },
        { id: "b", text: "50-60%", isCorrect: false },
        { id: "c", text: "60-70%", isCorrect: true },
        { id: "d", text: "70-80%", isCorrect: false },
      ],
      explanation: "A porcentagem varia com a idade: bebês têm cerca de 75%, adultos 60-70%, e idosos um pouco menos.",
    },
    {
      id: "q9",
      text: "Qual cientista formulou a Teoria da Relatividade?",
      options: [
        { id: "a", text: "Isaac Newton", isCorrect: false },
        { id: "b", text: "Albert Einstein", isCorrect: true },
        { id: "c", text: "Niels Bohr", isCorrect: false },
        { id: "d", text: "Stephen Hawking", isCorrect: false },
      ],
      explanation: "Einstein publicou a Teoria da Relatividade Especial em 1905 e a Geral em 1915, revolucionando a física.",
    },
    {
      id: "q10",
      text: "O DNA humano é composto por quantos pares de cromossomos?",
      options: [
        { id: "a", text: "21", isCorrect: false },
        { id: "b", text: "23", isCorrect: true },
        { id: "c", text: "25", isCorrect: false },
        { id: "d", text: "46", isCorrect: false },
      ],
      explanation: "Temos 23 PARES, totalizando 46 cromossomos. A opção 46 é o total, não o número de pares!",
    },
    {
      id: "q11",
      text: "Qual gás as plantas absorvem da atmosfera?",
      options: [
        { id: "a", text: "Oxigênio", isCorrect: false },
        { id: "b", text: "Nitrogênio", isCorrect: false },
        { id: "c", text: "Gás carbônico (CO₂)", isCorrect: true },
        { id: "d", text: "Metano", isCorrect: false },
      ],
      explanation: "As plantas absorvem CO₂ e liberam oxigênio durante a fotossíntese, processo essencial para a vida na Terra.",
    },
    {
      id: "q12",
      text: "Qual é a temperatura do núcleo do Sol?",
      options: [
        { id: "a", text: "1 milhão de graus", isCorrect: false },
        { id: "b", text: "5 milhões de graus", isCorrect: false },
        { id: "c", text: "15 milhões de graus", isCorrect: true },
        { id: "d", text: "100 milhões de graus", isCorrect: false },
      ],
      explanation: "O núcleo do Sol atinge cerca de 15 milhões de graus Celsius, onde ocorre a fusão nuclear do hidrogênio em hélio.",
    },
    {
      id: "q13",
      text: "Quantos litros de sangue tem o corpo humano em média?",
      options: [
        { id: "a", text: "2-3 litros", isCorrect: false },
        { id: "b", text: "4-5 litros", isCorrect: true },
        { id: "c", text: "7-8 litros", isCorrect: false },
        { id: "d", text: "10-12 litros", isCorrect: false },
      ],
      explanation: "Um adulto tem em média 4,5 a 5,5 litros de sangue, que é bombeado pelo coração cerca de 100 mil vezes por dia.",
    },
    {
      id: "q14",
      text: "Qual é o metal mais abundante na crosta terrestre?",
      options: [
        { id: "a", text: "Ferro", isCorrect: false },
        { id: "b", text: "Alumínio", isCorrect: true },
        { id: "c", text: "Cobre", isCorrect: false },
        { id: "d", text: "Ouro", isCorrect: false },
      ],
      explanation: "O alumínio representa cerca de 8% da crosta terrestre. É abundante, mas só foi isolado como metal em 1825.",
    },
    {
      id: "q15",
      text: "Qual planeta do Sistema Solar tem mais luas?",
      options: [
        { id: "a", text: "Júpiter", isCorrect: false },
        { id: "b", text: "Saturno", isCorrect: true },
        { id: "c", text: "Urano", isCorrect: false },
        { id: "d", text: "Netuno", isCorrect: false },
      ],
      explanation: "Saturno tem mais de 140 luas conhecidas, ultrapassando Júpiter!",
    },
  ],
};
