import type { Quiz } from "@/lib/types";

export const filmesClassicos: Quiz = {
  id: "filmes-classicos",
  slug: "quiz-filmes-classicos",
  title: "Quiz Filmes Clássicos de Hollywood",
  description: "De Titanic a Matrix — quanto você sabe sobre os maiores filmes da história?",
  type: "trivia",
  category: "series-filmes",
  emoji: "🎬",
  color: "#FFD700",
  tags: ["filmes", "cinema", "hollywood", "classicos", "oscar"],
  createdAt: "2026-06-09",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "IMDb — Top Rated Movies", url: "https://www.imdb.com/chart/top/", organization: "IMDb", accessedAt: "2026-07-12" },
    { label: "Academy Awards Database", organization: "Academy of Motion Picture Arts and Sciences", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "De Titanic a Matrix, de Star Wars a O Poderoso Chefão — teste o que você sabe sobre os maiores filmes da história.",
  questions: [
    {
      id: "q1",
      text: "Qual filme ganhou 11 Oscars em 1998, incluindo Melhor Filme?",
      options: [
        { id: "a", text: "O Resgate do Soldado Ryan", isCorrect: false },
        { id: "b", text: "Titanic", isCorrect: true },
        { id: "c", text: "Shakespeare Apaixonado", isCorrect: false },
        { id: "d", text: "Forrest Gump", isCorrect: false },
      ],
      explanation: "Titanic igualou o recorde de Ben-Hur com 11 estatuetas do Oscar.",
    },
    {
      id: "q2",
      text: "Em Matrix, qual pílula Neo escolhe?",
      options: [
        { id: "a", text: "Azul", isCorrect: false },
        { id: "b", text: "Verde", isCorrect: false },
        { id: "c", text: "Vermelha", isCorrect: true },
        { id: "d", text: "Branca", isCorrect: false },
      ],
      explanation: "Neo escolhe a pílula vermelha oferecida por Morpheus para conhecer a verdade sobre a Matrix.",
    },
    {
      id: "q3",
      text: "Qual ator interpretou Jack em Titanic?",
      options: [
        { id: "a", text: "Brad Pitt", isCorrect: false },
        { id: "b", text: "Leonardo DiCaprio", isCorrect: true },
        { id: "c", text: "Johnny Depp", isCorrect: false },
        { id: "d", text: "Matt Damon", isCorrect: false },
      ],
      explanation: "Leonardo DiCaprio interpretou Jack Dawson ao lado de Kate Winslet (Rose) no filme de James Cameron (1997).",
    },
    {
      id: "q4",
      text: "Qual é a frase icônica de 'O Poderoso Chefão'?",
      options: [
        { id: "a", text: "Eu sou inevitável", isCorrect: false },
        { id: "b", text: "Vou fazer uma oferta irrecusável", isCorrect: true },
        { id: "c", text: "Que a Força esteja com você", isCorrect: false },
        { id: "d", text: "Eu voltarei", isCorrect: false },
      ],
      explanation: "A frase 'Vou fazer uma oferta irrecusável' (em inglês, 'I'm gonna make him an offer he can't refuse') é dita por Don Vito Corleone (Marlon Brando).",
    },
    {
      id: "q5",
      text: "Em qual planeta se passa Avatar (2009)?",
      options: [
        { id: "a", text: "Tatooine", isCorrect: false },
        { id: "b", text: "Pandora", isCorrect: true },
        { id: "c", text: "Endor", isCorrect: false },
        { id: "d", text: "Krypton", isCorrect: false },
      ],
      explanation: "Pandora é a lua fictícia do sistema Alpha Centauri, lar dos Na'vi no filme de James Cameron.",
    },
    {
      id: "q6",
      text: "Quem dirigiu Jurassic Park (1993)?",
      options: [
        { id: "a", text: "James Cameron", isCorrect: false },
        { id: "b", text: "Steven Spielberg", isCorrect: true },
        { id: "c", text: "George Lucas", isCorrect: false },
        { id: "d", text: "Ridley Scott", isCorrect: false },
      ],
      explanation: "Steven Spielberg também dirigiu E.T., A Lista de Schindler e O Resgate do Soldado Ryan.",
    },
    {
      id: "q7",
      text: "Em Vingadores: Ultimato, quem faz o estalo final?",
      options: [
        { id: "a", text: "Thor", isCorrect: false },
        { id: "b", text: "Thanos", isCorrect: false },
        { id: "c", text: "Homem de Ferro (Tony Stark)", isCorrect: true },
        { id: "d", text: "Hulk", isCorrect: false },
      ],
      explanation: "Tony Stark faz o estalo final com as Joias do Infinito, sacrificando sua vida para salvar o universo.",
    },
    {
      id: "q8",
      text: "Qual filme brasileiro ganhou indicação ao Oscar de Melhor Filme Estrangeiro em 1999?",
      options: [
        { id: "a", text: "Cidade de Deus", isCorrect: false },
        { id: "b", text: "Central do Brasil", isCorrect: true },
        { id: "c", text: "Tropa de Elite", isCorrect: false },
        { id: "d", text: "O Auto da Compadecida", isCorrect: false },
      ],
      explanation: "Central do Brasil, dirigido por Walter Salles e estrelado por Fernanda Montenegro, foi indicado ao Oscar de Melhor Filme Estrangeiro em 1999.",
    },
    {
      id: "q9",
      text: "Quantos filmes tem a saga original de Star Wars?",
      options: [
        { id: "a", text: "3", isCorrect: false },
        { id: "b", text: "6", isCorrect: false },
        { id: "c", text: "9", isCorrect: true },
        { id: "d", text: "12", isCorrect: false },
      ],
      explanation: "A saga Skywalker tem 9 filmes divididos em 3 trilogias (1977-2019).",
    },
    {
      id: "q10",
      text: "Qual é o filme de maior bilheteria de todos os tempos (até 2026)?",
      options: [
        { id: "a", text: "Vingadores: Ultimato", isCorrect: false },
        { id: "b", text: "Avatar", isCorrect: true },
        { id: "c", text: "Titanic", isCorrect: false },
        { id: "d", text: "Star Wars: O Despertar da Força", isCorrect: false },
      ],
      explanation: "Avatar (2009) arrecadou mais de US$ 2,9 bilhões mundialmente, superando Vingadores: Ultimato.",
    },
    {
      id: "q11",
      text: "Em qual cidade se passa Batman: O Cavaleiro das Trevas?",
      options: [
        { id: "a", text: "Metrópolis", isCorrect: false },
        { id: "b", text: "Nova York", isCorrect: false },
        { id: "c", text: "Gotham City", isCorrect: true },
        { id: "d", text: "Star City", isCorrect: false },
      ],
      explanation: "Gotham City é a cidade fictícia criada pela DC Comics como lar do Batman desde 1939.",
    },
    {
      id: "q12",
      text: "Qual ator disse 'Eu sou o Groot' nos filmes da Marvel?",
      options: [
        { id: "a", text: "Chris Pratt", isCorrect: false },
        { id: "b", text: "Vin Diesel", isCorrect: true },
        { id: "c", text: "Dave Bautista", isCorrect: false },
        { id: "d", text: "Bradley Cooper", isCorrect: false },
      ],
      explanation: "Vin Diesel fez a voz de Groot em todos os filmes dos Guardiões da Galáxia e nos Vingadores.",
    },
    {
      id: "q13",
      text: "Qual desses filmes NÃO é da Pixar?",
      options: [
        { id: "a", text: "Toy Story", isCorrect: false },
        { id: "b", text: "Shrek", isCorrect: true },
        { id: "c", text: "Procurando Nemo", isCorrect: false },
        { id: "d", text: "Divertida Mente", isCorrect: false },
      ],
      explanation: "Shrek é da DreamWorks Animation, não da Pixar!",
    },
    {
      id: "q14",
      text: "Em 'O Senhor dos Anéis', quem carrega o Um Anel até a Montanha da Perdição?",
      options: [
        { id: "a", text: "Aragorn", isCorrect: false },
        { id: "b", text: "Gandalf", isCorrect: false },
        { id: "c", text: "Frodo", isCorrect: true },
        { id: "d", text: "Legolas", isCorrect: false },
      ],
      explanation: "Frodo Bolseiro carrega o Um Anel acompanhado de Sam, seu fiel amigo, na trilogia de Peter Jackson.",
    },
    {
      id: "q15",
      text: "Qual personagem diz 'Hakuna Matata' no Rei Leão?",
      options: [
        { id: "a", text: "Simba e Nala", isCorrect: false },
        { id: "b", text: "Timão e Pumba", isCorrect: true },
        { id: "c", text: "Scar e as Hienas", isCorrect: false },
        { id: "d", text: "Mufasa e Rafiki", isCorrect: false },
      ],
      explanation: "Timão (suricato) e Pumba (javali) cantam 'Hakuna Matata', que significa 'sem preocupações' em suaíli.",
    },
  ],
};
