import type { Quiz } from "@/lib/types";

export const geografiaDoBrasil: Quiz = {
  id: "geografia-do-brasil",
  slug: "quiz-geografia-do-brasil",
  title: "Quiz Geografia do Brasil",
  description: "Biomas, rios, estados e regiões — quanto você manja do mapa do Brasil?",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🗺️",
  color: "#10B981",
  tags: ["geografia", "brasil", "estados", "enem", "educacao"],
  createdAt: "2026-06-09",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "IBGE — Informações sobre estados e municípios", url: "https://www.ibge.gov.br/", organization: "IBGE", accessedAt: "2026-07-12" },
    { label: "ICMBio — Biomas brasileiros", organization: "ICMBio/MMA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Biomas, rios, estados e regiões — teste o que você sabe sobre a geografia do Brasil.",
  questions: [
    {
      id: "q1",
      text: "Qual é o maior estado do Brasil em área?",
      options: [
        { id: "a", text: "Minas Gerais", isCorrect: false },
        { id: "b", text: "Pará", isCorrect: false },
        { id: "c", text: "Amazonas", isCorrect: true },
        { id: "d", text: "Mato Grosso", isCorrect: false },
      ],
      explanation: "O Amazonas tem 1,56 milhão de km² — é maior que muitos países europeus juntos!",
    },
    {
      id: "q2",
      text: "Quantos estados tem o Brasil (contando o DF)?",
      options: [
        { id: "a", text: "25", isCorrect: false },
        { id: "b", text: "26", isCorrect: false },
        { id: "c", text: "27", isCorrect: true },
        { id: "d", text: "28", isCorrect: false },
      ],
      explanation: "São 26 estados mais o Distrito Federal, totalizando 27 unidades federativas.",
    },
    {
      id: "q3",
      text: "Qual é o rio mais longo do Brasil?",
      options: [
        { id: "a", text: "Rio São Francisco", isCorrect: false },
        { id: "b", text: "Rio Amazonas", isCorrect: true },
        { id: "c", text: "Rio Paraná", isCorrect: false },
        { id: "d", text: "Rio Tocantins", isCorrect: false },
      ],
      explanation: "O Rio Amazonas tem cerca de 6.400 km de extensão e é também o maior rio do mundo em volume de água.",
    },
    {
      id: "q4",
      text: "Qual bioma ocupa a maior área do Brasil?",
      options: [
        { id: "a", text: "Cerrado", isCorrect: false },
        { id: "b", text: "Mata Atlântica", isCorrect: false },
        { id: "c", text: "Amazônia", isCorrect: true },
        { id: "d", text: "Caatinga", isCorrect: false },
      ],
      explanation: "A Amazônia ocupa cerca de 49% do território brasileiro.",
    },
    {
      id: "q5",
      text: "Qual é a capital do Mato Grosso do Sul?",
      options: [
        { id: "a", text: "Cuiabá", isCorrect: false },
        { id: "b", text: "Campo Grande", isCorrect: true },
        { id: "c", text: "Goiânia", isCorrect: false },
        { id: "d", text: "Palmas", isCorrect: false },
      ],
      explanation: "Campo Grande é a capital do MS. Cuiabá é a capital do Mato Grosso (sem o 'do Sul').",
    },
    {
      id: "q6",
      text: "Qual região do Brasil tem mais estados?",
      options: [
        { id: "a", text: "Sudeste", isCorrect: false },
        { id: "b", text: "Sul", isCorrect: false },
        { id: "c", text: "Nordeste", isCorrect: true },
        { id: "d", text: "Norte", isCorrect: false },
      ],
      explanation: "O Nordeste tem 9 estados, sendo a região com mais unidades federativas.",
    },
    {
      id: "q7",
      text: "Qual é o ponto mais alto do Brasil?",
      options: [
        { id: "a", text: "Pico da Bandeira", isCorrect: false },
        { id: "b", text: "Pico da Neblina", isCorrect: true },
        { id: "c", text: "Pico do Paraná", isCorrect: false },
        { id: "d", text: "Pico das Agulhas Negras", isCorrect: false },
      ],
      explanation: "O Pico da Neblina tem 2.993 metros e fica no Amazonas, na fronteira com a Venezuela.",
    },
    {
      id: "q8",
      text: "Qual o único país da América do Sul que NÃO faz fronteira com o Brasil?",
      options: [
        { id: "a", text: "Equador e Chile", isCorrect: true },
        { id: "b", text: "Colômbia e Peru", isCorrect: false },
        { id: "c", text: "Argentina e Paraguai", isCorrect: false },
        { id: "d", text: "Bolívia e Suriname", isCorrect: false },
      ],
      explanation: "Equador e Chile são os únicos países sul-americanos que não fazem fronteira com o Brasil.",
    },
    {
      id: "q9",
      text: "Qual estado brasileiro é o menor em área?",
      options: [
        { id: "a", text: "Alagoas", isCorrect: false },
        { id: "b", text: "Rio de Janeiro", isCorrect: false },
        { id: "c", text: "Sergipe", isCorrect: true },
        { id: "d", text: "Espírito Santo", isCorrect: false },
      ],
      explanation: "Sergipe tem apenas 21.915 km², sendo o menor estado brasileiro em área territorial.",
    },
    {
      id: "q10",
      text: "O Pantanal fica principalmente em quais estados?",
      options: [
        { id: "a", text: "Goiás e Tocantins", isCorrect: false },
        { id: "b", text: "Mato Grosso e Mato Grosso do Sul", isCorrect: true },
        { id: "c", text: "Pará e Amazonas", isCorrect: false },
        { id: "d", text: "Minas Gerais e Bahia", isCorrect: false },
      ],
      explanation: "O Pantanal ocupa partes do MT e MS, sendo a maior planície alagável do mundo (~150 mil km²).",
    },
    {
      id: "q11",
      text: "Qual cidade brasileira é conhecida como 'Capital do Frio'?",
      options: [
        { id: "a", text: "Gramado (RS)", isCorrect: false },
        { id: "b", text: "São Joaquim (SC)", isCorrect: false },
        { id: "c", text: "Urupema (SC)", isCorrect: true },
        { id: "d", text: "Campos do Jordão (SP)", isCorrect: false },
      ],
      explanation: "Urupema (SC) é considerada a cidade mais fria do Brasil, com temperaturas que chegam a -7°C.",
    },
    {
      id: "q12",
      text: "Qual é o maior arquipélago brasileiro?",
      options: [
        { id: "a", text: "Fernando de Noronha", isCorrect: false },
        { id: "b", text: "Arquipélago de Abrolhos", isCorrect: false },
        { id: "c", text: "Ilha de Marajó", isCorrect: true },
        { id: "d", text: "Ilhabela", isCorrect: false },
      ],
      explanation: "A Ilha de Marajó, no Pará, é a maior ilha fluviomarinha do mundo!",
    },
    {
      id: "q13",
      text: "Em qual estado ficam as Cataratas do Iguaçu?",
      options: [
        { id: "a", text: "Santa Catarina", isCorrect: false },
        { id: "b", text: "Paraná", isCorrect: true },
        { id: "c", text: "Rio Grande do Sul", isCorrect: false },
        { id: "d", text: "Mato Grosso do Sul", isCorrect: false },
      ],
      explanation: "As Cataratas do Iguaçu ficam em Foz do Iguaçu (PR), na fronteira com a Argentina. São Patrimônio Mundial da UNESCO.",
    },
    {
      id: "q14",
      text: "Qual fuso horário oficial do Brasil (horário de Brasília)?",
      options: [
        { id: "a", text: "GMT -2", isCorrect: false },
        { id: "b", text: "GMT -3", isCorrect: true },
        { id: "c", text: "GMT -4", isCorrect: false },
        { id: "d", text: "GMT -5", isCorrect: false },
      ],
      explanation: "O horário de Brasília (GMT -3) é o fuso oficial. O Brasil tem 4 fusos horários no total.",
    },
    {
      id: "q15",
      text: "A linha do Equador passa por quais estados brasileiros?",
      options: [
        { id: "a", text: "Amazonas, Pará, Amapá e Roraima", isCorrect: true },
        { id: "b", text: "Acre, Rondônia e Tocantins", isCorrect: false },
        { id: "c", text: "Maranhão, Piauí e Ceará", isCorrect: false },
        { id: "d", text: "Mato Grosso, Goiás e Bahia", isCorrect: false },
      ],
      explanation: "A linha do Equador cruza Amazonas, Pará, Amapá e Roraima, todos na região Norte do Brasil.",
    },
  ],
};
