import type { Quiz } from "@/lib/types";

export const golsHistoricosCopa: Quiz = {
  id: "gols-historicos-copa",
  slug: "voce-lembra-desses-gols-historicos-de-copa",
  title: "Você Lembra Desses Gols Históricos de Copa?",
  description: "De Pelé a Messi — teste sua memória sobre os gols mais marcantes das Copas!",
  type: "trivia",
  category: "copa-do-mundo",
  emoji: "🥅",
  color: "#059669",
  tags: ["copa", "gols", "futebol", "historia", "selecao"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "FIFA.com — Classic Goals", url: "https://www.fifa.com/en/tournaments/mens/worldcup", organization: "FIFA", accessedAt: "2026-07-12" },
    { label: "FIFA.com — Awards & Records", organization: "FIFA", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Reviva os gols mais marcantes da história das Copas do Mundo, de Pelé a Messi.",
  questions: [
    {
      id: "q1",
      text: "Quem fez o gol do título do Brasil na final da Copa de 2002?",
      options: [
        { id: "a", text: "Rivaldo", isCorrect: false },
        { id: "b", text: "Ronaldo (2 gols)", isCorrect: true },
        { id: "c", text: "Ronaldinho", isCorrect: false },
        { id: "d", text: "Roberto Carlos", isCorrect: false },
      ],
      explanation: "Ronaldo Fenômeno fez os 2 gols na final contra a Alemanha (2x0), se redimindo da Copa de 98.",
    },
    {
      id: "q2",
      text: "Qual jogador marcou o 'Gol do Século' na Copa de 1986?",
      options: [
        { id: "a", text: "Pelé", isCorrect: false },
        { id: "b", text: "Zidane", isCorrect: false },
        { id: "c", text: "Maradona", isCorrect: true },
        { id: "d", text: "Platini", isCorrect: false },
      ],
      explanation: "Maradona driblou meia seleção inglesa num gol histórico nas quartas de final. No mesmo jogo fez o 'Mão de Deus'.",
    },
    {
      id: "q3",
      text: "Messi marcou na final da Copa 2022. Qual foi o placar final?",
      options: [
        { id: "a", text: "Argentina 2x1 França", isCorrect: false },
        { id: "b", text: "Argentina 3x3 (pênaltis 4x2)", isCorrect: true },
        { id: "c", text: "Argentina 4x2 França", isCorrect: false },
        { id: "d", text: "Argentina 2x0 França", isCorrect: false },
      ],
      explanation: "Considerada a melhor final da história! Mbappé fez hat-trick mas a Argentina venceu nos pênaltis.",
    },
    {
      id: "q4",
      text: "Quem marcou o primeiro gol da história das Copas (1930)?",
      options: [
        { id: "a", text: "Héctor Castro (Uruguai)", isCorrect: false },
        { id: "b", text: "Lucien Laurent (França)", isCorrect: true },
        { id: "c", text: "Guillermo Stábile (Argentina)", isCorrect: false },
        { id: "d", text: "Bert Patenaude (EUA)", isCorrect: false },
      ],
      explanation: "Lucien Laurent marcou o primeiro gol da história das Copas, aos 19 minutos de França 4x1 México, em 13 de julho de 1930.",
    },
    {
      id: "q5",
      text: "Na Copa de 1970, Pelé marcou quantos gols?",
      options: [
        { id: "a", text: "2", isCorrect: false },
        { id: "b", text: "4", isCorrect: true },
        { id: "c", text: "6", isCorrect: false },
        { id: "d", text: "8", isCorrect: false },
      ],
      explanation: "Pelé marcou 4 gols na Copa de 1970 no México, incluindo o primeiro da final contra a Itália (4x1).",
    },
    {
      id: "q6",
      text: "Qual alemão marcou gol histórico na semifinal contra o Brasil (7x1) em 2014?",
      options: [
        { id: "a", text: "Müller (abriu o placar)", isCorrect: true },
        { id: "b", text: "Klose", isCorrect: false },
        { id: "c", text: "Özil", isCorrect: false },
        { id: "d", text: "Götze", isCorrect: false },
      ],
      explanation: "Thomas Müller abriu o placar aos 11 minutos. A Alemanha fez 5 gols em 18 minutos no primeiro tempo.",
    },
    {
      id: "q7",
      text: "Zidane marcou 2 gols de cabeça na final de 1998. Contra quem?",
      options: [
        { id: "a", text: "Alemanha", isCorrect: false },
        { id: "b", text: "Brasil", isCorrect: true },
        { id: "c", text: "Itália", isCorrect: false },
        { id: "d", text: "Holanda", isCorrect: false },
      ],
      explanation: "Zidane marcou dois gols de cabeça contra o Brasil na final de 1998 (3x0). A França conquistou seu primeiro título mundial.",
    },
    {
      id: "q8",
      text: "Quem fez o gol do título da Alemanha na final da Copa 2014?",
      options: [
        { id: "a", text: "Müller", isCorrect: false },
        { id: "b", text: "Klose", isCorrect: false },
        { id: "c", text: "Mario Götze", isCorrect: true },
        { id: "d", text: "Schweinsteiger", isCorrect: false },
      ],
      explanation: "Götze marcou na prorrogação contra a Argentina, aos 113 minutos!",
    },
    {
      id: "q9",
      text: "Na Copa de 2022, qual foi o gol mais rápido do torneio?",
      options: [
        { id: "a", text: "Gol de Alphonso Davies (Canadá) contra Croácia", isCorrect: true },
        { id: "b", text: "Gol de Gakpo (Holanda) contra Equador", isCorrect: false },
        { id: "c", text: "Gol de Al-Dawsari (Arábia) contra Argentina", isCorrect: false },
        { id: "d", text: "Gol de Richarlison (Brasil) contra Sérvia", isCorrect: false },
      ],
      explanation: "Davies marcou aos 1 minuto e 8 segundos contra a Croácia, o gol mais rápido da Copa 2022.",
    },
    {
      id: "q10",
      text: "Qual foi eleito o gol mais bonito da Copa 2022?",
      options: [
        { id: "a", text: "Messi vs México", isCorrect: false },
        { id: "b", text: "Richarlison vs Sérvia (bicicleta)", isCorrect: true },
        { id: "c", text: "Mbappé vs Polônia", isCorrect: false },
        { id: "d", text: "Enzo vs Croácia", isCorrect: false },
      ],
      explanation: "A bicicleta de Richarlison contra a Sérvia foi eleita pela FIFA como o gol mais bonito da Copa 2022.",
    },
    {
      id: "q11",
      text: "Quem marcou o gol do título da Espanha na Copa 2010?",
      options: [
        { id: "a", text: "David Villa", isCorrect: false },
        { id: "b", text: "Andrés Iniesta", isCorrect: true },
        { id: "c", text: "Xavi", isCorrect: false },
        { id: "d", text: "Fernando Torres", isCorrect: false },
      ],
      explanation: "Iniesta marcou aos 116 minutos da prorrogação contra a Holanda, dando à Espanha seu primeiro título mundial.",
    },
    {
      id: "q12",
      text: "Klose se tornou o maior artilheiro de Copas em qual edição?",
      options: [
        { id: "a", text: "Copa 2006 (Alemanha)", isCorrect: false },
        { id: "b", text: "Copa 2010 (África do Sul)", isCorrect: false },
        { id: "c", text: "Copa 2014 (Brasil)", isCorrect: true },
        { id: "d", text: "Copa 2002 (Japão/Coreia)", isCorrect: false },
      ],
      explanation: "Klose marcou seu 16º gol na Copa 2014 no Brasil, superando Ronaldo Fenômeno (15 gols) como maior artilheiro de Copas.",
    },
    {
      id: "q13",
      text: "Roberto Carlos fez um gol de falta histórico contra a França em 1997. Como foi?",
      options: [
        { id: "a", text: "A bola fez uma curva impossível", isCorrect: true },
        { id: "b", text: "Chute de 40 metros no ângulo", isCorrect: false },
        { id: "c", text: "Cobrança por baixo da barreira", isCorrect: false },
        { id: "d", text: "Falta batida com a perna direita", isCorrect: false },
      ],
      explanation: "A bola desviou tanto que os físicos até hoje estudam aquela curva! Não foi em Copa, mas é icônica.",
    },
    {
      id: "q14",
      text: "Qual jogador marcou o gol mais rápido da história das Copas (11 segundos)?",
      options: [
        { id: "a", text: "Ronaldo", isCorrect: false },
        { id: "b", text: "Hakan Şükür (Turquia)", isCorrect: true },
        { id: "c", text: "Miroslav Klose", isCorrect: false },
        { id: "d", text: "Clint Dempsey (EUA)", isCorrect: false },
      ],
      explanation: "Hakan Şükür marcou aos 11 segundos na disputa de 3º lugar contra Coreia do Sul em 2002.",
    },
    {
      id: "q15",
      text: "Quem fez o gol 'Mão de Deus' na Copa de 1986?",
      options: [
        { id: "a", text: "Pelé", isCorrect: false },
        { id: "b", text: "Zico", isCorrect: false },
        { id: "c", text: "Maradona", isCorrect: true },
        { id: "d", text: "Platini", isCorrect: false },
      ],
      explanation: "Maradona marcou com a mão contra a Inglaterra nas quartas de final de 1986. Ele disse que foi 'a mão de Deus'.",
    },
  ],
};
