import type { Quiz } from "@/lib/types";

export const historiaDoBrasil: Quiz = {
  id: "historia-do-brasil",
  slug: "quiz-historia-do-brasil",
  title: "Quiz História do Brasil",
  description: "Do descobrimento à república — quanto você sabe sobre a história do nosso país?",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🇧🇷",
  color: "#009739",
  tags: ["historia", "brasil", "educacao", "enem", "vestibular"],
  createdAt: "2026-06-09",
  featured: true,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "Governo Federal — Portal da História do Brasil", organization: "Governo Federal do Brasil", accessedAt: "2026-07-12" },
    { label: "Britannica — History of Brazil", organization: "Encyclopædia Britannica", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Do descobrimento à república — reviva os momentos que moldaram o Brasil.",
  questions: [
    {
      id: "q1",
      text: "Em que ano Pedro Álvares Cabral chegou ao Brasil?",
      options: [
        { id: "a", text: "1492", isCorrect: false },
        { id: "b", text: "1500", isCorrect: true },
        { id: "c", text: "1510", isCorrect: false },
        { id: "d", text: "1534", isCorrect: false },
      ],
      explanation: "Cabral chegou ao litoral baiano em 22 de abril de 1500.",
    },
    {
      id: "q2",
      text: "Quem proclamou a Independência do Brasil?",
      options: [
        { id: "a", text: "Dom Pedro II", isCorrect: false },
        { id: "b", text: "José Bonifácio", isCorrect: false },
        { id: "c", text: "Dom Pedro I", isCorrect: true },
        { id: "d", text: "Tiradentes", isCorrect: false },
      ],
      explanation: "Dom Pedro I proclamou a independência em 7 de setembro de 1822, às margens do rio Ipiranga, em São Paulo.",
    },
    {
      id: "q3",
      text: "Em que ano foi abolida a escravidão no Brasil?",
      options: [
        { id: "a", text: "1822", isCorrect: false },
        { id: "b", text: "1850", isCorrect: false },
        { id: "c", text: "1888", isCorrect: true },
        { id: "d", text: "1889", isCorrect: false },
      ],
      explanation: "A Lei Áurea foi assinada pela Princesa Isabel em 13 de maio de 1888, sendo o Brasil o último país das Américas a abolir a escravidão.",
    },
    {
      id: "q4",
      text: "Quem foi o primeiro presidente do Brasil?",
      options: [
        { id: "a", text: "Getúlio Vargas", isCorrect: false },
        { id: "b", text: "Deodoro da Fonseca", isCorrect: true },
        { id: "c", text: "Floriano Peixoto", isCorrect: false },
        { id: "d", text: "Prudente de Morais", isCorrect: false },
      ],
      explanation: "Deodoro da Fonseca proclamou a República em 15 de novembro de 1889 e se tornou o primeiro presidente.",
    },
    {
      id: "q5",
      text: "Qual era o nome do movimento de Tiradentes?",
      options: [
        { id: "a", text: "Revolta dos Farrapos", isCorrect: false },
        { id: "b", text: "Inconfidência Mineira", isCorrect: true },
        { id: "c", text: "Conjuração Baiana", isCorrect: false },
        { id: "d", text: "Guerra dos Canudos", isCorrect: false },
      ],
      explanation: "A Inconfidência Mineira (1789) foi um dos primeiros movimentos pela independência. Tiradentes foi executado em 1792.",
    },
    {
      id: "q6",
      text: "Quem construiu Brasília?",
      options: [
        { id: "a", text: "Getúlio Vargas", isCorrect: false },
        { id: "b", text: "Juscelino Kubitschek", isCorrect: true },
        { id: "c", text: "João Goulart", isCorrect: false },
        { id: "d", text: "Tancredo Neves", isCorrect: false },
      ],
      explanation: "JK inaugurou Brasília em 21 de abril de 1960 com o projeto urbanístico de Lúcio Costa e arquitetura de Oscar Niemeyer.",
    },
    {
      id: "q7",
      text: "Quanto tempo durou a ditadura militar no Brasil?",
      options: [
        { id: "a", text: "10 anos (1964-1974)", isCorrect: false },
        { id: "b", text: "15 anos (1964-1979)", isCorrect: false },
        { id: "c", text: "21 anos (1964-1985)", isCorrect: true },
        { id: "d", text: "25 anos (1964-1989)", isCorrect: false },
      ],
      explanation: "A ditadura militar durou 21 anos e teve 5 presidentes militares, do AI-1 ao processo de redemocratização.",
    },
    {
      id: "q8",
      text: "Qual foi a principal riqueza do Brasil colônia no século XVIII?",
      options: [
        { id: "a", text: "Café", isCorrect: false },
        { id: "b", text: "Cana-de-açúcar", isCorrect: false },
        { id: "c", text: "Ouro", isCorrect: true },
        { id: "d", text: "Borracha", isCorrect: false },
      ],
      explanation: "O Ciclo do Ouro (século XVIII) transformou Minas Gerais no centro econômico da colônia.",
    },
    {
      id: "q9",
      text: "Quem assinou a Lei Áurea?",
      options: [
        { id: "a", text: "Dom Pedro II", isCorrect: false },
        { id: "b", text: "Princesa Isabel", isCorrect: true },
        { id: "c", text: "José do Patrocínio", isCorrect: false },
        { id: "d", text: "Joaquim Nabuco", isCorrect: false },
      ],
      explanation: "A Princesa Isabel assinou a Lei Áurea em 13 de maio de 1888 enquanto atuava como regente do Império.",
    },
    {
      id: "q10",
      text: "O que foi o 'Grito do Ipiranga'?",
      options: [
        { id: "a", text: "A abolição da escravidão", isCorrect: false },
        { id: "b", text: "A proclamação da República", isCorrect: false },
        { id: "c", text: "A declaração de Independência", isCorrect: true },
        { id: "d", text: "O início da ditadura", isCorrect: false },
      ],
      explanation: "O Grito do Ipiranga, em 7 de setembro de 1822, marca a declaração de independência do Brasil por Dom Pedro I.",
    },
    {
      id: "q11",
      text: "Em que ano o Brasil se tornou República?",
      options: [
        { id: "a", text: "1822", isCorrect: false },
        { id: "b", text: "1888", isCorrect: false },
        { id: "c", text: "1889", isCorrect: true },
        { id: "d", text: "1891", isCorrect: false },
      ],
      explanation: "A República foi proclamada em 15 de novembro de 1889 pelo Marechal Deodoro da Fonseca.",
    },
    {
      id: "q12",
      text: "Qual presidente ficou conhecido como 'Pai dos Pobres'?",
      options: [
        { id: "a", text: "Juscelino Kubitschek", isCorrect: false },
        { id: "b", text: "Getúlio Vargas", isCorrect: true },
        { id: "c", text: "Lula", isCorrect: false },
        { id: "d", text: "João Goulart", isCorrect: false },
      ],
      explanation: "Getúlio Vargas governou o Brasil em dois períodos (1930-1945 e 1951-1954) e criou a CLT e a Petrobras.",
    },
    {
      id: "q13",
      text: "Que país colonizou o Brasil?",
      options: [
        { id: "a", text: "Espanha", isCorrect: false },
        { id: "b", text: "França", isCorrect: false },
        { id: "c", text: "Portugal", isCorrect: true },
        { id: "d", text: "Holanda", isCorrect: false },
      ],
      explanation: "Portugal colonizou o Brasil de 1500 a 1822, quando Dom Pedro I declarou a independência.",
    },
    {
      id: "q14",
      text: "A primeira capital do Brasil foi:",
      options: [
        { id: "a", text: "Rio de Janeiro", isCorrect: false },
        { id: "b", text: "Salvador", isCorrect: true },
        { id: "c", text: "São Paulo", isCorrect: false },
        { id: "d", text: "Recife", isCorrect: false },
      ],
      explanation: "Salvador foi a primeira capital (1549-1763), seguida pelo Rio de Janeiro (1763-1960) e depois Brasília.",
    },
    {
      id: "q15",
      text: "Qual movimento pediu eleições diretas em 1984?",
      options: [
        { id: "a", text: "Semana de Arte Moderna", isCorrect: false },
        { id: "b", text: "Tropicália", isCorrect: false },
        { id: "c", text: "Diretas Já", isCorrect: true },
        { id: "d", text: "Caras-Pintadas", isCorrect: false },
      ],
      explanation: "Diretas Já foi o maior movimento cívico da história do Brasil, com comícios de até 1,5 milhão de pessoas.",
    },
  ],
};
