import type { Quiz } from "@/lib/types";

export const mitologiaGrega: Quiz = {
  id: "mitologia-grega",
  slug: "quiz-mitologia-grega",
  title: "Quiz Mitologia Grega",
  description: "De Zeus a Hércules — quanto você sabe sobre os deuses do Olimpo?",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "⚡",
  color: "#D97706",
  tags: ["mitologia", "grecia", "deuses", "educacao", "historia"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Patrick Bastos",
  authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
  sources: [
    { label: "Theoi Greek Mythology — Encyclopaedia", url: "https://www.theoi.com/", organization: "Theoi Project", accessedAt: "2026-07-12" },
    { label: "Britannica — Greek Mythology", organization: "Encyclopædia Britannica", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Deuses do Olimpo, heróis mortais, criaturas impossíveis e guerras épicas — a mitologia grega é rica em histórias e este quiz cobre as principais.",
  questions: [
    {
      id: "q1",
      text: "Quem é o rei dos deuses na mitologia grega?",
      options: [
        { id: "a", text: "Poseidon", isCorrect: false },
        { id: "b", text: "Zeus", isCorrect: true },
        { id: "c", text: "Hades", isCorrect: false },
        { id: "d", text: "Ares", isCorrect: false },
      ],
      explanation: "Zeus era o deus do trovão e governava os deuses do Monte Olimpo. Seus irmãos Poseidon e Hades governavam os mares e o submundo.",
    },
    {
      id: "q2",
      text: "Qual deus governa os mares?",
      options: [
        { id: "a", text: "Hermes", isCorrect: false },
        { id: "b", text: "Apolo", isCorrect: false },
        { id: "c", text: "Poseidon", isCorrect: true },
        { id: "d", text: "Dionísio", isCorrect: false },
      ],
      explanation: "Poseidon era irmão de Zeus e Hades. Além dos mares, era o deus dos terremotos e dos cavalos.",
    },
    {
      id: "q3",
      text: "Quem é a deusa do amor e da beleza?",
      options: [
        { id: "a", text: "Atena", isCorrect: false },
        { id: "b", text: "Afrodite", isCorrect: true },
        { id: "c", text: "Ártemis", isCorrect: false },
        { id: "d", text: "Hera", isCorrect: false },
      ],
      explanation: "Afrodite nasceu da espuma do mar, segundo a Teogonia de Hesíodo. Seu equivalente romano é Vênus.",
    },
    {
      id: "q4",
      text: "Qual herói matou a Medusa?",
      options: [
        { id: "a", text: "Hércules", isCorrect: false },
        { id: "b", text: "Perseu", isCorrect: true },
        { id: "c", text: "Teseu", isCorrect: false },
        { id: "d", text: "Aquiles", isCorrect: false },
      ],
      explanation: "Perseu cortou a cabeça da Medusa usando um escudo espelhado pra não olhar diretamente pra ela!",
    },
    {
      id: "q5",
      text: "Qual é o ponto fraco de Aquiles?",
      options: [
        { id: "a", text: "O coração", isCorrect: false },
        { id: "b", text: "O calcanhar", isCorrect: true },
        { id: "c", text: "Os olhos", isCorrect: false },
        { id: "d", text: "A mão direita", isCorrect: false },
      ],
      explanation: "Aquiles foi mergulhado no rio Estige por sua mãe Tétis, que o segurou pelo calcanhar — o único ponto vulnerável.",
    },
    {
      id: "q6",
      text: "Quem ficou preso num labirinto com o Minotauro?",
      options: [
        { id: "a", text: "Perseu", isCorrect: false },
        { id: "b", text: "Teseu", isCorrect: true },
        { id: "c", text: "Odisseu (Ulisses)", isCorrect: false },
        { id: "d", text: "Jasão", isCorrect: false },
      ],
      explanation: "Teseu entrou no labirinto de Creta, matou o Minotauro e saiu usando o fio de Ariadne!",
    },
    {
      id: "q7",
      text: "Quem foi condenado a empurrar uma pedra montanha acima eternamente?",
      options: [
        { id: "a", text: "Prometeu", isCorrect: false },
        { id: "b", text: "Sísifo", isCorrect: true },
        { id: "c", text: "Tântalo", isCorrect: false },
        { id: "d", text: "Atlas", isCorrect: false },
      ],
      explanation: "Sísifo foi punido por enganar a morte duas vezes. Sua pedra sempre rolava de volta antes de chegar ao topo.",
    },
    {
      id: "q8",
      text: "Quem roubou o fogo dos deuses e deu aos humanos?",
      options: [
        { id: "a", text: "Hefesto", isCorrect: false },
        { id: "b", text: "Prometeu", isCorrect: true },
        { id: "c", text: "Hermes", isCorrect: false },
        { id: "d", text: "Dionísio", isCorrect: false },
      ],
      explanation: "Como castigo, Zeus acorrentou Prometeu a uma rocha onde uma águia comia seu fígado todos os dias — que se regenerava!",
    },
    {
      id: "q9",
      text: "O que havia dentro da caixa de Pandora?",
      options: [
        { id: "a", text: "Ouro e joias", isCorrect: false },
        { id: "b", text: "Todos os males do mundo", isCorrect: true },
        { id: "c", text: "Poderes divinos", isCorrect: false },
        { id: "d", text: "Almas dos mortos", isCorrect: false },
      ],
      explanation: "Quando Pandora abriu a caixa, todos os males escaparam. Só a esperança ficou dentro!",
    },
    {
      id: "q10",
      text: "Qual deus governa o mundo dos mortos?",
      options: [
        { id: "a", text: "Ares", isCorrect: false },
        { id: "b", text: "Hades", isCorrect: true },
        { id: "c", text: "Tânatos", isCorrect: false },
        { id: "d", text: "Cronos", isCorrect: false },
      ],
      explanation: "Hades não era considerado um deus malvado, mas era temido. Tânatos era a personificação da morte em si.",
    },
    {
      id: "q11",
      text: "Quem construiu o famoso Cavalo de Troia?",
      options: [
        { id: "a", text: "Aquiles", isCorrect: false },
        { id: "b", text: "Odisseu (Ulisses)", isCorrect: true },
        { id: "c", text: "Ájax", isCorrect: false },
        { id: "d", text: "Agamêmnon", isCorrect: false },
      ],
      explanation: "Odisseu (Ulisses) planejou o estratagema do Cavalo de Troia para encerrar a guerra de 10 anos contra Troia.",
    },
    {
      id: "q12",
      text: "Quantos trabalhos Hércules teve que completar?",
      options: [
        { id: "a", text: "7", isCorrect: false },
        { id: "b", text: "10", isCorrect: false },
        { id: "c", text: "12", isCorrect: true },
        { id: "d", text: "15", isCorrect: false },
      ],
      explanation: "Os 12 Trabalhos de Hércules foram impostos como penitência por Euristeu, rei de Micenas, a mando de Hera.",
    },
    {
      id: "q13",
      text: "Quem é a deusa da sabedoria e da guerra estratégica?",
      options: [
        { id: "a", text: "Hera", isCorrect: false },
        { id: "b", text: "Atena", isCorrect: true },
        { id: "c", text: "Ártemis", isCorrect: false },
        { id: "d", text: "Deméter", isCorrect: false },
      ],
      explanation: "Atena nasceu diretamente da cabeça de Zeus, já adulta e com armadura completa.",
    },
    {
      id: "q14",
      text: "Qual criatura tem corpo de leão e cabeça humana e faz enigmas?",
      options: [
        { id: "a", text: "Minotauro", isCorrect: false },
        { id: "b", text: "Esfinge", isCorrect: true },
        { id: "c", text: "Centauro", isCorrect: false },
        { id: "d", text: "Hidra", isCorrect: false },
      ],
      explanation: "A Esfinge ficava na entrada de Tebas e devorava quem não resolvia seu enigma. Édipo foi o único que acertou.",
    },
    {
      id: "q15",
      text: "Quem olhava pra Medusa se transformava em:",
      options: [
        { id: "a", text: "Ouro", isCorrect: false },
        { id: "b", text: "Pedra", isCorrect: true },
        { id: "c", text: "Cobra", isCorrect: false },
        { id: "d", text: "Cinzas", isCorrect: false },
      ],
      explanation: "A Medusa era uma das três Górgonas. Originalmente era uma bela mortal, transformada em monstro por Atena.",
    },
  ],
};
