import type { Quiz } from "@/lib/types";

export const mundoAnimal: Quiz = {
  id: "mundo-animal",
  slug: "quiz-mundo-animal",
  title: "Quiz Mundo Animal",
  description: "Quanto você sabe sobre o reino animal? 15 perguntas que vão testar seu conhecimento!",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🦁",
  color: "#16A34A",
  tags: ["animais", "natureza", "conhecimentos-gerais", "biologia"],
  createdAt: "2026-06-08",
  featured: false,
  author: "Patrick Bastos",
  authorBio: "Diretor executivo, autor e empreendedor digital, Patrick Bastos atua na criação de projetos que unem conteúdo, tecnologia e experiência do usuário. No MegaQuiz, é responsável pela direção editorial e revisão dos conteúdos.",
  sources: [
    { label: "IUCN Red List — Leontopithecus rosalia", url: "https://www.iucnredlist.org/species/11506/17935340", organization: "IUCN", accessedAt: "2026-07-12" },
    { label: "National Geographic — Animals", organization: "National Geographic", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Velocidade, camuflagem, veneno, migração — o reino animal está cheio de fatos surpreendentes. Veja quantos deles você já conhece.",
  questions: [
    {
      id: "q1",
      text: "Qual é o animal mais rápido do mundo?",
      options: [
        { id: "a", text: "Leopardo", isCorrect: false },
        { id: "b", text: "Guepardo (Cheetah)", isCorrect: true },
        { id: "c", text: "Falcão-peregrino", isCorrect: false },
        { id: "d", text: "Lebre", isCorrect: false },
      ],
      explanation: "O guepardo atinge até 120 km/h em corridas curtas. O falcão-peregrino é mais rápido em mergulho (390 km/h), mas em corrida o guepardo vence.",
    },
    {
      id: "q2",
      text: "Quantos corações tem um polvo?",
      options: [
        { id: "a", text: "1", isCorrect: false },
        { id: "b", text: "2", isCorrect: false },
        { id: "c", text: "3", isCorrect: true },
        { id: "d", text: "5", isCorrect: false },
      ],
      explanation: "O polvo tem 3 corações: dois bombeiam sangue para as brânquias e um para o resto do corpo.",
    },
    {
      id: "q3",
      text: "Qual animal tem a gestação mais longa?",
      options: [
        { id: "a", text: "Baleia-azul", isCorrect: false },
        { id: "b", text: "Rinoceronte", isCorrect: false },
        { id: "c", text: "Elefante", isCorrect: true },
        { id: "d", text: "Girafa", isCorrect: false },
      ],
      explanation: "A gestação do elefante dura cerca de 22 meses, a mais longa entre os mamíferos terrestres.",
    },
    {
      id: "q4",
      text: "Qual destes animais é venenoso (e não peçonhento)?",
      options: [
        { id: "a", text: "Cobra coral", isCorrect: false },
        { id: "b", text: "Aranha viúva-negra", isCorrect: false },
        { id: "c", text: "Sapo-flecha (dendrobates)", isCorrect: true },
        { id: "d", text: "Escorpião", isCorrect: false },
      ],
      explanation: "Venenoso = você morre se comer/tocar. Peçonhento = ele injeta o veneno. O sapo-flecha é venenoso ao toque.",
    },
    {
      id: "q5",
      text: "Qual o maior animal que já existiu na Terra?",
      options: [
        { id: "a", text: "Tiranossauro Rex", isCorrect: false },
        { id: "b", text: "Baleia-azul", isCorrect: true },
        { id: "c", text: "Megalodon", isCorrect: false },
        { id: "d", text: "Argentinosaurus", isCorrect: false },
      ],
      explanation: "A baleia-azul é o maior animal que já existiu, chegando a 30 metros e 180 toneladas — maior que qualquer dinossauro!",
    },
    {
      id: "q6",
      text: "Qual animal dorme até 22 horas por dia?",
      options: [
        { id: "a", text: "Gato", isCorrect: false },
        { id: "b", text: "Preguiça", isCorrect: false },
        { id: "c", text: "Coala", isCorrect: true },
        { id: "d", text: "Tartaruga", isCorrect: false },
      ],
      explanation: "Coalas dormem até 22 horas porque sua dieta de eucalipto tem pouquíssima energia. A preguiça dorme 'só' 15-20 horas.",
    },
    {
      id: "q7",
      text: "Qual o único mamífero que voa de verdade?",
      options: [
        { id: "a", text: "Esquilo voador", isCorrect: false },
        { id: "b", text: "Morcego", isCorrect: true },
        { id: "c", text: "Colugos", isCorrect: false },
        { id: "d", text: "Ornitorrinco", isCorrect: false },
      ],
      explanation: "O morcego é o único mamífero com voo verdadeiro. Esquilos voadores apenas planam.",
    },
    {
      id: "q8",
      text: "Quantas patas tem uma aranha?",
      options: [
        { id: "a", text: "6", isCorrect: false },
        { id: "b", text: "8", isCorrect: true },
        { id: "c", text: "10", isCorrect: false },
        { id: "d", text: "12", isCorrect: false },
      ],
      explanation: "Aranhas são aracnídeos e têm 8 patas. Insetos têm 6 patas.",
    },
    {
      id: "q9",
      text: "Qual animal produz o som mais alto do planeta?",
      options: [
        { id: "a", text: "Leão", isCorrect: false },
        { id: "b", text: "Elefante", isCorrect: false },
        { id: "c", text: "Baleia-azul", isCorrect: true },
        { id: "d", text: "Bugio", isCorrect: false },
      ],
      explanation: "O chamado da baleia-azul chega a 188 decibéis, mais alto que um motor de jato (140dB)!",
    },
    {
      id: "q10",
      text: "Qual ave não consegue voar?",
      options: [
        { id: "a", text: "Avestruz", isCorrect: true },
        { id: "b", text: "Condor", isCorrect: false },
        { id: "c", text: "Pelicano", isCorrect: false },
        { id: "d", text: "Albatroz", isCorrect: false },
      ],
      explanation: "O avestruz é a maior ave do mundo e não voa, mas compensa correndo a até 70 km/h!",
    },
    {
      id: "q11",
      text: "Qual animal brasileiro está ameaçado de extinção?",
      options: [
        { id: "a", text: "Capivara", isCorrect: false },
        { id: "b", text: "Mico-leão-dourado", isCorrect: true },
        { id: "c", text: "Tucano", isCorrect: false },
        { id: "d", text: "Jacaré-do-pantanal", isCorrect: false },
      ],
      explanation: "O mico-leão-dourado (Leontopithecus rosalia) é classificado como 'Em Perigo' (Endangered) pela Lista Vermelha da IUCN. A espécie vive na Mata Atlântica do Rio de Janeiro e é símbolo da conservação no Brasil.",
    },
    {
      id: "q12",
      text: "Qual animal muda de cor para se camuflar?",
      options: [
        { id: "a", text: "Iguana", isCorrect: false },
        { id: "b", text: "Salamandra", isCorrect: false },
        { id: "c", text: "Camaleão", isCorrect: true },
        { id: "d", text: "Lagarto-monitor", isCorrect: false },
      ],
      explanation: "O camaleão muda de cor controlando cristais em sua pele. Mas curioso: eles mudam mais por humor e temperatura do que camuflagem!",
    },
    {
      id: "q13",
      text: "Qual destes animais é um mamífero que bota ovo?",
      options: [
        { id: "a", text: "Pangolim", isCorrect: false },
        { id: "b", text: "Tatu", isCorrect: false },
        { id: "c", text: "Ornitorrinco", isCorrect: true },
        { id: "d", text: "Castor", isCorrect: false },
      ],
      explanation: "O ornitorrinco é um dos poucos mamíferos monotremados — bota ovos, tem bico e é venenoso!",
    },
    {
      id: "q14",
      text: "Qual animal tem a mordida mais forte do mundo?",
      options: [
        { id: "a", text: "Tubarão-branco", isCorrect: false },
        { id: "b", text: "Leão", isCorrect: false },
        { id: "c", text: "Hipopótamo", isCorrect: false },
        { id: "d", text: "Crocodilo-de-água-salgada", isCorrect: true },
      ],
      explanation: "O crocodilo-de-água-salgada tem a mordida mais poderosa já medida: 3.700 PSI!",
    },
    {
      id: "q15",
      text: "Quantas espécies de formigas existem aproximadamente?",
      options: [
        { id: "a", text: "Cerca de 500", isCorrect: false },
        { id: "b", text: "Cerca de 5.000", isCorrect: false },
        { id: "c", text: "Mais de 20.000", isCorrect: true },
        { id: "d", text: "Cerca de 2.000", isCorrect: false },
      ],
      explanation: "Existem mais de 20.000 espécies conhecidas de formigas! E estima-se que existam mais não descobertas.",
    },
  ],
};
