import type { Quiz } from "@/lib/types";

export const musicaBrasileira: Quiz = {
  id: "musica-brasileira",
  slug: "quiz-musica-brasileira",
  title: "Quiz Música Brasileira",
  description: "Do sertanejo ao funk, do axé ao rap — quanto você manja de música BR?",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "🎵",
  color: "#EC4899",
  tags: ["musica", "brasil", "sertanejo", "funk", "conhecimentos-gerais"],
  createdAt: "2026-06-08",
  featured: true,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "Dicionário Cravo Albin da Música Popular Brasileira", url: "https://dicionariompb.com.br/", organization: "Instituto Cultural Cravo Albin", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Do sertanejo ao funk, do axé ao rap — prove que você conhece a música brasileira.",
  questions: [
    {
      id: "q1",
      text: "Qual dupla sertaneja gravou 'Evidências'?",
      options: [
        { id: "a", text: "Zezé Di Camargo e Luciano", isCorrect: true },
        { id: "b", text: "Chitãozinho e Xororó", isCorrect: false },
        { id: "c", text: "Leandro e Leonardo", isCorrect: false },
        { id: "d", text: "Bruno e Marrone", isCorrect: false },
      ],
      explanation: "Evidências (1990) de Zezé Di Camargo e Luciano é considerada uma das maiores músicas sertanejas de todos os tempos.",
    },
    {
      id: "q2",
      text: "Quem é conhecido como 'Rei do Baile Funk'?",
      options: [
        { id: "a", text: "MC Kevinho", isCorrect: false },
        { id: "b", text: "Mr. Catra", isCorrect: true },
        { id: "c", text: "MC Guimê", isCorrect: false },
        { id: "d", text: "Kondzilla", isCorrect: false },
      ],
      explanation: "Mr. Catra (Wagner Domingues, 1968-2018) foi um dos pioneiros e maiores nomes do funk carioca.",
    },
    {
      id: "q3",
      text: "Qual banda baiana criou o 'Axé Music'?",
      options: [
        { id: "a", text: "Olodum", isCorrect: false },
        { id: "b", text: "Chiclete com Banana", isCorrect: false },
        { id: "c", text: "Ara Ketu", isCorrect: false },
        { id: "d", text: "Todas ajudaram, mas o termo veio do jornalismo", isCorrect: true },
      ],
      explanation: "O termo 'Axé Music' foi criado pelo jornalista Hagamenon Brito em 1987, de forma pejorativa, mas virou gênero!",
    },
    {
      id: "q4",
      text: "Qual rapper brasileiro lançou o álbum 'Sobrevivendo no Inferno'?",
      options: [
        { id: "a", text: "Sabotage", isCorrect: false },
        { id: "b", text: "Racionais MC's", isCorrect: true },
        { id: "c", text: "MV Bill", isCorrect: false },
        { id: "d", text: "Emicida", isCorrect: false },
      ],
      explanation: "Sobrevivendo no Inferno (1997) dos Racionais MC's vendeu mais de 1,5 milhão de cópias e virou patrimônio cultural.",
    },
    {
      id: "q5",
      text: "Qual cantor é conhecido como 'Rei do Sertanejo Universitário'?",
      options: [
        { id: "a", text: "Gusttavo Lima", isCorrect: false },
        { id: "b", text: "Luan Santana", isCorrect: true },
        { id: "c", text: "Michel Teló", isCorrect: false },
        { id: "d", text: "Jorge e Mateus", isCorrect: false },
      ],
      explanation: "Luan Santana estourou em 2009 com 'Meteoro' e é considerado um dos pioneiros do sertanejo universitário.",
    },
    {
      id: "q6",
      text: "Qual música brasileira tem mais views no YouTube (até 2026)?",
      options: [
        { id: "a", text: "Ai Se Eu Te Pego - Michel Teló", isCorrect: true },
        { id: "b", text: "Envolver - Anitta", isCorrect: false },
        { id: "c", text: "Bum Bum Tam Tam - MC Fioti", isCorrect: false },
        { id: "d", text: "Sua Cara - Major Lazer ft Anitta", isCorrect: false },
      ],
      explanation: "Ai Se Eu Te Pego ultrapassou 3 bilhões de views e foi um fenômeno mundial em 2011-2012!",
    },
    {
      id: "q7",
      text: "Quem cantou 'Tente Outra Vez' e 'Maluco Beleza'?",
      options: [
        { id: "a", text: "Cazuza", isCorrect: false },
        { id: "b", text: "Raul Seixas", isCorrect: true },
        { id: "c", text: "Renato Russo", isCorrect: false },
        { id: "d", text: "Belchior", isCorrect: false },
      ],
      explanation: "Raul Seixas, o 'Pai do Rock Brasileiro', gravou esses clássicos nos anos 70.",
    },
    {
      id: "q8",
      text: "Qual gênero musical nasceu no Recife nos anos 90?",
      options: [
        { id: "a", text: "Brega funk", isCorrect: false },
        { id: "b", text: "Manguebeat", isCorrect: true },
        { id: "c", text: "Tecnobrega", isCorrect: false },
        { id: "d", text: "Forró eletrônico", isCorrect: false },
      ],
      explanation: "O Manguebeat misturou ritmos regionais com rock e eletrônica. Chico Science e Nação Zumbi foram os criadores.",
    },
    {
      id: "q9",
      text: "Qual cantora gospel brasileira é a mais ouvida no Spotify?",
      options: [
        { id: "a", text: "Aline Barros", isCorrect: false },
        { id: "b", text: "Ana Vilela", isCorrect: false },
        { id: "c", text: "Gabriela Rocha", isCorrect: true },
        { id: "d", text: "Fernandinho", isCorrect: false },
      ],
      explanation: "Gabriela Rocha se tornou uma das artistas gospel mais ouvidas com hits como 'Não Temas' e 'Eu Navegarei'.",
    },
    {
      id: "q10",
      text: "Que estilo musical gaúcho usa gaita e violão?",
      options: [
        { id: "a", text: "Vanerinha", isCorrect: false },
        { id: "b", text: "Música nativista", isCorrect: true },
        { id: "c", text: "Milonga", isCorrect: false },
        { id: "d", text: "Chamamé", isCorrect: false },
      ],
      explanation: "A música nativista gaúcha valoriza a cultura do Rio Grande do Sul com gaita-ponto, violão e letras sobre a vida no campo.",
    },
    {
      id: "q11",
      text: "Quem gravou 'Macarena Brasileira' - a versão 'Dança da Manivela'?",
      options: [
        { id: "a", text: "Latino", isCorrect: true },
        { id: "b", text: "Bonde do Rolê", isCorrect: false },
        { id: "c", text: "Claudinho e Buchecha", isCorrect: false },
        { id: "d", text: "Rouge", isCorrect: false },
      ],
      explanation: "Latino ficou famoso nos anos 2000 com versões brasileiras de hits internacionais e músicas dançantes.",
    },
    {
      id: "q12",
      text: "Qual é o festival de música mais famoso do Brasil?",
      options: [
        { id: "a", text: "Lollapalooza Brasil", isCorrect: false },
        { id: "b", text: "Rock in Rio", isCorrect: true },
        { id: "c", text: "Festa do Peão de Barretos", isCorrect: false },
        { id: "d", text: "Villa Mix", isCorrect: false },
      ],
      explanation: "Rock in Rio começou em 1985 no Rio de Janeiro e se tornou um dos maiores festivais do mundo.",
    },
    {
      id: "q13",
      text: "Marília Mendonça era conhecida como...",
      options: [
        { id: "a", text: "Rainha do Sertanejo", isCorrect: false },
        { id: "b", text: "Rainha da Sofrência", isCorrect: true },
        { id: "c", text: "Diva Sertaneja", isCorrect: false },
        { id: "d", text: "Princesa do Sertão", isCorrect: false },
      ],
      explanation: "Marília Mendonça (1995-2021) revolucionou o sertanejo feminino e é a artista brasileira mais ouvida da história do Spotify.",
    },
    {
      id: "q14",
      text: "Qual cidade é considerada o berço do samba?",
      options: [
        { id: "a", text: "Salvador", isCorrect: false },
        { id: "b", text: "São Paulo", isCorrect: false },
        { id: "c", text: "Rio de Janeiro", isCorrect: true },
        { id: "d", text: "Recife", isCorrect: false },
      ],
      explanation: "O samba como gênero se consolidou no Rio de Janeiro, especialmente na região da Praça Onze e no Morro da Mangueira.",
    },
    {
      id: "q15",
      text: "Qual artista brasileiro tem mais ouvintes mensais no Spotify (2026)?",
      options: [
        { id: "a", text: "Anitta", isCorrect: true },
        { id: "b", text: "Ludmilla", isCorrect: false },
        { id: "c", text: "Henrique e Juliano", isCorrect: false },
        { id: "d", text: "Alok", isCorrect: false },
      ],
      explanation: "Anitta se consolidou como a artista brasileira de maior alcance global no streaming.",
    },
  ],
};
