import type { Quiz } from "@/lib/types";

export const round6Sobreviveria: Quiz = {
  id: "round6-sobreviveria",
  slug: "quiz-round-6-voce-sobreviveria",
  title: "Quanto Você Sabe Sobre Round 6 (Squid Game)?",
  description: "15 perguntas sobre a série que virou fenômeno mundial na Netflix.",
  type: "trivia",
  category: "series-filmes",
  emoji: "🦑",
  color: "#DC2626",
  tags: ["round 6", "squid game", "netflix", "series", "survival"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "Netflix — Squid Game", organization: "Netflix", accessedAt: "2026-07-12" },
    { label: "IMDb — Squid Game", url: "https://www.imdb.com/title/tt10919420/", organization: "IMDb", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "De Batatinha Fatatinha ao jogo final — o quanto você prestou atenção na série?",
  questions: [
    {
      id: "q1",
      text: "Qual é o primeiro jogo de Round 6?",
      options: [
        { id: "a", text: "Cabo de guerra", isCorrect: false },
        { id: "b", text: "Batatinha frita 1, 2, 3", isCorrect: true },
        { id: "c", text: "Jogo de bolinhas de gude", isCorrect: false },
        { id: "d", text: "Jogo da lula", isCorrect: false },
      ],
      explanation: "Batatinha frita 1, 2, 3 (Red Light, Green Light) é o primeiro e mais icônico jogo da série.",
    },
    {
      id: "q2",
      text: "Qual é o prêmio total dos jogos?",
      options: [
        { id: "a", text: "10 bilhões de wons", isCorrect: false },
        { id: "b", text: "45,6 bilhões de wons", isCorrect: true },
        { id: "c", text: "100 bilhões de wons", isCorrect: false },
        { id: "d", text: "25 bilhões de wons", isCorrect: false },
      ],
      explanation: "45,6 bilhões de wons equivalem a aproximadamente R$ 180 milhões!",
    },
    {
      id: "q3",
      text: "Qual é o número do protagonista Seong Gi-hun?",
      options: [
        { id: "a", text: "001", isCorrect: false },
        { id: "b", text: "067", isCorrect: false },
        { id: "c", text: "456", isCorrect: true },
        { id: "d", text: "218", isCorrect: false },
      ],
      explanation: "456 é o último número de inscrição, indicando que Gi-hun foi o último a entrar nos jogos.",
    },
    {
      id: "q4",
      text: "No jogo do biscoito (dalgona), qual forma é a mais difícil?",
      options: [
        { id: "a", text: "Círculo", isCorrect: false },
        { id: "b", text: "Triângulo", isCorrect: false },
        { id: "c", text: "Estrela", isCorrect: false },
        { id: "d", text: "Guarda-chuva (sombrinha)", isCorrect: true },
      ],
      explanation: "O guarda-chuva tem muitos detalhes finos e é quase impossível de recortar sem quebrar!",
    },
    {
      id: "q5",
      text: "Quem é o jogador 001?",
      options: [
        { id: "a", text: "Um apostador falido", isCorrect: false },
        { id: "b", text: "Um velho com tumor cerebral (e criador dos jogos)", isCorrect: true },
        { id: "c", text: "Um ex-policial infiltrado", isCorrect: false },
        { id: "d", text: "Um empresário disfarçado", isCorrect: false },
      ],
      explanation: "O jogador 001, Oh Il-nam, é revelado no final como o criador dos jogos — um dos maiores plot twists da série.",
    },
    {
      id: "q6",
      text: "Quantos jogadores iniciam os jogos na temporada 1?",
      options: [
        { id: "a", text: "200", isCorrect: false },
        { id: "b", text: "356", isCorrect: false },
        { id: "c", text: "456", isCorrect: true },
        { id: "d", text: "500", isCorrect: false },
      ],
      explanation: "456 jogadores começam os jogos na temporada 1, e cada eliminação adiciona 100 milhões de wons ao prêmio.",
    },
    {
      id: "q7",
      text: "No jogo da ponte de vidro, quantas etapas os jogadores precisam pular?",
      options: [
        { id: "a", text: "10 pares", isCorrect: false },
        { id: "b", text: "16 pares", isCorrect: false },
        { id: "c", text: "18 pares", isCorrect: true },
        { id: "d", text: "20 pares", isCorrect: false },
      ],
      explanation: "Os jogadores devem escolher entre vidro temperado e vidro comum em 18 pares de painéis sobre um abismo.",
    },
    {
      id: "q8",
      text: "Qual é a cor dos uniformes dos guardas?",
      options: [
        { id: "a", text: "Preto", isCorrect: false },
        { id: "b", text: "Rosa/Vermelho", isCorrect: true },
        { id: "c", text: "Branco", isCorrect: false },
        { id: "d", text: "Azul", isCorrect: false },
      ],
      explanation: "Os guardas usam macacão rosa/vermelho com máscaras pretas. Os jogadores vestem verde-água.",
    },
    {
      id: "q9",
      text: "O que os símbolos nas máscaras dos guardas representam?",
      options: [
        { id: "a", text: "Força, velocidade e inteligência", isCorrect: false },
        { id: "b", text: "Círculo (trabalhador), Triângulo (soldado), Quadrado (gerente)", isCorrect: true },
        { id: "c", text: "Terra, água e fogo", isCorrect: false },
        { id: "d", text: "São apenas decoração", isCorrect: false },
      ],
      explanation: "Círculo = trabalhadores (nível mais baixo), triângulo = soldados armados, quadrado = gerentes que supervisionam.",
    },
    {
      id: "q10",
      text: "Na segunda temporada, o que Gi-hun tenta fazer?",
      options: [
        { id: "a", text: "Fugir do país", isCorrect: false },
        { id: "b", text: "Voltar aos jogos para derrubá-los por dentro", isCorrect: true },
        { id: "c", text: "Criar seus próprios jogos", isCorrect: false },
        { id: "d", text: "Esquecer tudo e seguir em frente", isCorrect: false },
      ],
      explanation: "Na temporada 2, Gi-hun retorna aos jogos com o objetivo de acabar com eles por dentro e salvar os participantes.",
    },
    {
      id: "q11",
      text: "Qual jogo envolve formar duplas e apostar tudo?",
      options: [
        { id: "a", text: "Cabo de guerra", isCorrect: false },
        { id: "b", text: "Bolinhas de gude", isCorrect: true },
        { id: "c", text: "Jogo da lula", isCorrect: false },
        { id: "d", text: "Luz vermelha, luz verde", isCorrect: false },
      ],
      explanation: "O jogo de bolinhas de gude é o mais emocionalmente devastador — você joga contra seu parceiro!",
    },
    {
      id: "q12",
      text: "Qual é a profissão do jogador 218 (Cho Sang-woo)?",
      options: [
        { id: "a", text: "Médico", isCorrect: false },
        { id: "b", text: "Formado em negócios (ex-analista financeiro)", isCorrect: true },
        { id: "c", text: "Professor", isCorrect: false },
        { id: "d", text: "Policial", isCorrect: false },
      ],
      explanation: "Cho Sang-woo se formou na Universidade Nacional de Seoul e era analista financeiro, mas acumulou dívidas com apostas ilegais.",
    },
    {
      id: "q13",
      text: "O que acontece se a maioria dos jogadores votar para sair?",
      options: [
        { id: "a", text: "Todos morrem", isCorrect: false },
        { id: "b", text: "Os jogos continuam de qualquer forma", isCorrect: false },
        { id: "c", text: "Todos são libertados sem o prêmio", isCorrect: true },
        { id: "d", text: "Só metade sai", isCorrect: false },
      ],
      explanation: "Na regra democrática dos jogos, se a maioria votar para encerrar, todos são libertados — mas podem ser convidados a voltar.",
    },
    {
      id: "q14",
      text: "Qual país produziu Round 6?",
      options: [
        { id: "a", text: "Japão", isCorrect: false },
        { id: "b", text: "Coreia do Sul", isCorrect: true },
        { id: "c", text: "China", isCorrect: false },
        { id: "d", text: "Tailândia", isCorrect: false },
      ],
      explanation: "Round 6 é uma produção sul-coreana criada por Hwang Dong-hyuk e se tornou a série mais assistida da Netflix.",
    },
    {
      id: "q15",
      text: "Quantas temporadas Round 6 tem (até 2026)?",
      options: [
        { id: "a", text: "1", isCorrect: false },
        { id: "b", text: "2", isCorrect: true },
        { id: "c", text: "3", isCorrect: false },
        { id: "d", text: "4", isCorrect: false },
      ],
      explanation: "Até 2026, Round 6 tem 2 temporadas: a primeira lançada em 2021 e a segunda em 2024.",
    },
  ],
};
