import type { Quiz } from "@/lib/types";

export const timesBrasileiros: Quiz = {
  id: "times-brasileiros",
  slug: "quanto-voce-sabe-sobre-os-times-brasileiros",
  title: "Quanto você sabe sobre os times brasileiros?",
  description:
    "De Flamengo a Grêmio, de Corinthians a Bahia. Teste seus conhecimentos sobre o futebol brasileiro! 3 erros e você está fora.",
  type: "trivia",
  category: "esportes",
  emoji: "⚽",
  color: "#F59E0B",
  tags: ["futebol brasileiro", "times", "brasileirao", "esportes"],
  createdAt: "2026-06-08",
  featured: true,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "CBF — Campeonato Brasileiro Série A", url: "https://www.cbf.com.br/", organization: "CBF", accessedAt: "2026-07-12" },
    { label: "CONMEBOL — Libertadores", organization: "CONMEBOL", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Títulos, rivalidades, ídolos e estádios — perguntas sobre os grandes clubes do futebol brasileiro, da Série A aos clássicos regionais.",
  questions: [
    {
      id: "q1",
      text: "Qual time brasileiro tem mais títulos do Campeonato Brasileiro?",
      options: [
        { id: "a", text: "Santos", isCorrect: false },
        { id: "b", text: "Palmeiras", isCorrect: true },
        { id: "c", text: "Flamengo", isCorrect: false },
        { id: "d", text: "Corinthians", isCorrect: false },
      ],
      explanation: "O Palmeiras é o maior campeão brasileiro, com mais de dez títulos do Campeonato Brasileiro na contagem oficial da CBF.",
    },
    {
      id: "q2",
      text: "Qual o estádio do Flamengo?",
      options: [
        { id: "a", text: "Maracanã", isCorrect: true },
        { id: "b", text: "Engenhão", isCorrect: false },
        { id: "c", text: "São Januário", isCorrect: false },
        { id: "d", text: "Ilha do Urubu", isCorrect: false },
      ],
      explanation: "O Flamengo manda seus jogos no Maracanã, maior estádio do Brasil.",
    },
    {
      id: "q3",
      text: "Qual time é conhecido como 'Timão'?",
      options: [
        { id: "a", text: "São Paulo", isCorrect: false },
        { id: "b", text: "Palmeiras", isCorrect: false },
        { id: "c", text: "Corinthians", isCorrect: true },
        { id: "d", text: "Santos", isCorrect: false },
      ],
      explanation: "Timão é o apelido carinhoso do Corinthians, fundado em 1910 no bairro do Bom Retiro, em São Paulo.",
    },
    {
      id: "q4",
      text: "Quantas Libertadores o Flamengo conquistou?",
      options: [
        { id: "a", text: "2", isCorrect: false },
        { id: "b", text: "3", isCorrect: true },
        { id: "c", text: "4", isCorrect: false },
        { id: "d", text: "1", isCorrect: false },
      ],
      explanation: "O Flamengo venceu a Libertadores em 1981, 2019 e 2022.",
    },
    {
      id: "q5",
      text: "Qual time paulista é chamado de 'Verdão'?",
      options: [
        { id: "a", text: "Santos", isCorrect: false },
        { id: "b", text: "São Paulo", isCorrect: false },
        { id: "c", text: "Palmeiras", isCorrect: true },
        { id: "d", text: "Guarani", isCorrect: false },
      ],
      explanation: "Verdão é o apelido do Palmeiras por causa das cores verde e branco do clube, fundado em 1914.",
    },
    {
      id: "q6",
      text: "Em que ano o Corinthians ganhou o Mundial de Clubes?",
      options: [
        { id: "a", text: "2010", isCorrect: false },
        { id: "b", text: "2012", isCorrect: true },
        { id: "c", text: "2011", isCorrect: false },
        { id: "d", text: "2013", isCorrect: false },
      ],
      explanation: "O Corinthians venceu o Chelsea por 1x0 na final em Yokohama, gol de Guerrero.",
    },
    {
      id: "q7",
      text: "Qual o clássico entre Flamengo e Fluminense?",
      options: [
        { id: "a", text: "Clássico dos Milhões", isCorrect: false },
        { id: "b", text: "Fla-Flu", isCorrect: true },
        { id: "c", text: "Clássico da Rivalidade", isCorrect: false },
        { id: "d", text: "Derby Carioca", isCorrect: false },
      ],
      explanation: "O Fla-Flu é um dos clássicos mais tradicionais do futebol brasileiro, disputado desde 1912.",
    },
    {
      id: "q8",
      text: "Qual time gaúcho é conhecido como 'Tricolor'?",
      options: [
        { id: "a", text: "Internacional", isCorrect: false },
        { id: "b", text: "Grêmio", isCorrect: true },
        { id: "c", text: "Juventude", isCorrect: false },
        { id: "d", text: "Caxias", isCorrect: false },
      ],
      explanation: "O Grêmio é chamado de Tricolor por suas cores azul, preto e branco. O Inter é o Colorado (vermelho).",
    },
    {
      id: "q9",
      text: "Pelé fez a maior parte de sua carreira em qual time?",
      options: [
        { id: "a", text: "Corinthians", isCorrect: false },
        { id: "b", text: "São Paulo", isCorrect: false },
        { id: "c", text: "Santos", isCorrect: true },
        { id: "d", text: "Flamengo", isCorrect: false },
      ],
      explanation: "Pelé jogou no Santos de 1956 a 1974, marcando mais de 1.000 gols pelo clube.",
    },
    {
      id: "q10",
      text: "Qual time brasileiro nunca foi rebaixado para a Série B?",
      options: [
        { id: "a", text: "Flamengo", isCorrect: false },
        { id: "b", text: "Santos", isCorrect: false },
        { id: "c", text: "São Paulo", isCorrect: true },
        { id: "d", text: "Palmeiras", isCorrect: false },
      ],
      explanation: "O São Paulo é o único grande que nunca caiu para a segunda divisão.",
    },
    {
      id: "q11",
      text: "Qual time mineiro é chamado de 'Galo'?",
      options: [
        { id: "a", text: "Cruzeiro", isCorrect: false },
        { id: "b", text: "Atlético Mineiro", isCorrect: true },
        { id: "c", text: "América Mineiro", isCorrect: false },
        { id: "d", text: "Atlético Goianiense", isCorrect: false },
      ],
      explanation: "O Atlético Mineiro é chamado de Galo por causa do mascote, um galo carijó. Foi campeão da Libertadores em 2013.",
    },
    {
      id: "q12",
      text: "Em que ano o Palmeiras ganhou sua primeira Libertadores?",
      options: [
        { id: "a", text: "1999", isCorrect: true },
        { id: "b", text: "2000", isCorrect: false },
        { id: "c", text: "2020", isCorrect: false },
        { id: "d", text: "1995", isCorrect: false },
      ],
      explanation: "O Palmeiras venceu o Deportivo Cali na final de 1999. Depois conquistou novamente em 2020 e 2021.",
    },
    {
      id: "q13",
      text: "Qual o maior artilheiro da história do Campeonato Brasileiro?",
      options: [
        { id: "a", text: "Romário", isCorrect: false },
        { id: "b", text: "Zico", isCorrect: false },
        { id: "c", text: "Roberto Dinamite", isCorrect: true },
        { id: "d", text: "Edmundo", isCorrect: false },
      ],
      explanation: "Roberto Dinamite marcou 190 gols no Brasileirão, pelo Vasco da Gama.",
    },
    {
      id: "q14",
      text: "O estádio 'Beira-Rio' pertence a qual time?",
      options: [
        { id: "a", text: "Grêmio", isCorrect: false },
        { id: "b", text: "Internacional", isCorrect: true },
        { id: "c", text: "Atlético Paranaense", isCorrect: false },
        { id: "d", text: "Coritiba", isCorrect: false },
      ],
      explanation: "O Beira-Rio é a casa do Internacional desde 1969, com capacidade para mais de 50 mil torcedores.",
    },
    {
      id: "q15",
      text: "Qual time nordestino tem mais títulos do Brasileirão?",
      options: [
        { id: "a", text: "Sport", isCorrect: false },
        { id: "b", text: "Bahia", isCorrect: true },
        { id: "c", text: "Fortaleza", isCorrect: false },
        { id: "d", text: "Náutico", isCorrect: false },
      ],
      explanation: "O Bahia venceu o Brasileirão em 1959 e 1988.",
    },
    {
      id: "q16",
      text: "Qual time é conhecido como 'Mengão'?",
      options: [
        { id: "a", text: "Vasco", isCorrect: false },
        { id: "b", text: "Botafogo", isCorrect: false },
        { id: "c", text: "Flamengo", isCorrect: true },
        { id: "d", text: "Fluminense", isCorrect: false },
      ],
      explanation: "Mengão é uma variação carinhosa de Flamengo, o clube com a maior torcida do Brasil.",
    },
    {
      id: "q17",
      text: "Quantas vezes o Santos ganhou a Libertadores?",
      options: [
        { id: "a", text: "2 vezes", isCorrect: false },
        { id: "b", text: "3 vezes", isCorrect: true },
        { id: "c", text: "4 vezes", isCorrect: false },
        { id: "d", text: "1 vez", isCorrect: false },
      ],
      explanation: "O Santos venceu em 1962, 1963 e 2011.",
    },
    {
      id: "q18",
      text: "O clássico 'Grenal' é entre quais times?",
      options: [
        { id: "a", text: "Grêmio x Internacional", isCorrect: true },
        { id: "b", text: "Grêmio x Juventude", isCorrect: false },
        { id: "c", text: "Inter x Caxias", isCorrect: false },
        { id: "d", text: "Grêmio x Coritiba", isCorrect: false },
      ],
      explanation: "O Grenal é o maior clássico do sul do Brasil, disputado desde 1909 entre Grêmio e Internacional.",
    },
    {
      id: "q19",
      text: "Qual time brasileiro tem a maior torcida do país?",
      options: [
        { id: "a", text: "Corinthians", isCorrect: false },
        { id: "b", text: "Flamengo", isCorrect: true },
        { id: "c", text: "São Paulo", isCorrect: false },
        { id: "d", text: "Palmeiras", isCorrect: false },
      ],
      explanation: "O Flamengo tem a maior torcida do Brasil, estimada em mais de 40 milhões.",
    },
    {
      id: "q20",
      text: "Qual time ganhou a primeira edição da Copa do Brasil em 1989?",
      options: [
        { id: "a", text: "Flamengo", isCorrect: false },
        { id: "b", text: "Grêmio", isCorrect: true },
        { id: "c", text: "Cruzeiro", isCorrect: false },
        { id: "d", text: "Palmeiras", isCorrect: false },
      ],
      explanation: "O Grêmio venceu o Sport na final da primeira Copa do Brasil, em 1989.",
    },
  ],
};
