import type { Quiz } from "@/lib/types";

export const vestibular1990: Quiz = {
  id: "vestibular-1990",
  slug: "voce-passaria-no-vestibular-de-1990",
  title: "Você Passaria no Vestibular de 1990?",
  description: "Perguntas reais de vestibulares dos anos 90 — será que você passaria?",
  type: "trivia",
  category: "conhecimentos-gerais",
  emoji: "📚",
  color: "#D97706",
  tags: ["vestibular", "educacao", "enem", "historia", "nostalgia"],
  createdAt: "2026-06-11",
  featured: false,
  author: "Equipe Editorial MegaQuiz",
  authorBio: "Conteúdo produzido e revisado pela equipe responsável pelo MegaQuiz, com consulta às fontes indicadas em cada publicação.",
  sources: [
    { label: "Questões de vestibulares brasileiros (anos 1990)", organization: "Universidades brasileiras", accessedAt: "2026-07-12" },
  ],
  lastReviewedAt: "2026-07-12",
  introText: "Perguntas reais de vestibulares dos anos 90. Será que você passaria naquela época?",
  questions: [
    {
      id: "q1",
      text: "Qual foi o regime político do Brasil entre 1964 e 1985?",
      options: [
        { id: "a", text: "Monarquia", isCorrect: false },
        { id: "b", text: "Ditadura militar", isCorrect: true },
        { id: "c", text: "República parlamentarista", isCorrect: false },
        { id: "d", text: "Anarquia", isCorrect: false },
      ],
      explanation: "A ditadura militar brasileira durou 21 anos, com 5 presidentes militares e restrição de liberdades civis.",
    },
    {
      id: "q2",
      text: "Qual é a fórmula da água?",
      options: [
        { id: "a", text: "CO2", isCorrect: false },
        { id: "b", text: "H2O", isCorrect: true },
        { id: "c", text: "NaCl", isCorrect: false },
        { id: "d", text: "O2", isCorrect: false },
      ],
      explanation: "H2O significa dois átomos de hidrogênio ligados a um de oxigênio — a molécula mais essencial para a vida.",
    },
    {
      id: "q3",
      text: "Quem escreveu 'Dom Casmurro'?",
      options: [
        { id: "a", text: "José de Alencar", isCorrect: false },
        { id: "b", text: "Machado de Assis", isCorrect: true },
        { id: "c", text: "Monteiro Lobato", isCorrect: false },
        { id: "d", text: "Castro Alves", isCorrect: false },
      ],
      explanation: "Machado de Assis é considerado o maior escritor brasileiro. Dom Casmurro (1899) traz a famosa dúvida: Capitu traiu ou não?",
    },
    {
      id: "q4",
      text: "Qual é a raiz quadrada de 144?",
      options: [
        { id: "a", text: "10", isCorrect: false },
        { id: "b", text: "12", isCorrect: true },
        { id: "c", text: "14", isCorrect: false },
        { id: "d", text: "16", isCorrect: false },
      ],
      explanation: "12 x 12 = 144, portanto a raiz quadrada de 144 é 12.",
    },
    {
      id: "q5",
      text: "Em que ano caiu o Muro de Berlim?",
      options: [
        { id: "a", text: "1987", isCorrect: false },
        { id: "b", text: "1989", isCorrect: true },
        { id: "c", text: "1991", isCorrect: false },
        { id: "d", text: "1993", isCorrect: false },
      ],
      explanation: "O Muro de Berlim caiu em 9 de novembro de 1989, marcando o fim simbólico da Guerra Fria.",
    },
    {
      id: "q6",
      text: "Qual é o maior osso do corpo humano?",
      options: [
        { id: "a", text: "Tíbia", isCorrect: false },
        { id: "b", text: "Fêmur", isCorrect: true },
        { id: "c", text: "Úmero", isCorrect: false },
        { id: "d", text: "Costela", isCorrect: false },
      ],
      explanation: "O fêmur é o osso mais longo e resistente do corpo humano, localizado na coxa.",
    },
    {
      id: "q7",
      text: "Qual é a capital da Austrália?",
      options: [
        { id: "a", text: "Sydney", isCorrect: false },
        { id: "b", text: "Melbourne", isCorrect: false },
        { id: "c", text: "Canberra", isCorrect: true },
        { id: "d", text: "Brisbane", isCorrect: false },
      ],
      explanation: "A maioria erra essa! Canberra foi construída como capital de compromisso entre Sydney e Melbourne.",
    },
    {
      id: "q8",
      text: "O que é mitose?",
      options: [
        { id: "a", text: "Divisão celular que gera células idênticas", isCorrect: true },
        { id: "b", text: "Processo de digestão de proteínas", isCorrect: false },
        { id: "c", text: "Reação química do sangue", isCorrect: false },
        { id: "d", text: "Processo de fotossíntese", isCorrect: false },
      ],
      explanation: "A mitose produz duas células geneticamente idênticas. A meiose, diferente, gera células com metade dos cromossomos.",
    },
    {
      id: "q9",
      text: "Quem pintou a Mona Lisa?",
      options: [
        { id: "a", text: "Michelangelo", isCorrect: false },
        { id: "b", text: "Leonardo da Vinci", isCorrect: true },
        { id: "c", text: "Rafael", isCorrect: false },
        { id: "d", text: "Van Gogh", isCorrect: false },
      ],
      explanation: "Leonardo da Vinci pintou a Mona Lisa entre 1503 e 1519. Hoje ela está no Museu do Louvre, em Paris.",
    },
    {
      id: "q10",
      text: "Qual é o resultado de 3² + 4²?",
      options: [
        { id: "a", text: "14", isCorrect: false },
        { id: "b", text: "25", isCorrect: true },
        { id: "c", text: "49", isCorrect: false },
        { id: "d", text: "7", isCorrect: false },
      ],
      explanation: "3² = 9 e 4² = 16. Portanto 9 + 16 = 25. É também o famoso triângulo pitagórico 3-4-5!",
    },
    {
      id: "q11",
      text: "Qual tratado dividiu o mundo entre Portugal e Espanha em 1494?",
      options: [
        { id: "a", text: "Tratado de Versalhes", isCorrect: false },
        { id: "b", text: "Tratado de Tordesilhas", isCorrect: true },
        { id: "c", text: "Tratado de Madrid", isCorrect: false },
        { id: "d", text: "Tratado de Utrecht", isCorrect: false },
      ],
      explanation: "O Tratado de Tordesilhas (1494) dividiu o mundo entre Portugal e Espanha com uma linha a 370 léguas de Cabo Verde.",
    },
    {
      id: "q12",
      text: "Qual é o gás responsável pelo efeito estufa?",
      options: [
        { id: "a", text: "Oxigênio (O2)", isCorrect: false },
        { id: "b", text: "Nitrogênio (N2)", isCorrect: false },
        { id: "c", text: "Gás carbônico (CO2)", isCorrect: true },
        { id: "d", text: "Hélio (He)", isCorrect: false },
      ],
      explanation: "O CO2 é o principal gás de efeito estufa emitido por atividades humanas, especialmente queima de combustíveis fósseis.",
    },
    {
      id: "q13",
      text: "Quem foi o líder da Revolução Francesa que foi guilhotinado?",
      options: [
        { id: "a", text: "Napoleão Bonaparte", isCorrect: false },
        { id: "b", text: "Robespierre", isCorrect: true },
        { id: "c", text: "Voltaire", isCorrect: false },
        { id: "d", text: "Luís XVI", isCorrect: false },
      ],
      explanation: "Tanto Luís XVI quanto Robespierre foram guilhotinados, mas Robespierre foi o líder revolucionário que acabou vítima do próprio Terror.",
    },
    {
      id: "q14",
      text: "Qual é o sinônimo de 'prodigioso'?",
      options: [
        { id: "a", text: "Preguiçoso", isCorrect: false },
        { id: "b", text: "Extraordinário", isCorrect: true },
        { id: "c", text: "Perigoso", isCorrect: false },
        { id: "d", text: "Produtivo", isCorrect: false },
      ],
      explanation: "Prodigioso vem do latim 'prodigiosus' e significa algo extraordinário, espantoso ou fora do comum.",
    },
    {
      id: "q15",
      text: "Se um trem viaja a 120 km/h, quantos km percorre em 45 minutos?",
      options: [
        { id: "a", text: "80 km", isCorrect: false },
        { id: "b", text: "90 km", isCorrect: true },
        { id: "c", text: "100 km", isCorrect: false },
        { id: "d", text: "60 km", isCorrect: false },
      ],
      explanation: "120 km/h dividido por 60 = 2 km por minuto. Em 45 minutos: 2 x 45 = 90 km.",
    },
  ],
};
